# SPDX-License-Identifier: FSL-1.1-ALv2
# Stable options only; used by `cargo fmt` and Bazel's rustfmt_test.
edition = "2024"
style_edition = "2024"
max_width = 100
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
