// SPDX-License-Identifier: FSL-1.1-ALv2

//! Generated protobuf messages ([`proto`], buffa) and RPC stubs ([`connect`],
//! connect-rust) used by `cucinactl` (ADR 0003), laid out by protobuf package:
//!
//! * `cucina::v1` — the Cucina management API (`api/proto/cucina/v1`).
//! * `build::bazel::remote::execution::v2` — REAPI v2 (CAS, AC, Capabilities),
//!   vendored from `bazelbuild/remote-apis` at the commit bb-storage pins.
//! * `buildbarn::cas` — `HistoricalExecuteResponse` (uncached results bb_worker
//!   stores in the CAS), vendored from bb-remote-execution.
//! * `google::bytestream`, `google::longrunning`, `google::rpc` — googleapis
//!   dependencies of REAPI.
//!
//! The code under `src/gen/` is generated by `cargo xtask codegen` and checked in;
//! never edit it by hand.

#[allow(
    clippy::all,
    clippy::pedantic,
    missing_docs,
    rustdoc::all,
    unreachable_pub,
    unused_qualifications,
    unused_imports,
    dead_code,
    non_camel_case_types
)]
// rustfmt::skip: the files are checked in byte-for-byte as generated (drift checks).
#[rustfmt::skip]
#[path = "gen/buffa/mod.rs"]
pub mod proto;

#[allow(
    clippy::all,
    clippy::pedantic,
    missing_docs,
    rustdoc::all,
    unreachable_pub,
    unused_qualifications,
    unused_imports,
    dead_code,
    refining_impl_trait_internal,
    refining_impl_trait_reachable
)]
#[rustfmt::skip]
#[path = "gen/connect/mod.rs"]
pub mod connect;

/// Version of the management API / hostd protocol this client speaks
/// (`ProtocolVersion` in `common.proto`): major 1, minor 0.
pub const PROTOCOL_MAJOR: u32 = 1;
/// See [`PROTOCOL_MAJOR`].
pub const PROTOCOL_MINOR: u32 = 0;
