# SPDX-License-Identifier: FSL-1.1-ALv2
"""Module extension providing the exec-side replacement for hermetic-llvm's `@macos_sdk` (R-XPLAT-8).

Root MODULE.bazel (only the root module may override another extension's repositories):

    osx = use_extension("@llvm//extensions:osx.bzl", "osx")
    apple = use_extension("@cucina_platforms//apple:extensions.bzl", "apple")
    use_repo(apple, "cucina_macos_exec_sdk")
    override_repo(osx, macos_sdk = "cucina_macos_exec_sdk")

hermetic-llvm (toolchains, module map) and rules_rs then see `@macos_sdk//sysroot` as the SDK on the
macOS exec machine, and Apple's SDK package is never downloaded by any client. Pair it with
`--@rules_rust//rust/settings:use_hermetic_macos_sdkroot=false` (rules_rs would otherwise ask the
sysroot for exactly one file); docs/cross-compilation.md has the complete set of lines.
"""

_SYSROOT_BUILD = """\
# Generated by @cucina_platforms//apple:extensions.bzl. The macOS SDK is NOT in this repository:
# it is resolved on the macOS exec machine (R-XPLAT-8, docs/cross-compilation.md).
load("{exec_sdk_bzl}", "exec_macos_sdk")

exec_macos_sdk(
    name = "sysroot",
    visibility = ["//visibility:public"],
)
"""

def _exec_sdk_repo_impl(rctx):
    rctx.file("BUILD.bazel", "")
    rctx.file("sysroot/BUILD.bazel", _SYSROOT_BUILD.format(
        exec_sdk_bzl = str(Label(":exec_sdk.bzl")),
    ))

    # The content depends only on this module's labels: eligible for the repo contents cache.
    return rctx.repo_metadata(reproducible = True)

_exec_sdk_repo = repository_rule(
    implementation = _exec_sdk_repo_impl,
    doc = "A stand-in for @macos_sdk whose //sysroot is the SDK on the macOS exec machine.",
)

def _apple_impl(mctx):
    _exec_sdk_repo(name = "cucina_macos_exec_sdk")
    return mctx.extension_metadata(
        root_module_direct_deps = ["cucina_macos_exec_sdk"],
        root_module_direct_dev_deps = [],
        reproducible = True,
    )

apple = module_extension(
    implementation = _apple_impl,
    doc = "Creates @cucina_macos_exec_sdk, the exec-side macOS SDK used to override @macos_sdk.",
)
