# SPDX-License-Identifier: FSL-1.1-ALv2
# Rotation of the Buildbarn service logs inside macOS worker VMs (installed as /etc/newsyslog.d/cucina.conf).
# N: launchd owns the processes (no pid file to signal); they reopen their log when hostd re-bootstraps them.
# logfilename                        [owner:group]          mode count size(KB) when flags
/var/log/cucina/bb_worker.log        @BUILD_USER@:staff     644  3     51200    *    JN
/var/log/cucina/bb_runner.log        @BUILD_USER@:staff     644  3     51200    *    JN
