# SPDX-License-Identifier: FSL-1.1-ALv2
# Installed as /etc/ssh/sshd_config.d/000-cucina.conf (sshd uses the first value it reads, so this file sorts first).
# Management of worker VMs is `tart exec` (Tart Guest Agent). SSH stays available for keys a host installs per VM,
# never for passwords: the Cirrus base's admin/admin credentials are rotated at image build and unusable remotely.
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
PermitEmptyPasswords no
