# Code generated by //tools/xplat from platforms/pools.json and platforms/targets.json. DO NOT EDIT.
# Regenerate: bazel run //tools/xplat:update. Design: docs/cross-compilation.md.
"""Runner property sets and the target matrix, for macros and rules of @cucina_platforms."""

# Pool -> runner -> exact REAPI property set (platforms/pools.json).
RUNNERS = {
    "linux-aarch64": {
        "native": {
            "ISA": "arm-a64",
            "OSFamily": "linux",
        },
    },
    "linux-x86-64": {
        "native": {
            "ISA": "x86-64",
            "OSFamily": "linux",
        },
        "qemu-arm-a32": {
            "ISA": "arm-a32",
            "OSFamily": "linux",
            "cucina-emulation": "qemu",
        },
        "qemu-rv64g": {
            "ISA": "rv64g",
            "OSFamily": "linux",
            "cucina-emulation": "qemu",
        },
        "qemu-s390x": {
            "ISA": "s390x",
            "OSFamily": "linux",
            "cucina-emulation": "qemu",
        },
    },
    "macos-arm64-xcode27.0": {
        "generic": {
            "ISA": "arm-a64",
            "OSFamily": "macos",
        },
        "xcode": {
            "ISA": "arm-a64",
            "OSFamily": "macos",
            "xcode-version": "27.0",
        },
    },
    "windows-x86-64": {
        "native": {
            "ISA": "x86-64",
            "OSFamily": "windows",
        },
    },
}

# Compile exec platforms in default preference order (UC25).
EXEC_PLATFORMS = [
    "@cucina_platforms//exec:linux-x86-64-native",
    "@cucina_platforms//exec:linux-aarch64-native",
    "@cucina_platforms//exec:windows-x86-64-native",
    "@cucina_platforms//exec:macos-arm64-xcode27.0-xcode",
]

# hermetic-llvm target platform -> its test exec platform.
TEST_PLATFORMS = {
    "@llvm//platforms:macos_aarch64": "@cucina_platforms//test:test_on_macos_aarch64",
    "@llvm//platforms:linux_x86_64_gnu.2.28": "@cucina_platforms//test:test_on_linux_x86_64_gnu.2.28",
    "@llvm//platforms:linux_x86_64_musl": "@cucina_platforms//test:test_on_linux_x86_64_musl",
    "@llvm//platforms:linux_aarch64_gnu.2.28": "@cucina_platforms//test:test_on_linux_aarch64_gnu.2.28",
    "@llvm//platforms:linux_aarch64_musl": "@cucina_platforms//test:test_on_linux_aarch64_musl",
    "@llvm//platforms:linux_riscv64_gnu.2.33": "@cucina_platforms//test:test_on_linux_riscv64_gnu.2.33",
    "@llvm//platforms:linux_riscv64_musl": "@cucina_platforms//test:test_on_linux_riscv64_musl",
    "@llvm//platforms:linux_s390x_gnu.2.28": "@cucina_platforms//test:test_on_linux_s390x_gnu.2.28",
    "@llvm//platforms:linux_s390x_musl": "@cucina_platforms//test:test_on_linux_s390x_musl",
    "@llvm//platforms:linux_armv7_gnu.2.28": "@cucina_platforms//test:test_on_linux_armv7_gnu.2.28",
    "@llvm//platforms:linux_armv7_musl": "@cucina_platforms//test:test_on_linux_armv7_musl",
    "@llvm//platforms:windows_x86_64_msvc": "@cucina_platforms//test:test_on_windows_x86_64_msvc",
    "@llvm//platforms:windows_x86_64": "@cucina_platforms//test:test_on_windows_x86_64",
}
