#!/bin/sh
# SPDX-License-Identifier: FSL-1.1-ALv2
# Builds the Cucina host distribution package (R-MAC-8): stage payload -> [codesign Mach-O] -> pkgbuild component
# -> productbuild distribution [--sign]. Unsigned by default, so it runs on any macOS worker (Bazel genrule entry
# point, R-BUILD-1 "macOS pkg"); signing (scripts/sign.sh) re-runs it with an identity from a local keychain.
# Never re-signs tart.app (its restricted com.apple.vm.networking entitlement depends on Cirrus Labs' signature).
# Deterministic inputs only: every upstream file is passed in (or taken from fetch-deps.sh's verified cache).
#
# usage: build-pkg.sh --hostd PATH --version X.Y.Z --out FILE.pkg [options]
#   --hostd PATH             cucina-hostd darwin/arm64 Mach-O (bazel: //cmd/cucina-hostd)
#   --bb-storage PATH        bb_storage darwin/arm64 (default: verified cache of fetch-deps.sh)
#   --tart-tarball PATH      official Tart release tarball (default: verified cache of fetch-deps.sh)
#   --license PATH           LICENSE.md (default: <repo>/LICENSE.md)
#   --notices PATH           THIRD_PARTY_NOTICES.md (default: <repo>/THIRD_PARTY_NOTICES.md)
#   --version X.Y.Z          package version (MAJOR.MINOR.PATCH)
#   --out FILE               output product archive
#   --work DIR               scratch directory (default: a fresh temporary directory, removed afterwards)
#   --sign-identity ID       codesign identity for cucina-hostd and bb_storage (private cert or Developer ID App)
#   --installer-identity ID  productbuild --sign identity (default: --sign-identity)
#   --keychain PATH          keychain holding the identities (default: search list)
#   --no-timestamp           do not request secure timestamps (offline test builds only)
#   --uninstall              build the payload-free uninstaller package instead (ai.sloper.cucina.host.uninstall)
#   --uninstall-args "ARGS"  arguments baked into the uninstaller (e.g. "--purge"); default: none
set -eu

. "$(dirname -- "$0")/lib.sh"
PKG_DIR=$(cucina_pkg_dir)
REPO_DIR=$(CDPATH='' cd -- "$PKG_DIR/../.." && pwd -P)
cucina_load_pins "$PKG_DIR/pins.env"

hostd='' bb_storage='' tart_tarball='' version='' out='' work='' sign_id='' installer_id='' keychain=''
license=$REPO_DIR/LICENSE.md
notices=$REPO_DIR/THIRD_PARTY_NOTICES.md
timestamp=1 uninstall=0 uninstall_args=''
while [ $# -gt 0 ]; do
	case $1 in
	--hostd) hostd=$2 && shift 2 ;;
	--bb-storage) bb_storage=$2 && shift 2 ;;
	--tart-tarball) tart_tarball=$2 && shift 2 ;;
	--license) license=$2 && shift 2 ;;
	--notices) notices=$2 && shift 2 ;;
	--version) version=$2 && shift 2 ;;
	--out) out=$2 && shift 2 ;;
	--work) work=$2 && shift 2 ;;
	--sign-identity) sign_id=$2 && shift 2 ;;
	--installer-identity) installer_id=$2 && shift 2 ;;
	--keychain) keychain=$2 && shift 2 ;;
	--no-timestamp) timestamp=0 && shift ;;
	--uninstall) uninstall=1 && shift ;;
	--uninstall-args) uninstall_args=$2 && shift 2 ;;
	-h | --help) sed -n '2,/^set -eu/p' "$0" | sed '$d' && exit 0 ;;
	*) cucina_die "unknown argument: $1 (try --help)" ;;
	esac
done

cucina_need pkgbuild productbuild pkgutil lsbom mkbom shasum plutil tar gzip codesign xattr lipo
[ -n "$version" ] || cucina_die "--version is required"
cucina_validate_version "$version"
[ -n "$out" ] || cucina_die "--out is required"
[ -n "$installer_id" ] || installer_id=$sign_id
out=$(cucina_abspath "$out")
mkdir -p "$(dirname -- "$out")"

cleanup_work=0
if [ -z "$work" ]; then
	work=$(mktemp -d "${TMPDIR:-/tmp}/cucina-pkg.XXXXXX")
	cleanup_work=1
fi
work=$(cucina_abspath "$work")
cleanup() { [ "$cleanup_work" = 0 ] || rm -rf "$work"; }
trap cleanup EXIT INT TERM
rm -rf "$work/stage" "$work/scripts" "$work/components"
mkdir -p "$work/stage" "$work/scripts" "$work/components"

# productbuild_dist PKG_ID TITLE COMPONENT_FILE — writes the distribution and the product archive.
productbuild_dist() {
	sed -e "s|@PKG_ID@|$1|g" -e "s|@TITLE@|$2|g" -e "s|@VERSION@|$version|g" \
		-e "s|@MIN_MACOS@|$CUCINA_MIN_MACOS|g" -e "s|@COMPONENT@|$3|g" \
		"$PKG_DIR/resources/distribution.xml.in" >"$work/distribution.xml"
	set -- --distribution "$work/distribution.xml" --package-path "$work/components"
	if [ -n "$installer_id" ]; then
		set -- "$@" --sign "$installer_id"
		[ -z "$keychain" ] || set -- "$@" --keychain "$keychain"
		if [ "$timestamp" = 1 ]; then set -- "$@" --timestamp; else set -- "$@" --timestamp=none; fi
	fi
	rm -f "$out"
	productbuild --quiet "$@" "$out"
}

if [ "$uninstall" = 1 ]; then
	# Payload-free uninstaller: Scripts/postinstall runs the embedded copy of cucina-host-uninstall.
	cp "$PKG_DIR/payload/cucina-host-uninstall" "$work/scripts/cucina-host-uninstall"
	cat >"$work/scripts/postinstall" <<EOF
#!/bin/sh
# SPDX-License-Identifier: FSL-1.1-ALv2
# Cucina host uninstaller $version (generated by macos/pkg/scripts/build-pkg.sh).
exec "\$(dirname -- "\$0")/cucina-host-uninstall" --yes $uninstall_args
EOF
	chmod 0755 "$work/scripts/postinstall" "$work/scripts/cucina-host-uninstall"
	pkgbuild --quiet --nopayload --scripts "$work/scripts" --identifier "$CUCINA_UNINSTALL_PKG_ID" \
		--version "$version" "$work/components/cucina-host-uninstall-component.pkg"
	productbuild_dist "$CUCINA_UNINSTALL_PKG_ID" "Cucina host uninstaller" cucina-host-uninstall-component.pkg
	cucina_info "wrote $out ($(cucina_sha256 "$out"))"
	exit 0
fi

# --- inputs ---------------------------------------------------------------------------------------------------
[ -n "$hostd" ] || cucina_die "--hostd is required (bazel: //cmd/cucina-hostd; make: builds ./cmd/cucina-hostd)"
if [ -z "$bb_storage" ] || [ -z "$tart_tarball" ]; then
	deps=$("$PKG_DIR/scripts/fetch-deps.sh" --print)
	[ -n "$bb_storage" ] || bb_storage=$(printf '%s\n' "$deps" | sed -n 's/^BB_STORAGE_BIN=//p')
	[ -n "$tart_tarball" ] || tart_tarball=$(printf '%s\n' "$deps" | sed -n 's/^TART_TARBALL=//p')
fi
for f in "$hostd" "$bb_storage" "$tart_tarball" "$license"; do
	[ -f "$f" ] || cucina_die "missing input: $f"
done
[ -f "$notices" ] || cucina_die "missing $notices (THIRD_PARTY_NOTICES.md must ship in the pkg; pass --notices)"
cucina_verify_sha256 "$tart_tarball" "$TART_SHA256"
cucina_verify_sha256 "$bb_storage" "$BB_STORAGE_SHA256"
for bin in "$hostd" "$bb_storage"; do
	case $(lipo -archs "$bin" 2>/dev/null || true) in
	*arm64*) ;;
	*) cucina_die "$bin is not an arm64 Mach-O" ;;
	esac
done

# --- stage the payload (paths: docs/dev/hostd.md §2) ----------------------------------------------------------
S=$work/stage
P=$S/usr/local/cucina
install -d -m 0755 "$S/Library/LaunchDaemons" "$S/private/etc/newsyslog.d" "$P/bin" "$P/share/doc/tart" "$P/share/cucina"
install -m 0644 "$PKG_DIR/resources/ai.sloper.cucina.hostd.plist" "$S/Library/LaunchDaemons/$CUCINA_LABEL.plist"
install -m 0644 "$PKG_DIR/resources/newsyslog-ai.sloper.cucina.conf" "$S/private/etc/newsyslog.d/ai.sloper.cucina.conf"
install -m 0755 "$hostd" "$P/bin/cucina-hostd"
install -m 0755 "$bb_storage" "$P/bin/bb_storage"
install -m 0755 "$PKG_DIR/resources/tart-wrapper.sh" "$P/bin/tart"
install -m 0755 "$PKG_DIR/payload/cucina-host-setup" "$P/bin/cucina-host-setup"
install -m 0755 "$PKG_DIR/payload/cucina-host-uninstall" "$P/bin/cucina-host-uninstall"
install -m 0644 "$license" "$P/share/doc/LICENSE.md"
install -m 0644 "$notices" "$P/share/doc/THIRD_PARTY_NOTICES.md"
printf '%s\n' "$version" >"$P/VERSION"
chmod 0644 "$P/VERSION"
printf 'cucina-host=%s\ntart=%s\nbb_storage=%s\n' "$version" "$TART_VERSION" "$BB_STORAGE_RELEASE" >"$P/share/cucina/components"
chmod 0644 "$P/share/cucina/components"

# Tart: extract the official tarball as-is (tart.app + LICENSE), then prove it is untouched.
mkdir -p "$work/tart"
tar -xzf "$tart_tarball" -C "$work/tart"
if [ ! -d "$work/tart/tart.app" ] || [ ! -f "$work/tart/LICENSE" ]; then
	cucina_die "unexpected Tart tarball layout"
fi
cp -R "$work/tart/tart.app" "$P/tart.app"
install -m 0644 "$work/tart/LICENSE" "$P/share/doc/tart/LICENSE"
xattr -cr "$S"

verify_tart() { # APP
	codesign --verify --deep --strict "$1" || cucina_die "tart.app signature is not intact: $1"
	vt_info=$(codesign -dvvv "$1" 2>&1)
	printf '%s\n' "$vt_info" | grep -qx "TeamIdentifier=$TART_TEAM_ID" || cucina_die "tart.app TeamIdentifier changed"
	printf '%s\n' "$vt_info" | grep -qx "Identifier=$TART_BUNDLE_ID" || cucina_die "tart.app identifier changed"
	printf '%s\n' "$vt_info" | grep -qx "CDHash=$TART_CDHASH" || cucina_die "tart.app CDHash changed"
	codesign -d --entitlements - --xml "$1" 2>/dev/null | grep -q 'com.apple.vm.networking' ||
		cucina_die "tart.app lost its com.apple.vm.networking entitlement"
}
verify_tart "$P/tart.app"

# --- sign Cucina's own Mach-O binaries (never tart.app) --------------------------------------------------------
if [ -n "$sign_id" ]; then
	for pair in "cucina-hostd:ai.sloper.cucina.hostd" "bb_storage:ai.sloper.cucina.bb_storage"; do
		bin=${pair%%:*}
		ident=${pair#*:}
		set -- --force --sign "$sign_id" --options runtime --identifier "$ident"
		[ -z "$keychain" ] || set -- "$@" --keychain "$keychain"
		if [ "$timestamp" = 1 ]; then set -- "$@" --timestamp; else set -- "$@" --timestamp=none; fi
		codesign "$@" "$P/bin/$bin"
		codesign --verify --strict "$P/bin/$bin" || cucina_die "signature check failed for $bin"
	done
	verify_tart "$P/tart.app"
fi

# --- package --------------------------------------------------------------------------------------------------
# pkgbuild archives every extended attribute of the staged files as an AppleDouble "._name" payload entry. macOS
# attaches com.apple.provenance (which cannot be removed) to all files written by provenance-tracked processes
# (terminal apps, IDEs, Bazel, CI agents), so the raw payload would install "._*" files/xattrs on every host.
# strip_appledouble filters the payload archive and the BOM, then re-flattens the component (ADR 0750).
strip_appledouble() { # COMPONENT_PKG
	sa_x=$work/component-expanded
	rm -rf "$sa_x"
	pkgutil --expand "$1" "$sa_x"
	lsbom "$sa_x/Bom" | awk -F '\t' '{ n = $1; sub(/.*\//, "", n); if (n !~ /^\._/) print }' >"$work/bom.list"
	mkbom -i "$work/bom.list" "$sa_x/Bom.clean"
	mv -f "$sa_x/Bom.clean" "$sa_x/Bom"
	tar -c --format odc --no-mac-metadata --no-xattrs --exclude '._*' --exclude '*/._*' -f - "@$sa_x/Payload" |
		gzip -9 -n >"$sa_x/Payload.clean"
	mv -f "$sa_x/Payload.clean" "$sa_x/Payload"
	rm -rf "$sa_x/Scripts"
	mkdir "$sa_x/Scripts"
	cp -p "$work/scripts/preinstall" "$work/scripts/postinstall" "$sa_x/Scripts/"
	sa_n=$(wc -l <"$work/bom.list" | tr -d ' ')
	sed -E "s/numberOfFiles=\"[0-9]+\"/numberOfFiles=\"$sa_n\"/" "$sa_x/PackageInfo" >"$sa_x/PackageInfo.clean"
	mv -f "$sa_x/PackageInfo.clean" "$sa_x/PackageInfo"
	rm -f "$1"
	pkgutil --flatten "$sa_x" "$1"
	if tar -tf "$sa_x/Payload" | grep -q '\(^\|/\)\._'; then cucina_die "AppleDouble entries left in the payload"; fi
}

cp "$PKG_DIR/install-scripts/preinstall" "$PKG_DIR/install-scripts/postinstall" "$work/scripts/"
chmod 0755 "$work/scripts/preinstall" "$work/scripts/postinstall"
pkgbuild --quiet --root "$S" --component-plist "$PKG_DIR/resources/component.plist" --scripts "$work/scripts" \
	--identifier "$CUCINA_PKG_ID" --version "$version" --install-location / --ownership recommended \
	--compression legacy --min-os-version "$CUCINA_MIN_MACOS" "$work/components/cucina-host-component.pkg"
strip_appledouble "$work/components/cucina-host-component.pkg"
productbuild_dist "$CUCINA_PKG_ID" "$CUCINA_PKG_TITLE" cucina-host-component.pkg
cucina_info "wrote $out ($(cucina_sha256 "$out"))"
