// SPDX-License-Identifier: FSL-1.1-ALv2

// Package report renders the campaign report docs/reports/e2e-<date>.md from
// the scenario results (R-TEST-8d JSON): the NFR pass/fail table for every
// row of PROMPT §8, per-scenario results with numbers, the itemised cost
// against the §12 budget, the standing cost (NFR-C2), issues found and fixed
// (docs/reports/issues.md, maintained by the lead), the ADR index,
// limitations, and the tag-sweep output — with environment identifiers
// redacted (§12).
package report

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/sloper-ai/cucina/test/e2e/harness"
	"github.com/sloper-ai/cucina/test/e2e/nfr"
)

// Input is everything the report is built from.
type Input struct {
	Date    time.Time
	RunID   string
	Results []*harness.Result
	// Issues is the verbatim content of docs/reports/issues.md (may be empty).
	Issues string
	// ADRs are "NNNN — title" lines from docs/adr.
	ADRs []string
	// BudgetUSD is the campaign budget (§12).
	BudgetUSD float64
	// ExtraSpend is spend not attributed to scenarios (standing environment,
	// image builds, Fast Launch), itemised.
	ExtraSpend map[string]float64
}

// Render builds the markdown (not yet redacted).
func Render(in Input) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }
	w("<!-- SPDX-License-Identifier: FSL-1.1-ALv2 -->\n")
	w("<!-- Generated by `go run ./test/e2e/cmd/e2e report` from the scenario results; environment identifiers redacted. -->\n\n")
	w("# Cucina acceptance campaign — %s\n\n", in.Date.Format("2006-01-02"))
	counts := map[harness.Status]int{}
	for _, r := range in.Results {
		counts[r.Status]++
	}
	rows := nfr.Aggregate(in.Results)
	nc := map[nfr.Status]int{}
	for _, r := range rows {
		nc[r.Status]++
	}
	spent, items := spend(in)
	w("Run `%s` · %d scenarios: **%d pass**, %d fail, %d skip, %d error · NFRs: **%d pass**, %d fail, %d partial, %d not measured · spend **$%.2f** of $%.0f.\n\n",
		in.RunID, len(in.Results), counts[harness.StatusPass], counts[harness.StatusFail], counts[harness.StatusSkip], counts[harness.StatusError],
		nc[nfr.Pass], nc[nfr.Fail], nc[nfr.Partial], nc[nfr.NotMeasured], spent, in.BudgetUSD)

	w("## NFR results\n\n| NFR | Target | Status | Measured | Scenarios |\n| --- | --- | --- | --- | --- |\n")
	for _, r := range rows {
		from := strings.Join(r.From, ", ")
		if len(r.Missing) > 0 {
			from += "; missing: " + strings.Join(r.Missing, ", ")
		}
		w("| %s | %s | %s | %s | %s |\n", r.ID, esc(r.Target), statusBadge(string(r.Status)), esc(measurements(r.Measurements)), from)
	}

	w("\n## Scenarios\n\n| ID | Scenario | Status | Duration | Cost class | Measured $ |\n| --- | --- | --- | --- | --- | --- |\n")
	for _, r := range in.Results {
		w("| %s | %s | %s | %s | %s | %.2f |\n", r.ID, esc(r.Title), statusBadge(string(r.Status)), r.Duration.Round(time.Second), r.CostClass, r.Cost.MeasuredUSD)
	}
	for _, r := range in.Results {
		scenario(&b, r)
	}

	w("\n## Cost\n\nBudget (§12): $%.0f. Spent: $%.2f (%.0f%%).\n\n| Item | USD |\n| --- | --- |\n", in.BudgetUSD, spent, 100*spent/max(in.BudgetUSD, 1))
	keys := make([]string, 0, len(items))
	for k := range items {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		w("| %s | %.2f |\n", esc(k), items[k])
	}
	standing(&b, in.Results)

	w("\n## Issues found and fixed\n\n")
	if strings.TrimSpace(in.Issues) == "" {
		w("_No ledger (docs/reports/issues.md) was provided._\n")
	} else {
		w("%s\n", strings.TrimSpace(stripHeader(in.Issues)))
	}
	w("\n## ADRs\n\n")
	for _, a := range in.ADRs {
		w("- %s\n", a)
	}
	w("\n## Limitations\n\n")
	lim := limitations(in.Results, rows)
	if len(lim) == 0 {
		w("_None recorded._\n")
	}
	for _, l := range lim {
		w("- %s\n", esc(l))
	}
	w("\n## Tag sweep\n\n```text\n%s\n```\n", sweepOutput(in.Results))
	return b.String()
}

func statusBadge(s string) string {
	switch strings.ToUpper(s) {
	case "PASS":
		return "✅ PASS"
	case "FAIL":
		return "❌ FAIL"
	case "ERROR":
		return "⚠️ ERROR"
	case "SKIP":
		return "⏭ SKIP"
	}
	return s
}

func esc(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.ReplaceAll(s, "\n", " ")
}

func measurements(ms []harness.NFRResult) string {
	var parts []string
	for _, m := range ms {
		mark := "✓"
		if !m.Pass {
			mark = "✗"
		}
		parts = append(parts, fmt.Sprintf("%s %s: %s %s", mark, m.Subject, trimFloat(m.Measured), m.Unit))
	}
	if len(parts) > 6 {
		parts = append(parts[:6], fmt.Sprintf("… +%d", len(parts)-6))
	}
	return strings.Join(parts, "; ")
}

func trimFloat(f float64) string {
	s := fmt.Sprintf("%.3f", f)
	s = strings.TrimRight(strings.TrimRight(s, "0"), ".")
	if s == "" || s == "-" {
		return "0"
	}
	return s
}

func scenario(b *strings.Builder, r *harness.Result) {
	fmt.Fprintf(b, "\n### %s — %s\n\n%s · %s · cost class %s · $%.2f measured ($%.2f reserved)\n",
		r.ID, r.Title, statusBadge(string(r.Status)), r.Duration.Round(time.Second), r.CostClass, r.Cost.MeasuredUSD, r.Cost.EstimateUSD)
	if r.MeasurementScope != "" {
		fmt.Fprintf(b, "\nMeasurement scope: `%s`.\n", esc(r.MeasurementScope))
	}
	if r.SkipReason != "" {
		fmt.Fprintf(b, "\nSkipped: %s\n", r.SkipReason)
	}
	if r.Error != "" {
		fmt.Fprintf(b, "\nError: `%s`\n", oneLine(r.Error, 400))
	}
	if len(r.NFRs) > 0 {
		b.WriteString("\n| NFR | Subject | Measured | Target | Result |\n| --- | --- | --- | --- | --- |\n")
		for _, n := range r.NFRs {
			res := "pass"
			if !n.Pass {
				res = "**fail**"
			}
			if n.Unqualified != "" {
				res = "not qualified: " + esc(n.Unqualified)
			}
			fmt.Fprintf(b, "| %s | %s | %s %s | %s | %s |\n", n.ID, esc(n.Subject), trimFloat(n.Measured), n.Unit, esc(n.Target), res)
		}
	}
	if len(r.Checks) > 0 {
		b.WriteString("\n| Check | Kind | Value | Result |\n| --- | --- | --- | --- |\n")
		for _, c := range r.Checks {
			res := "pass"
			switch {
			case c.Skipped != "":
				res = "not run: " + c.Skipped
			case !c.Pass:
				res = "**fail** " + c.Detail
			}
			fmt.Fprintf(b, "| %s | %s | %s | %s |\n", esc(c.Name), c.Kind, esc(oneLine(c.Value, 120)), esc(oneLine(res, 200)))
		}
	}
	if len(r.Metrics) > 0 {
		keys := make([]string, 0, len(r.Metrics))
		for k := range r.Metrics {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		b.WriteString("\n<details><summary>Metrics</summary>\n\n| Metric | Value |\n| --- | --- |\n")
		for _, k := range keys {
			m := r.Metrics[k]
			fmt.Fprintf(b, "| %s | %s %s |\n", k, trimFloat(m.Value), m.Unit)
		}
		b.WriteString("\n</details>\n")
	}
	if len(r.Steps) > 0 {
		b.WriteString("\n<details><summary>Steps</summary>\n\n| Step | Duration | Error |\n| --- | --- | --- |\n")
		for _, s := range r.Steps {
			fmt.Fprintf(b, "| %s | %s | %s |\n", esc(s.Name), s.Duration.Round(time.Second), esc(oneLine(s.Error, 160)))
		}
		b.WriteString("\n</details>\n")
	}
	if len(r.Timeline) > 0 {
		tl := append([]harness.TimelineEvent(nil), r.Timeline...)
		sort.Slice(tl, func(i, j int) bool { return tl[i].At.Before(tl[j].At) })
		b.WriteString("\n<details><summary>Timeline</summary>\n\n| Time (UTC) | Subject | Event |\n| --- | --- | --- |\n")
		for i, e := range tl {
			if i == 60 {
				fmt.Fprintf(b, "| … | | %d more |\n", len(tl)-60)
				break
			}
			fmt.Fprintf(b, "| %s | %s | %s |\n", e.At.UTC().Format("15:04:05"), esc(e.Subject), esc(e.Event))
		}
		b.WriteString("\n</details>\n")
	}
	if len(r.Queries) > 0 {
		b.WriteString("\n<details><summary>PromQL used</summary>\n\n")
		seen := map[string]bool{}
		for _, q := range r.Queries {
			if seen[q.Query] {
				continue
			}
			seen[q.Query] = true
			fmt.Fprintf(b, "- `%s`%s → %s\n", strings.ReplaceAll(q.Query, "`", "'"), rangeSuffix(q.Range), esc(oneLine(q.Result, 160)))
		}
		b.WriteString("\n</details>\n")
	}
	for _, n := range r.Notes {
		fmt.Fprintf(b, "\n> %s\n", oneLine(n, 600))
	}
}

func rangeSuffix(r string) string {
	if r == "" {
		return ""
	}
	return " " + r
}

func oneLine(s string, n int) string {
	s = strings.Join(strings.Fields(s), " ")
	if len(s) > n {
		return s[:n] + "…"
	}
	return s
}

// spend sums measured scenario costs and extra items.
func spend(in Input) (float64, map[string]float64) {
	items := map[string]float64{}
	var total float64
	for _, r := range in.Results {
		for k, v := range r.Cost.Items {
			items[k] += v
		}
		total += r.Cost.MeasuredUSD
	}
	for k, v := range in.ExtraSpend {
		items[k] += v
		total += v
	}
	return total, items
}

func standing(b *strings.Builder, results []*harness.Result) {
	for _, r := range results {
		raw, ok := r.Values["standingCost"]
		if !ok {
			continue
		}
		bs, _ := json.Marshal(raw)
		var sc struct {
			Test []struct {
				Item        string
				USDPerMonth float64
			} `json:"test"`
			TestUSD    float64 `json:"testUSDPerMonth"`
			Production []struct {
				Item        string
				USDPerMonth float64
			} `json:"production"`
			ProductionUSD float64 `json:"productionUSDPerMonth"`
		}
		if json.Unmarshal(bs, &sc) != nil {
			continue
		}
		fmt.Fprintf(b, "\n### Standing cost per month (NFR-C2)\n\n| Topology | Item | USD/month |\n| --- | --- | --- |\n")
		for _, it := range sc.Test {
			fmt.Fprintf(b, "| test | %s | %.2f |\n", esc(it.Item), it.USDPerMonth)
		}
		fmt.Fprintf(b, "| **test total** | | **%.2f** |\n", sc.TestUSD)
		for _, it := range sc.Production {
			fmt.Fprintf(b, "| small production | %s | %.2f |\n", esc(it.Item), it.USDPerMonth)
		}
		fmt.Fprintf(b, "| **small production total** | | **%.2f** |\n", sc.ProductionUSD)
		b.WriteString("\nPools at zero cost nothing but their AMI snapshots (current + previous) and, for Windows, the EC2 Fast Launch pre-provisioned snapshots (user-approved). Enabling Fast Launch created the service-linked role `AWSServiceRoleForEC2FastLaunch`, which stays in place.\n")
		return
	}
}

func limitations(results []*harness.Result, rows []nfr.Row) []string {
	var out []string
	for _, r := range results {
		if r.Status == harness.StatusSkip {
			out = append(out, fmt.Sprintf("%s skipped: %s", r.ID, r.SkipReason))
		}
		for _, c := range r.Checks {
			if c.Skipped != "" {
				out = append(out, fmt.Sprintf("%s: check %q not run: %s", r.ID, c.Name, c.Skipped))
			}
		}
	}
	for _, row := range rows {
		if row.Status == nfr.NotMeasured {
			out = append(out, fmt.Sprintf("%s not measured (scenarios: %s)", row.ID, strings.Join(row.Scenarios, ", ")))
		}
	}
	return out
}

func sweepOutput(results []*harness.Result) string {
	for i := len(results) - 1; i >= 0; i-- {
		if raw, ok := results[i].Values["sweep"]; ok {
			bs, _ := json.Marshal(raw)
			var sw struct {
				Output string `json:"output"`
				Clean  bool   `json:"clean"`
			}
			if json.Unmarshal(bs, &sw) == nil {
				return strings.TrimSpace(sw.Output) + fmt.Sprintf("\n# clean: %v", sw.Clean)
			}
		}
	}
	return "(T15 has not run: no tag sweep output yet)"
}

func stripHeader(s string) string {
	lines := strings.Split(s, "\n")
	for len(lines) > 0 && (strings.HasPrefix(lines[0], "<!--") || strings.HasPrefix(lines[0], "# ")) {
		lines = lines[1:]
	}
	return strings.Join(lines, "\n")
}

// ADRIndex lists "NNNN — Title" for docs/adr/*.md.
func ADRIndex(dir string) ([]string, error) {
	files, err := filepath.Glob(filepath.Join(dir, "[0-9][0-9][0-9][0-9]-*.md"))
	if err != nil {
		return nil, err
	}
	sort.Strings(files)
	var out []string
	for _, f := range files {
		b, err := os.ReadFile(f)
		if err != nil {
			return nil, err
		}
		title := strings.TrimSuffix(filepath.Base(f), ".md")
		for _, line := range strings.Split(string(b), "\n") {
			if t, ok := strings.CutPrefix(line, "# "); ok {
				title = t
				break
			}
		}
		out = append(out, fmt.Sprintf("[%s](../adr/%s) — %s", filepath.Base(f)[:4], filepath.Base(f), title))
	}
	return out, nil
}

// Write renders, redacts and writes the report; it refuses to write if
// redaction left anything behind.
func Write(path string, in Input, red Redactor) ([]Finding, error) {
	text, found := red.Apply(Render(in))
	if left := Check(text); len(left) > 0 {
		return found, fmt.Errorf("redaction left %d identifiers (first: %s %q)", len(left), left[0].Rule, left[0].Match)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return found, err
	}
	return found, os.WriteFile(path, bytes.TrimLeft([]byte(text), "\n"), 0o644)
}
