#!/bin/bash
# SPDX-License-Identifier: FSL-1.1-ALv2
#
# Generates the Bazel workload of bench-build-dir.sh (R-CACHE-3 measurement):
#   gen-workspace.sh <dir> [units] [headers]
# * <headers> small headers (default 2000) that are inputs of EVERY compile action, standing in for a toolchain or
#   sysroot tree in the input root (what hermetic toolchains put there): native build directories must hardlink all
#   of them per action, a virtual (NFSv4) one instantiates them lazily.
# * <units> compile actions (default 200; /usr/bin/clang++ with the image's Xcode, -O1, a few STL headers each),
#   one link action reading every object, one action running the linked test binary, one action reading every header
#   (many small reads), and a trivial `smoke` action used to time the first action after a worker registers.
# Genrules call /usr/bin/clang++ directly so the measurement does not depend on Bazel's C++ toolchain setup.
# shellcheck disable=SC2016 # $(location …), $@ and $(SRCS) are Bazel genrule variables, not shell expansions.
set -euo pipefail

dir="$1"
units="${2:-200}"
headers="${3:-2000}"
mkdir -p "$dir/inc" "$dir/src"
cd "$dir"

printf '9.2.0\n' >.bazelversion
printf '# Generated by workers/macos/bench/gen-workspace.sh\nmodule(name = "cucina_bench_build_dir")\n' >MODULE.bazel

for ((h = 0; h < headers; h++)); do
  name=$(printf 'h%04d' "$h")
  {
    printf '#pragma once\n// %s: padding so every header is about 1 KiB, like typical sysroot headers.\n' "$name"
    for ((l = 0; l < 12; l++)); do printf '// %s line %02d ......................................................................\n' "$name" "$l"; done
    printf 'inline int %s_f(int x) { return x * %d + 1; }\n' "$name" "$((h + 1))"
  } >"inc/$name.h"
done

for ((u = 0; u < units; u++)); do
  {
    printf '#include <algorithm>\n#include <map>\n#include <string>\n#include <vector>\n'
    for ((k = 0; k < 8; k++)); do printf '#include "h%04d.h"\n' "$(((u * 8 + k) % headers))"; done
    printf 'int unit_%d() {\n  std::map<std::string, int> m;\n  std::vector<int> v;\n' "$u"
    for ((k = 0; k < 8; k++)); do printf '  v.push_back(h%04d_f(%d));\n' "$(((u * 8 + k) % headers))" "$k"; done
    printf '  std::sort(v.begin(), v.end());\n  for (int x : v) m[std::to_string(x)] += x;\n'
    printf '  int s = 0;\n  for (auto &kv : m) s += kv.second;\n  return s;\n}\n'
  } >"src/u$u.cc"
done
{
  printf '#include <cstdio>\n'
  for ((u = 0; u < units; u++)); do printf 'int unit_%d();\n' "$u"; done
  printf 'int main() {\n  long s = 0;\n'
  for ((u = 0; u < units; u++)); do printf '  s += unit_%d();\n' "$u"; done
  printf '  std::printf("sum=%%ld\\n", s);\n  return s > 0 ? 0 : 1;\n}\n'
} >src/main.cc

{
  printf '# Generated by workers/macos/bench/gen-workspace.sh\n'
  printf 'filegroup(name = "hdrs", srcs = glob(["inc/*.h"]))\n\n'
  printf 'genrule(name = "smoke", outs = ["smoke.txt"], cmd = "test $$(id -u) -ne 0 && echo ok > $@")\n\n'
  printf 'genrule(name = "read_all", srcs = [":hdrs"], outs = ["read_all.sha256"], cmd = "cat $(SRCS) | shasum -a 256 > $@")\n\n'
  printf '[genrule(\n    name = "c%%d" %% i,\n    srcs = ["src/u%%d.cc" %% i, ":hdrs"],\n    outs = ["u%%d.o" %% i],\n'
  printf '    cmd = "/usr/bin/clang++ -std=c++20 -O1 -Iinc -c $(location src/u%%d.cc) -o $@" %% i,\n) for i in range(%d)]\n\n' "$units"
  printf 'genrule(\n    name = "cmain",\n    srcs = ["src/main.cc"],\n    outs = ["main.o"],\n    cmd = "/usr/bin/clang++ -std=c++20 -O1 -c $< -o $@",\n)\n\n'
  printf 'genrule(\n    name = "link",\n    srcs = [":cmain"] + [":c%%d" %% i for i in range(%d)],\n    outs = ["bench_bin"],\n' "$units"
  printf '    cmd = "/usr/bin/clang++ -o $@ $(SRCS)",\n)\n\n'
  printf 'genrule(\n    name = "run",\n    srcs = [":link"],\n    outs = ["run.txt"],\n    cmd = "./$(location :link) > $@",\n)\n'
} >BUILD.bazel

echo "generated $units compile units and $headers headers in $dir"
