#!/usr/bin/env bash
# SPDX-License-Identifier: FSL-1.1-ALv2
#
# generate.sh: build THIRD_PARTY_NOTICES.md from the dependency set that exists
# in the repository right now. Re-run it whenever dependencies change and before
# every release; --check is the read-only mode for a release or CI gate.
#
#   tools/notices/generate.sh            write THIRD_PARTY_NOTICES.md
#   tools/notices/generate.sh --check    fail if the file is stale (no write)
#   tools/notices/generate.sh --stdout   print instead of writing
#
# Sources:
#   * components.json   hand-maintained: Buildbarn, Tart, WinFsp, shawl, hermetic-llvm,
#                       Go, musl, ...; licence texts in texts/
#   * Go modules        `go list -deps` of the shipped binaries (./cmd/...; while that
#                       tree is still empty, ./internal/... and ./api/...) for every
#                       release platform, plus the licence files in the module cache
#   * Rust crates       `cargo about generate` (pinned version below) over the Cargo
#                       workspace, using about.toml and about.hbs
#
# Policy: only licences listed in policy.json may be bundled. An unknown or
# disallowed licence, or a module without a licence file, makes the script exit 1
# without replacing the notices, so a human decides (add a text under texts/ and
# a mapping in overrides.json, or drop the dependency).
#
# Needs: go, jq, awk, shasum or sha256sum; cargo-about when a Cargo workspace exists.
# The output is deterministic: no timestamps, sorted everywhere.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../.." && pwd)"
# shellcheck source=lib.sh
# shellcheck source-path=SCRIPTDIR
. "$here/lib.sh"

bt='`'
cargo_about_version="0.9.2"
go_platforms="linux/amd64 linux/arm64 darwin/arm64 windows/amd64"
out_file="$repo/THIRD_PARTY_NOTICES.md"
mode="write"

while [ "$#" -gt 0 ]; do
    case "$1" in
    --check) mode="check"; shift ;;
    --stdout) mode="stdout"; shift ;;
    --out) out_file="${2:?--out needs a file}"; shift 2 ;;
    -h | --help)
        sed -n '2,/^set -euo/p' "$0" | sed '$d; s/^# \{0,1\}//'
        exit 0
        ;;
    *)
        echo "generate.sh: unknown argument: $1" >&2
        exit 2
        ;;
    esac
done

work="$(mktemp -d "${TMPDIR:-/tmp}/cucina-notices.XXXXXX")"
trap 'rm -rf "$work"' EXIT
problems="$work/problems.txt"
: >"$problems"

problem() {
    echo "$1" >>"$problems"
    echo "generate.sh: $1" >&2
}

sha() {
    if command -v sha256sum >/dev/null 2>&1; then sha256sum | cut -d' ' -f1; else shasum -a 256 | cut -d' ' -f1; fi
}

# md_escape: make text safe inside a markdown table cell.
md_escape() {
    sed 's/|/\\|/g'
}

# ------------------------------------------------------------------ preamble

emit_preamble() {
    cat <<'EOF'
<!-- SPDX-License-Identifier: FSL-1.1-ALv2 -->
<!-- GENERATED by tools/notices/generate.sh. Do not edit by hand: change components.json, texts/ or the dependencies, then re-run the script. -->
# Third-party notices

Cucina is licensed under the Functional Source License, Version 1.1, ALv2 Future License
(`LICENSE.md`, licensor Brwse Co.). It runs, installs or bundles the third-party software listed
here, each under its own licence. This file lives in the repository and is shipped inside the macOS host
package; Cucina's container images and worker images are to carry it too.

1. [Components](#1-components): Buildbarn, Tart and the other pieces that are not Go modules or Rust crates.
2. [Go modules](#2-go-modules) linked into Cucina's Go binaries.
3. [Rust crates](#3-rust-crates) linked into `cucinactl`.
4. [Software installed in worker images](#4-software-installed-in-worker-images).

The Go and Rust sections are generated from the dependencies that exist in the repository at
generation time. They are regenerated before each release.
EOF
}

# ---------------------------------------------------------------- components

emit_components() {
    local json="$here/components.json" key
    echo
    echo "## 1. Components"
    echo
    echo "| Component | Version | Licence | How Cucina uses it | Where it ships |"
    echo "| --- | --- | --- | --- | --- |"
    jq -r '.components[] | [.name, .version, .license, .use, .shipped] | map(gsub("\\|"; "\\|")) | "| " + join(" | ") + " |"' "$json"
    echo
    echo "Buildbarn, Tart and the other upstream components are used as released; Cucina does not modify them."
    echo
    jq -r '.components[] | select(.text != null) | .text' "$json" | LC_ALL=C sort -u | while read -r key; do
        if [ ! -f "$here/texts/$key.txt" ]; then
            problem "components.json refers to texts/$key.txt, which does not exist"
            continue
        fi
        echo "### Licence text: $key"
        echo
        echo "Applies to: $(jq -r --arg k "$key" '[.components[] | select(.text == $k) | .name] | join("; ")' "$json")"
        echo
        echo "~~~~text"
        cat "$here/texts/$key.txt"
        echo
        echo "~~~~"
        echo
    done
}

# ------------------------------------------------------------------- Go modules

go_roots() {
    # The shipped binaries are the packages under cmd/. Until they exist, fall back
    # to the library packages so that the first version reflects today's dependencies.
    if find "$repo/cmd" -name '*.go' -type f 2>/dev/null | grep -q .; then
        echo "./cmd/..."
    else
        echo "./internal/... ./api/..."
    fi
}

# license_files <dir>: licence-like files at the root of a module, sorted.
license_files() {
    find "$1" -maxdepth 1 -type f \( -iname 'LICENSE' -o -iname 'LICENSE.*' -o -iname 'LICENSE-*' \
        -o -iname 'LICENCE*' -o -iname 'COPYING*' -o -iname 'UNLICENSE' -o -iname 'NOTICE*' \) | LC_ALL=C sort
}

emit_go() {
    local g="$work/go" plat goos goarch cgo path version dir f hash nhash spdx n override
    local lic="$g/current.lic.txt" notice="$g/current.notice.txt"
    mkdir -p "$g/texts" "$g/uses" "$g/spdx" "$g/notices" "$g/nuses"
    : >"$g/modules.tsv"
    # shellcheck disable=SC2046 # the roots are a short, deliberately word-split list of patterns
    set -- $(go_roots)
    for plat in $go_platforms; do
        goos="${plat%/*}"
        goarch="${plat#*/}"
        cgo=0
        [ "$goos" = darwin ] && cgo=1
        (cd "$repo" && GOFLAGS=-mod=readonly GOOS="$goos" GOARCH="$goarch" CGO_ENABLED="$cgo" \
            go list -e -deps -f '{{if and (not .Standard) .Module (not .Module.Main)}}{{.Module.Path}}{{"\t"}}{{.Module.Version}}{{"\t"}}{{.Module.Dir}}{{end}}' "$@" 2>/dev/null) >>"$g/modules.tsv" || {
            problem "go list failed for $plat (run it by hand: GOOS=$goos GOARCH=$goarch go list -e -deps $*)"
        }
    done
    LC_ALL=C sort -u "$g/modules.tsv" | grep -v '^$' >"$g/modules.sorted.tsv" || true
    # Packages that fail to load would silently shrink the list: report them. The
    # expected exception is a root package that does not build on a platform.
    for plat in $go_platforms; do
        goos="${plat%/*}"
        goarch="${plat#*/}"
        cgo=0
        [ "$goos" = darwin ] && cgo=1
        (cd "$repo" && GOFLAGS=-mod=readonly GOOS="$goos" GOARCH="$goarch" CGO_ENABLED="$cgo" \
            go list -e -deps -f '{{if .Error}}{{.ImportPath}}: {{.Error}}{{end}}' "$@" 2>&1 || true) |
            { grep -v -e '^$' -e 'build constraints exclude all Go files' || true; } |
            while read -r line; do problem "go list ($plat): $line"; done
    done

    echo
    echo "## 2. Go modules"
    echo
    echo "Modules linked into the Go binaries of this repository (packages: $(go_roots); platforms: $go_platforms),"
    echo "excluding modules that only tests use. The Go standard library is covered in section 1."
    echo
    n="$(wc -l <"$g/modules.sorted.tsv" | tr -d ' ')"
    if [ "$n" -eq 0 ]; then
        echo "No third-party Go modules are linked yet."
        return
    fi
    echo "| Module | Version | Licence |"
    echo "| --- | --- | --- |"
    while IFS="$(printf '\t')" read -r path version dir; do
        if [ -z "$dir" ] || [ ! -d "$dir" ]; then
            problem "module $path@$version is not in the module cache (run: go mod download)"
            continue
        fi
        : >"$lic"
        : >"$notice"
        while IFS= read -r f; do
            case "$(basename "$f" | tr '[:lower:]' '[:upper:]')" in
            NOTICE*) printf '%s\n\n' "$(cat "$f")" >>"$notice" ;;
            *) printf '%s\n\n' "$(cat "$f")" >>"$lic" ;;
            esac
        done < <(license_files "$dir")
        if [ ! -s "$lic" ]; then
            override="$(jq -r --arg p "$path" '.modules[$p].license_text // empty' "$here/overrides.json")"
            if [ -n "$override" ] && [ -f "$here/$override" ]; then
                cat "$here/$override" >"$lic"
            else
                problem "module $path@$version has no licence file in its root: add a mapping to tools/notices/overrides.json"
                printf "| ${bt}%s${bt} | %s | **no licence file** |\n" "$path" "$version"
                continue
            fi
        fi
        spdx="$(classify_text <"$lic")"
        if ! spdx_allowed "$here/policy.json" "$spdx"; then
            problem "module $path@$version has licence \"$spdx\", which policy.json does not allow"
        fi
        # Deduplicate identical full texts only. Apache appendices can carry
        # project-specific copyright notices; replacing them by a canonical
        # Apache text would silently discard those attributions.
        hash="$(sha <"$lic")"
        [ -f "$g/texts/$hash" ] || cp "$lic" "$g/texts/$hash"
        printf '%s@%s\n' "$path" "$version" >>"$g/uses/$hash"
        printf '%s' "$spdx" >"$g/spdx/$hash"
        if [ -s "$notice" ]; then
            nhash="$(normalize <"$notice" | sha)"
            [ -f "$g/notices/$nhash" ] || cp "$notice" "$g/notices/$nhash"
            printf '%s@%s\n' "$path" "$version" >>"$g/nuses/$nhash"
        fi
        printf "| ${bt}%s${bt} | %s | %s |\n" "$path" "$version" "$spdx"
    done <"$g/modules.sorted.tsv"

    if ! find "$g/texts" -type f | grep -q .; then
        return
    fi
    echo
    echo "### Licence texts (Go modules)"
    echo
    # Order: by licence, then by the first module that uses the text.
    for hash in $(for h in "$g"/texts/*; do
        h="$(basename "$h")"
        printf '%s\t%s\t%s\n' "$(cat "$g/spdx/$h")" "$(LC_ALL=C sort "$g/uses/$h" | head -n 1)" "$h"
    done | LC_ALL=C sort | cut -f3); do
        echo "#### $(cat "$g/spdx/$hash")"
        echo
        echo "Used by:"
        echo
        LC_ALL=C sort "$g/uses/$hash" | sed "s/^/- ${bt}/; s/\$/${bt}/"
        echo
        echo "~~~~text"
        sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$g/texts/$hash"
        echo "~~~~"
        echo
    done

    if find "$g/notices" -type f | grep -q .; then
        echo "### NOTICE files (Go modules)"
        echo
        echo "Apache-2.0 requires reproducing the NOTICE file of a work that has one."
        echo
        for nhash in $(for h in "$g"/notices/*; do
            h="$(basename "$h")"
            printf '%s\t%s\n' "$(LC_ALL=C sort "$g/nuses/$h" | head -n 1)" "$h"
        done | LC_ALL=C sort | cut -f2); do
            echo "Used by:"
            echo
            LC_ALL=C sort "$g/nuses/$nhash" | sed "s/^/- ${bt}/; s/\$/${bt}/"
            echo
            echo "~~~~text"
            sed -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$g/notices/$nhash"
            echo "~~~~"
            echo
        done
    fi
}

# ---------------------------------------------------------------- Rust crates

emit_rust() {
    local about="${CARGO_ABOUT:-cargo-about}" have
    echo
    echo "## 3. Rust crates"
    echo
    if [ ! -f "$repo/Cargo.toml" ]; then
        echo "No Rust crates are bundled yet: the Cargo workspace does not exist at generation time."
        return
    fi
    echo "Crates linked into \`cucinactl\` (Cargo workspace at the repository root; build and dev dependencies excluded)."
    echo "The Rust standard library is licensed MIT OR Apache-2.0; section 1 covers musl."
    echo
    if ! command -v "$about" >/dev/null 2>&1; then
        problem "cargo-about $cargo_about_version is required to list Rust crates (mise install cargo-about, or cargo install cargo-about --version $cargo_about_version --locked)"
        return
    fi
    have="$("$about" --version 2>/dev/null | awk '{print $2}')"
    if [ "$have" != "$cargo_about_version" ]; then
        problem "cargo-about $have found, $cargo_about_version is pinned in tools/notices/generate.sh (output must be reproducible)"
    fi
    (cd "$repo" && "$about" generate --workspace --locked --fail \
        --config "$here/about.toml" "$here/about.hbs") ||
        problem "cargo about failed (see above)"
}

# -------------------------------------------------------------- image contents

emit_images() {
    echo
    echo "## 4. Software installed in worker images"
    echo
    echo "The image builds install the following from their vendors. Worker images are built by each operator"
    echo "(AMIs per AWS account, Tart images pushed to a private registry); this project does not publish them,"
    echo "so these licences bind the operator who builds an image. Do not publish an image that contains WinFsp or Xcode."
    echo
    echo "| Software | Licence | Where |"
    echo "| --- | --- | --- |"
    jq -r '.image_contents.items[] | [.name, .license, .note] | map(gsub("\\|"; "\\|")) | "| " + join(" | ") + " |"' "$here/components.json"
}

# ----------------------------------------------------------------------- main

generated="$work/THIRD_PARTY_NOTICES.md"
{
    emit_preamble
    emit_components
    emit_go
    emit_rust
    emit_images
} >"$generated"

if [ -s "$problems" ]; then
    echo "generate.sh: $(wc -l <"$problems" | tr -d ' ') problem(s); notices unchanged; see above" >&2
    exit 1
fi

case "$mode" in
stdout) cat "$generated" ;;
check)
    if cmp -s "$generated" "$out_file"; then
        echo "generate.sh: $out_file is up to date"
    else
        echo "generate.sh: $out_file is stale; run tools/notices/generate.sh" >&2
        diff -u "$out_file" "$generated" | head -n 40 >&2 || true
        exit 1
    fi
    ;;
write)
    cp "$generated" "$out_file"
    echo "generate.sh: wrote $out_file ($(wc -l <"$out_file" | tr -d ' ') lines)"
    ;;
esac
