# SPDX-License-Identifier: FSL-1.1-ALv2
# Rotation for the Cucina host logs that hostd does not rotate itself (installed as
# /etc/newsyslog.d/ai.sloper.cucina.conf). hostd.log and bb_storage.log are rotated by hostd (docs/dev/hostd.md §2).
# Flags: N = no process to signal, J = bzip2, B = no "turned over" line (keeps JSON/plain logs parseable).
# logfilename                               [owner:group]  mode count size(KiB) when flags
/Library/Logs/Cucina/hostd.stderr.log       root:admin     640  5     10240     *    NJB
/Library/Logs/Cucina/install.log            root:admin     640  3     1024      *    NJB
