// SPDX-License-Identifier: FSL-1.1-ALv2

package workeragent_test

import (
	"encoding/json"
	"reflect"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/sloper-ai/cucina/internal/bbconfig"
	"github.com/sloper-ai/cucina/internal/workeragent"
	"github.com/sloper-ai/cucina/internal/workeragent/agenttest"
)

// Guards: the `render --machine` JSON contract (hostd, tests) carries every
// input of bbconfig.Machine — a field added to the renderer without a JSON
// mirror would silently never be set.
func TestMachineMirrorsRendererInput(t *testing.T) {
	m := workeragent.Machine{
		OS: "linux", Arch: "x86_64", VCPUs: 4, MemoryBytes: 1, InstanceStorePath: "/a", InstanceStoreBytes: 1,
		DataVolumePath: "/b", DataVolumeBytes: 1, StateRoot: "/c", StateRootBytes: 1, BuildRoot: "/d", RunDir: "/e",
		PKIDir: "/f", CABundlePEM: "g", StorageServerName: "h", StorageIsHostL2: true, MetricsHost: "i",
		BuildUser:                  &workeragent.UnixUser{UID: 1, GID: 1, AdditionalGIDs: []uint32{1}},
		EmulatorLDPrefixes:         map[string]string{"j": "k"},
		XcodeDeveloperDirectories:  map[string]string{"l": "m"},
		NativeBuildDirectoryReason: "n", NativeCacheBytes: 1,
	}
	bm := reflect.ValueOf(m.BBConfig())
	for i := range bm.NumField() {
		f := bm.Type().Field(i)
		_, mirrored := reflect.TypeOf(m).FieldByName(f.Name)
		require.True(t, mirrored, "bbconfig.Machine.%s has no JSON mirror in workeragent.Machine", f.Name)
		require.False(t, bm.Field(i).IsZero(), "workeragent.Machine.BBConfig drops %s", f.Name)
	}
}

// Guards: `render` input handling (strict machine document) and the service
// environment file (systemd EnvironmentFile= syntax, no injection through
// settings.env, CUCINA_* reserved).
func TestRenderInputsAndEnvironment(t *testing.T) {
	ca := agenttest.NewCA(t, "cucina test ca")
	doc := map[string]any{
		"os": "darwin", "arch": "arm64", "vcpus": 6, "memoryBytes": 16 << 30,
		"stateRoot": "/var/db/cucina", "stateRootBytes": 200 << 30, "buildRoot": "/Volumes/CucinaBuild",
		"runDir": "/var/run/cucina-runner", "pkiDir": "/var/db/cucina/pki", "caBundlePem": string(ca.CertPEM),
		"storageIsHostL2": true, "buildUser": map[string]any{"uid": 501, "gid": 20},
	}
	b, err := json.Marshal(doc)
	require.NoError(t, err)
	m, err := workeragent.DecodeMachine(b)
	require.NoError(t, err)
	_, err = workeragent.DecodeMachine([]byte(strings.Replace(string(b), `"vcpus"`, `"cpus"`, 1)))
	require.Error(t, err, "unknown fields fail")

	s := agenttest.Settings()
	s.Pool, s.Node, s.BuildDirectory, s.L1Placement = "macos-arm64-xcode27.0", "mini-01/vm-1", "native", "vm-disk"
	s.Env = map[string]string{"HTTPS_PROXY": "http://proxy.internal:3128", "NO_PROXY": "169.254.169.254,.internal", "QUOTE": "it's"}
	files, err := workeragent.RenderAll(workeragent.BBConfigRenderer{}, s, m)
	require.NoError(t, err)
	require.True(t, json.Valid(files.Worker) && json.Valid(files.Runner))
	require.Contains(t, string(files.Worker), "/var/db/cucina/pki/"+bbconfig.ClientPrivateKeyFile)
	require.Equal(t, "# Generated by cucina-worker-agent; do not edit.\n"+
		"CUCINA_BUILD_DIRECTORY='/Volumes/CucinaBuild/build'\n"+
		"CUCINA_BUILD_ROOT='/Volumes/CucinaBuild'\n"+
		"CUCINA_L1_PLACEMENT='vm-disk'\n"+
		"CUCINA_METRICS_PORT='9980'\n"+
		"CUCINA_NODE='mini-01/vm-1'\n"+
		"CUCINA_POOL='macos-arm64-xcode27.0'\n"+
		"CUCINA_STATE_ROOT='/var/db/cucina'\n"+
		"HTTPS_PROXY='http://proxy.internal:3128'\n"+
		"NO_PROXY='169.254.169.254,.internal'\n"+
		`QUOTE="it's"`+"\n", string(files.Env))

	for name, env := range map[string]map[string]string{
		"newline injection": {"A": "x\nLD_PRELOAD=/tmp/evil.so"},
		"reserved prefix":   {"CUCINA_POOL": "other"},
		"invalid name":      {"A-B": "x"},
	} {
		s.Env = env
		_, err := workeragent.RenderAll(workeragent.BBConfigRenderer{}, s, m)
		require.Error(t, err, name)
	}
}
