// SPDX-License-Identifier: FSL-1.1-ALv2

package workeragent

import (
	"bytes"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"

	cucinav1 "github.com/sloper-ai/cucina/api/proto/cucina/v1"
	"github.com/sloper-ai/cucina/internal/bbconfig"
)

// Renderer renders the Buildbarn configuration from the pool-level settings
// and the machine facts. BBConfigRenderer (internal/bbconfig) is the
// production implementation; Plan exposes the directories to create and the
// decisions to log.
type Renderer interface {
	Plan(settings *cucinav1.WorkerSettings, m Machine) (*bbconfig.WorkerPlan, error)
	Worker(settings *cucinav1.WorkerSettings, m Machine) ([]byte, error)
	Runner(settings *cucinav1.WorkerSettings, m Machine) ([]byte, error)
}

// BBConfigRenderer renders with internal/bbconfig.
type BBConfigRenderer struct{}

// Plan implements Renderer.
func (BBConfigRenderer) Plan(s *cucinav1.WorkerSettings, m Machine) (*bbconfig.WorkerPlan, error) {
	return bbconfig.PlanWorker(s, m.BBConfig())
}

// Worker implements Renderer.
func (BBConfigRenderer) Worker(s *cucinav1.WorkerSettings, m Machine) ([]byte, error) {
	return bbconfig.RenderWorker(s, m.BBConfig())
}

// Runner implements Renderer.
func (BBConfigRenderer) Runner(s *cucinav1.WorkerSettings, m Machine) ([]byte, error) {
	return bbconfig.RenderRunner(s, m.BBConfig())
}

// RenderedFiles are the rendered outputs of one machine.
type RenderedFiles struct {
	Worker []byte // worker.json
	Runner []byte // runner.json
	Env    []byte // env
	Plan   *bbconfig.WorkerPlan
}

// RenderAll plans and renders worker.json, runner.json and the service
// environment.
func RenderAll(r Renderer, settings *cucinav1.WorkerSettings, m Machine) (RenderedFiles, error) {
	if settings == nil {
		return RenderedFiles{}, errors.New("render: no worker settings")
	}
	plan, err := r.Plan(settings, m)
	if err != nil {
		return RenderedFiles{}, fmt.Errorf("plan worker configuration: %w", err)
	}
	w, err := r.Worker(settings, m)
	if err != nil {
		return RenderedFiles{}, fmt.Errorf("render bb_worker configuration: %w", err)
	}
	ru, err := r.Runner(settings, m)
	if err != nil {
		return RenderedFiles{}, fmt.Errorf("render bb_runner configuration: %w", err)
	}
	env, err := RenderEnv(settings, m, plan)
	if err != nil {
		return RenderedFiles{}, err
	}
	return RenderedFiles{Worker: w, Runner: ru, Env: env, Plan: plan}, nil
}

var envKey = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// RenderEnv renders the service environment file (systemd EnvironmentFile=
// syntax; the Windows services read the same KEY='value' lines). It holds the
// free-form WorkerSettings.env (proxies etc., never secrets) plus CUCINA_*
// facts. Per-runner variables such as QEMU_LD_PREFIX belong to the runner
// configuration (bb_worker runners[].environmentVariables), because one
// worker serves several emulated ISAs.
func RenderEnv(settings *cucinav1.WorkerSettings, m Machine, plan *bbconfig.WorkerPlan) ([]byte, error) {
	vars := map[string]string{}
	for k, v := range settings.GetEnv() {
		if !envKey.MatchString(k) {
			return nil, fmt.Errorf("env: invalid variable name %q", k)
		}
		if strings.HasPrefix(k, "CUCINA_") {
			return nil, fmt.Errorf("env: variable %q uses the reserved CUCINA_ prefix", k)
		}
		if strings.ContainsAny(v, "\x00\r\n") {
			return nil, fmt.Errorf("env: value of %q contains a NUL or line break", k)
		}
		vars[k] = v
	}
	vars["CUCINA_POOL"] = settings.GetPool()
	vars["CUCINA_NODE"] = settings.GetNode()
	vars["CUCINA_STATE_ROOT"] = m.StateRoot
	vars["CUCINA_BUILD_ROOT"] = m.BuildRoot
	if plan != nil {
		vars["CUCINA_BUILD_DIRECTORY"] = plan.BuildDirectoryPath
		vars["CUCINA_L1_PLACEMENT"] = plan.L1.Placement
	}
	if p := settings.GetMetricsPort(); p != 0 {
		vars["CUCINA_METRICS_PORT"] = strconv.FormatUint(uint64(p), 10)
	}
	keys := make([]string, 0, len(vars))
	for k := range vars {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b bytes.Buffer
	b.WriteString("# Generated by cucina-worker-agent; do not edit.\n")
	for _, k := range keys {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quoteEnv(vars[k]))
		b.WriteByte('\n')
	}
	return b.Bytes(), nil
}

// quoteEnv single-quotes a value (verbatim in systemd EnvironmentFile=) or,
// when it contains a single quote, double-quotes it with \ " ` $ escaped.
func quoteEnv(v string) string {
	if !strings.Contains(v, "'") {
		return "'" + v + "'"
	}
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`, "`", "\\`", `$`, `\$`)
	return `"` + r.Replace(v) + `"`
}

// DecodeSettings strictly parses WorkerSettings protojson (unknown fields fail).
func DecodeSettings(b []byte) (*cucinav1.WorkerSettings, error) {
	s := &cucinav1.WorkerSettings{}
	if err := (protojson.UnmarshalOptions{}).Unmarshal(b, s); err != nil {
		return nil, fmt.Errorf("worker settings: %w", err)
	}
	return s, nil
}
