load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "v1alpha1",
    srcs = [
        "groupversion_info.go",
        "machost_types.go",
        "trustpolicy_types.go",
        "workerpool_types.go",
        "zz_generated.deepcopy.go",
    ],
    importpath = "github.com/sloper-ai/cucina/api/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
    ],
)
