// SPDX-License-Identifier: FSL-1.1-ALv2

// Package v1alpha1 contains the Cucina custom resources: WorkerPool, MacHost and
// TrustPolicy. DeepCopy methods and the CRD manifests are generated by
// controller-gen (see docs/dev/bazel.md); do not edit zz_generated.* by hand.
//
// +kubebuilder:object:generate=true
// +groupName=cucina.sloper.ai
package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	// GroupVersion is the group/version used to register these objects.
	GroupVersion = schema.GroupVersion{Group: "cucina.sloper.ai", Version: "v1alpha1"}

	// SchemeBuilder collects the functions that add the types to a scheme.
	SchemeBuilder = runtime.NewSchemeBuilder(addKnownTypes)

	// AddToScheme adds the Cucina types to a scheme.
	AddToScheme = SchemeBuilder.AddToScheme
)

func addKnownTypes(s *runtime.Scheme) error {
	s.AddKnownTypes(GroupVersion,
		&WorkerPool{}, &WorkerPoolList{},
		&MacHost{}, &MacHostList{},
		&TrustPolicy{}, &TrustPolicyList{},
	)
	metav1.AddToGroupVersion(s, GroupVersion)
	return nil
}
