// SPDX-License-Identifier: FSL-1.1-ALv2

package xplat

import (
	"fmt"
	"slices"
	"sort"
	"strings"
)

const header = "Code generated by //tools/xplat from platforms/pools.json and platforms/targets.json. DO NOT EDIT.\n" +
	"# Regenerate: bazel run //tools/xplat:update. Design: docs/cross-compilation.md."

// Generated files. The first four are paths relative to bazel/platforms (the @cucina_platforms
// module root); ModuleSegment is the root-module segment that lives in tools/xplat (bazel/platforms
// is a separate module, .bazelignore'd in this repository, so the root module cannot include
// files from it).
const (
	ExecBuildFile    = "exec/BUILD.bazel"
	TestBuildFile    = "test/BUILD.bazel"
	CatalogFile      = "catalog.bzl"
	BazelrcFile      = "cucina.bazelrc"
	ModuleSegment    = "cucina_platforms.MODULE.bazel"
	ModuleVersion    = "0.1.0"
	modulePathInRepo = "bazel/platforms"
)

// ModuleFiles lists the generated files of the @cucina_platforms module.
var ModuleFiles = []string{BazelrcFile, CatalogFile, ExecBuildFile, TestBuildFile}

// Generate renders the generated files: the module files and the root-module segment.
func (c *Catalog) Generate() map[string]string {
	return map[string]string{
		ExecBuildFile: c.execBuild(),
		TestBuildFile: c.testBuild(),
		CatalogFile:   c.catalogBzl(),
		BazelrcFile:   c.bazelrc(),
		ModuleSegment: c.moduleSegment(),
	}
}

// MacOSFirst returns the compile exec platforms with the macOS ones first (stable otherwise).
func (c *Catalog) MacOSFirst() []ExecPlatform {
	var mac, rest []ExecPlatform
	for _, e := range c.Targets.ExecPlatforms {
		if e.OS == "macos" {
			mac = append(mac, e)
		} else {
			rest = append(rest, e)
		}
	}
	return append(mac, rest...)
}

// ExecutionPlatforms returns the complete --extra_execution_platforms list for a compile
// order: the compile exec platforms in that order, then every test exec platform (R-BUILD-4:
// Bazel appends the host platform last, and actions resolving to it would reach Buildbarn
// without platform properties, so the list must cover every action).
func (c *Catalog) ExecutionPlatforms(compile []ExecPlatform) []string {
	out := make([]string, 0, len(compile)+len(c.Targets.Targets))
	for _, e := range compile {
		out = append(out, e.Label)
	}
	for _, t := range c.Runnable() {
		out = append(out, t.Test.Label)
	}
	return out
}

func starlarkString(s string) string { return fmt.Sprintf("%q", s) }

func starlarkDict(indent string, m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var b strings.Builder
	b.WriteString("{\n")
	for _, k := range keys {
		fmt.Fprintf(&b, "%s    %s: %s,\n", indent, starlarkString(k), starlarkString(m[k]))
	}
	b.WriteString(indent + "}")
	return b.String()
}

func (c *Catalog) execBuild() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", header)
	b.WriteString(`#
# Compile exec platforms: one per compile-capable pool runner (R-XPLAT-2a). The constraint values
# include hermetic-llvm's exec constraints (rbe.bzl pattern) so that exec-configured tools build;
# exec_properties are exactly the runner's REAPI property set (Buildbarn matches the entire set).
# Native configurations (UC1-UC3) also use these as --host_platform and --platforms.

package(default_visibility = ["//visibility:public"])

exports_files(["BUILD.bazel"])
`)
	for _, e := range c.Targets.ExecPlatforms {
		r, _ := c.Runner(e.Pool, e.Runner)
		constraints := append([]string{"@platforms//os:" + e.OS, "@platforms//cpu:" + e.CPU}, e.Constraints...)
		b.WriteString("\n")
		fmt.Fprintf(&b, "# Pool %s, runner %s.\n", e.Pool, e.Runner)
		b.WriteString("platform(\n")
		fmt.Fprintf(&b, "    name = %s,\n", starlarkString(e.Pool+"-"+e.Runner))
		b.WriteString("    constraint_values = [\n")
		for _, cv := range constraints {
			fmt.Fprintf(&b, "        %s,\n", starlarkString(cv))
		}
		b.WriteString("    ],\n")
		fmt.Fprintf(&b, "    exec_properties = %s,\n", starlarkDict("    ", r.Properties))
		b.WriteString(")\n")
	}
	return b.String()
}

func (c *Catalog) testBuild() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", header)
	b.WriteString(`#
# Test exec platforms ("twins", R-XPLAT-2b): test_on_<P> inherits every constraint of the
# hermetic-llvm target platform P (libc and glibc version, Windows ABI and CRT, C++ library), so
# Bazel 9's default test toolchain, which requires the test's exec platform to satisfy all of the
# target platform's constraints, sends the test action here; exec_properties select the runner.
# For your own target platforms use cucina_test_exec_platform() from @cucina_platforms//:defs.bzl.

package(default_visibility = ["//visibility:public"])

exports_files(["BUILD.bazel"])
`)
	for _, t := range c.Runnable() {
		r, _ := c.Runner(t.Test.Pool, t.Test.Runner)
		b.WriteString("\n")
		fmt.Fprintf(&b, "# %s: tests on %s/%s (%s).\n", t.Name, t.Test.Pool, t.Test.Runner, t.Test.Mode)
		b.WriteString("platform(\n")
		fmt.Fprintf(&b, "    name = %s,\n", starlarkString("test_on_"+t.PlatformName()))
		fmt.Fprintf(&b, "    exec_properties = %s,\n", starlarkDict("    ", r.Properties))
		fmt.Fprintf(&b, "    parents = [%s],\n", starlarkString(t.Platform))
		b.WriteString(")\n")
	}
	return b.String()
}

func (c *Catalog) catalogBzl() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", header)
	b.WriteString(`"""Runner property sets and the target matrix, for macros and rules of @cucina_platforms."""

`)
	// Runners of every pool (including test-only ones), for cucina_test_exec_platform().
	b.WriteString("# Pool -> runner -> exact REAPI property set (platforms/pools.json).\n")
	b.WriteString("RUNNERS = {\n")
	pools := append([]PoolPlatform(nil), c.Pools.Platforms...)
	sort.Slice(pools, func(i, j int) bool { return pools[i].Name < pools[j].Name })
	for _, p := range pools {
		fmt.Fprintf(&b, "    %s: {\n", starlarkString(p.Name))
		runners := append([]Runner(nil), p.Runners...)
		sort.Slice(runners, func(i, j int) bool { return runners[i].Name < runners[j].Name })
		for _, r := range runners {
			fmt.Fprintf(&b, "        %s: %s,\n", starlarkString(r.Name), starlarkDict("        ", r.Properties))
		}
		b.WriteString("    },\n")
	}
	b.WriteString("}\n\n")

	b.WriteString("# Compile exec platforms in default preference order (UC25).\n")
	b.WriteString("EXEC_PLATFORMS = [\n")
	for _, e := range c.Targets.ExecPlatforms {
		fmt.Fprintf(&b, "    %s,\n", starlarkString(e.Label))
	}
	b.WriteString("]\n\n")

	b.WriteString("# hermetic-llvm target platform -> its test exec platform.\n")
	b.WriteString("TEST_PLATFORMS = {\n")
	for _, t := range c.Runnable() {
		fmt.Fprintf(&b, "    %s: %s,\n", starlarkString(t.Platform), starlarkString(t.Test.Label))
	}
	b.WriteString("}\n")
	return b.String()
}

func (c *Catalog) bazelrc() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", header)
	linux := c.Targets.ExecPlatforms
	mac := c.MacOSFirst()
	b.WriteString(`#
# Imported by the root .bazelrc (try-import %workspace%/bazel/platforms/cucina.bazelrc), after its
# own :cucina/:cucina-macos lines. "build:" (not "common:") on purpose: the root .bazelrc says
# build:cucina-macos --config=cucina, and Bazel expands common: lines of a config before its build:
# lines, so only build: lines here come after :cucina's list. --extra_execution_platforms keeps
# the last value: compile exec platforms in preference order, then every test exec platform
# (R-BUILD-4: the list must be complete; Bazel appends the host platform last).

# :cucina - Linux compiles first (default exec order, R-XPLAT-7). macOS-target compiles still land
# on macOS: no other exec platform has a C/C++ toolchain for macOS (ADR 0902).
`)
	fmt.Fprintf(&b, "build:cucina --extra_execution_platforms=%s\n", strings.Join(c.ExecutionPlatforms(linux), ","))
	fmt.Fprintf(&b, "build:cucina --host_platform=%s\n", linux[0].Label)
	for _, f := range c.macFlags() {
		fmt.Fprintf(&b, "build:cucina %s\n", f)
	}
	b.WriteString(`
# :cucina-macos - macOS first, so every action of a macOS-target build stays on macOS (R-XPLAT-2c);
# the macOS lane targets the macOS exec platform itself.
`)
	fmt.Fprintf(&b, "build:cucina-macos --extra_execution_platforms=%s\n", strings.Join(c.ExecutionPlatforms(mac), ","))
	fmt.Fprintf(&b, "build:cucina-macos --host_platform=%s\n", mac[0].Label)
	fmt.Fprintf(&b, "build:cucina-macos --platforms=%s\n", mac[0].Label)
	for _, f := range mac[0].Flags {
		fmt.Fprintf(&b, "build:cucina-macos %s\n", f)
	}
	return b.String()
}

// macFlags are the flags of the default macOS exec platform (the SDK version), needed by any
// configuration that may compile for macOS.
func (c *Catalog) macFlags() []string {
	for _, e := range c.MacOSFirst() {
		if e.OS == "macos" {
			return e.Flags
		}
	}
	return nil
}

// ToolchainPairs returns hermetic-llvm's stage-0 C/C++ toolchain labels for every supported
// (exec, target) pair: every compile exec OS/CPU to every in-scope non-macOS target, and macOS
// exec to macOS targets only (macOS targets compile on macOS; the SDK exists only there).
func (c *Catalog) ToolchainPairs() []string {
	type osCPU struct{ os, cpu string }
	var execs []osCPU
	for _, e := range c.Targets.ExecPlatforms {
		if p := (osCPU{e.OS, e.CPU}); !slices.Contains(execs, p) {
			execs = append(execs, p)
		}
	}
	var out []string
	seen := map[string]bool{}
	for _, e := range execs {
		for _, t := range c.InScope() {
			if t.OS == "macos" && e.os != "macos" {
				continue
			}
			name := fmt.Sprintf("@llvm//toolchain:%s_%s_to_%s_%s", e.os, e.cpu, t.OS, t.CPU)
			if t.ABI != nil && *t.ABI == "msvc" {
				name += "_msvc"
			}
			if !seen[name] {
				seen[name] = true
				out = append(out, name)
			}
		}
	}
	return out
}

func (c *Catalog) moduleSegment() string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", header)
	b.WriteString(`#
# MODULE.bazel segment for the Cucina repository's root module:
#   include("//tools/xplat:cucina_platforms.MODULE.bazel")
# Other workspaces copy these lines (with their own override or a registry version of the module)
# from docs/cross-compilation.md.

`)
	fmt.Fprintf(&b, "bazel_dep(name = %s, version = %s)\n", starlarkString(moduleName), starlarkString(ModuleVersion))
	fmt.Fprintf(&b, "local_path_override(\n    module_name = %s,\n    path = %s,\n)\n", starlarkString(moduleName), starlarkString(modulePathInRepo))
	b.WriteString(`
# R-XPLAT-8: macOS-target toolchains use the SDK of the macOS exec machine (the worker image);
# hermetic-llvm's @macos_sdk (Apple's SDK downloaded on the client) is never fetched.
osx = use_extension("@llvm//extensions:osx.bzl", "osx")

cucina_apple = use_extension("@cucina_platforms//apple:extensions.bzl", "apple")
use_repo(cucina_apple, "cucina_macos_exec_sdk")

override_repo(
    osx,
    macos_sdk = "cucina_macos_exec_sdk",
)

# hermetic-llvm C/C++ toolchains (stage 0) for the supported (exec, target) pairs only, instead of
# @llvm//toolchain:all: macOS targets compile on macOS exec platforms only, and the excluded
# platforms (macOS x86_64, Windows arm64) are neither exec nor target platforms.
register_toolchains(
`)
	for _, l := range c.ToolchainPairs() {
		fmt.Fprintf(&b, "    %s,\n", starlarkString(l))
	}
	b.WriteString(")\n")
	return b.String()
}
