// Code generated by //tools/envtest/cmd/sync from sigs.k8s.io/controller-runtime v0.24.1; DO NOT EDIT.
// Upstream Apache-2.0; see LICENSE. Cucina changes: import relocation and checked-in lifecycle patch.

// SPDX-License-Identifier: FSL-1.1-ALv2
//go:build windows

package process

import (
	"context"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"syscall"
	"testing"
	"testing/synctest"
	"time"
)

// Guards ADR 0112: an owned Windows child can be reaped by os/exec before the
// State's exit-publication goroutine completes. Stop must join that publication
// before treating an invalid/released handle as harmless or deleting state.
func TestStopJoinsReleasedWindowsHandle(t *testing.T) {
	const childMode = "CUCINA_ENVTEST_LIFETIME_CHILD"
	if os.Getenv(childMode) == "1" {
		return // An owned real helper child, not a simulated Unix signal.
	}
	binary, err := os.Executable()
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(binary, "-test.run=^TestStopJoinsReleasedWindowsHandle$")
	cmd.Env = append(os.Environ(), childMode+"=1")
	if err := cmd.Run(); err != nil {
		t.Fatalf("owned helper child: %v", err)
	}
	if err := cmd.Process.Kill(); !errors.Is(err, syscall.EINVAL) {
		t.Fatalf("expected pinned Go's released Windows handle error, got %v", err)
	}
	for _, joined := range []bool{true, false} {
		name := "wait publication joins"
		if !joined {
			name = "wait publication never joins"
		}
		t.Run(name, func(t *testing.T) {
			dir := filepath.Join(t.TempDir(), "state")
			if err := os.Mkdir(dir, 0o700); err != nil {
				t.Fatal(err)
			}
			synctest.Test(t, func(t *testing.T) {
				// The real process above has exited. Model only the delayed State
				// publication (the interval while Cmd.Wait drains copied output).
				ps := &State{Cmd: cmd, Path: binary, Dir: dir, DirNeedsCleaning: true,
					StopTimeout: 20 * time.Second, waitDone: make(chan struct{})}
				result := make(chan error, 1)
				go func() { result <- ps.Stop() }()
				synctest.Wait()
				select {
				case err := <-result:
					t.Fatalf("Stop returned before joining the owned Wait: %v", err)
				default:
				}
				if _, err := os.Stat(dir); err != nil {
					t.Fatalf("state removed before Wait publication: %v", err)
				}
				if joined {
					ps.errMu.Lock()
					ps.exited = true
					ps.errMu.Unlock()
					close(ps.waitDone)
				}
				err := <-result // Virtual time advances to the original budget if unjoined.
				if joined {
					if err != nil {
						t.Fatalf("reaped owned child should stop cleanly: %v", err)
					}
					if _, err := os.Stat(dir); !os.IsNotExist(err) {
						t.Fatalf("state was not removed after confirmed exit: %v", err)
					}
				} else {
					if !errors.Is(err, context.DeadlineExceeded) || !errors.Is(err, syscall.EINVAL) {
						t.Fatalf("unjoined handle must retain timeout and kill error: %v", err)
					}
					if _, err := os.Stat(dir); err != nil {
						t.Fatalf("unconfirmed process state must be retained: %v", err)
					}
				}
			})
		})
	}
}
