// Code generated by //tools/envtest/cmd/sync from sigs.k8s.io/controller-runtime v0.24.1; DO NOT EDIT.
// Upstream Apache-2.0; see LICENSE. Cucina changes: import relocation and checked-in lifecycle patch.

// SPDX-License-Identifier: FSL-1.1-ALv2
//go:build !windows

// All non-Windows platforms retain the upstream Stop body and signal behavior.
package process

func stopPlatformSpecific(_ *State) (bool, error) { return false, nil }
