# SPDX-License-Identifier: FSL-1.1-ALv2
# network-online.target as soon as the primary ENI is configured (bb-worker.service waits for it).
[Service]
ExecStart=
ExecStart=/usr/lib/systemd/systemd-networkd-wait-online --any --timeout=60
