// SPDX-License-Identifier: FSL-1.1-ALv2

// Command sync regenerates the small, test-only envtest source closure from a
// checksum-pinned upstream module zip. It never changes the Go module cache.
package main

import (
	"archive/zip"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type manifest struct {
	Module        string                `json:"module"`
	Version       string                `json:"version"`
	ArchiveSHA256 string                `json:"archive_sha256"`
	Files         map[string]sourceFile `json:"files"`
}

type sourceFile struct {
	SHA256 string `json:"sha256"`
}

type replacement struct {
	File string `json:"file"`
	Old  string `json:"old"`
	New  string `json:"new"`
}

type patchSet struct {
	Replacements []replacement     `json:"replacements"`
	Additions    map[string]string `json:"additions"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "envtest sync:", err)
		os.Exit(1)
	}
}

func run() error {
	archive := flag.String("archive", "", "pinned upstream Go module zip")
	specPath := flag.String("manifest", "", "upstream version and per-file checksums")
	patchPath := flag.String("patches", "", "exact lifecycle replacements and additional source templates")
	out := flag.String("out", "", "generated envtest package directory")
	check := flag.Bool("check", false, "compare with checked-in sources without writing")
	flag.Parse()
	if *archive == "" || *specPath == "" || *patchPath == "" || *out == "" {
		return fmt.Errorf("--archive, --manifest, --patches and --out are required")
	}
	var spec manifest
	if err := readJSON(*specPath, &spec); err != nil {
		return err
	}
	var patches patchSet
	if err := readJSON(*patchPath, &patches); err != nil {
		return err
	}
	data, err := os.ReadFile(*archive)
	if err != nil {
		return err
	}
	if digest(data) != spec.ArchiveSHA256 {
		return fmt.Errorf("archive SHA256 mismatch")
	}
	zr, err := zip.NewReader(bytes.NewReader(data), int64(len(data)))
	if err != nil {
		return err
	}
	files := make(map[string][]byte, len(spec.Files)+len(patches.Additions))
	prefix := spec.Module + "@" + spec.Version + "/"
	for _, f := range zr.File {
		name, found := strings.CutPrefix(f.Name, prefix)
		want, selected := spec.Files[name]
		if !found || !selected {
			continue
		}
		r, err := f.Open()
		if err != nil {
			return err
		}
		body, readErr := io.ReadAll(r)
		closeErr := r.Close()
		if readErr != nil {
			return readErr
		}
		if closeErr != nil {
			return closeErr
		}
		if digest(body) != want.SHA256 {
			return fmt.Errorf("upstream file %s SHA256 mismatch", name)
		}
		files[name] = body
	}
	if len(files) != len(spec.Files) {
		return fmt.Errorf("upstream archive lacks selected files: found %d, expected %d", len(files), len(spec.Files))
	}
	for _, p := range patches.Replacements {
		body, ok := files[p.File]
		if !ok || p.Old == "" || bytes.Count(body, []byte(p.Old)) != 1 {
			return fmt.Errorf("patch for %s must match exactly once", p.File)
		}
		files[p.File] = bytes.Replace(body, []byte(p.Old), []byte(p.New), 1)
	}
	for name, template := range patches.Additions {
		if _, exists := files[name]; exists || !filepath.IsLocal(template) {
			return fmt.Errorf("invalid addition %s from %s", name, template)
		}
		body, err := os.ReadFile(filepath.Join(filepath.Dir(*patchPath), template))
		if err != nil {
			return err
		}
		files[name] = body
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	expectedSources := make(map[string]bool, len(files))
	for _, name := range names {
		rel := name
		if strings.HasPrefix(name, "pkg/envtest/") {
			rel = strings.TrimPrefix(name, "pkg/envtest/")
		} else if strings.HasPrefix(name, "pkg/internal/") {
			rel = strings.TrimPrefix(name, "pkg/")
		} else if name != "LICENSE" {
			return fmt.Errorf("unexpected source outside envtest closure: %s", name)
		}
		if !filepath.IsLocal(rel) {
			return fmt.Errorf("invalid source path %s", name)
		}
		body := files[name]
		if strings.HasSuffix(name, ".go") {
			expectedSources[filepath.ToSlash(rel)] = true
			text := string(body)
			text = strings.ReplaceAll(text, spec.Module+"/pkg/envtest", "github.com/sloper-ai/cucina/internal/envtest")
			text = strings.ReplaceAll(text, spec.Module+"/pkg/internal/", "github.com/sloper-ai/cucina/internal/envtest/internal/")
			text = "// Code generated by //tools/envtest/cmd/sync from " + spec.Module + " " + spec.Version + "; DO NOT EDIT.\n" +
				"// Upstream Apache-2.0; see LICENSE. Cucina changes: import relocation and checked-in lifecycle patch.\n\n" + text
			body, err = format.Source([]byte(text))
			if err != nil {
				return fmt.Errorf("format %s: %w", name, err)
			}
		}
		dest := filepath.Join(*out, rel)
		if *check {
			actual, err := os.ReadFile(dest)
			if err != nil {
				return err
			}
			if !bytes.Equal(actual, body) {
				return fmt.Errorf("generated file differs: %s", rel)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dest, body, 0o644); err != nil {
			return err
		}
	}
	if *check {
		if err := filepath.WalkDir(*out, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
				return nil
			}
			rel, err := filepath.Rel(*out, path)
			if err != nil {
				return err
			}
			key := filepath.ToSlash(rel)
			if !expectedSources[key] {
				return fmt.Errorf("unexpected generated source: %s", rel)
			}
			delete(expectedSources, key)
			return nil
		}); err != nil {
			return err
		}
		if len(expectedSources) != 0 {
			return fmt.Errorf("source inventory is missing %d expected Go files", len(expectedSources))
		}
	}
	fmt.Printf("envtest %s: %d generated files verified\n", spec.Version, len(files))
	return nil
}

func digest(b []byte) string {
	sum := sha256.Sum256(b)
	return hex.EncodeToString(sum[:])
}

func readJSON(path string, out any) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}
