{
 "title": "Buildbarn / BlobAccess",
 "tags": [
  "cucina",
  "buildbarn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "ac_backend_type",
    "label": "Action Cache backend type",
    "query": "label_values(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{storage_type=\"ac\"}, backend_type)"
   },
   {
    "name": "cas_backend_type",
    "label": "Content Addressable Storage backend type",
    "query": "label_values(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{storage_type=\"cas\"}, backend_type)"
   },
   {
    "name": "icas_backend_type",
    "label": "Indirect Content Addressable Storage backend type",
    "query": "label_values(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{storage_type=\"icas\"}, backend_type)"
   },
   {
    "name": "iscc_backend_type",
    "label": "Initial Size Class Cache backend type",
    "query": "label_values(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{storage_type=\"iscc\"}, backend_type)"
   },
   {
    "name": "kubernetes_service",
    "label": "Service name",
    "query": "label_values(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m, kubernetes_service)"
   }
  ]
 },
 "panels": [
  { "title": "Operation rate by operation", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Action Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"ac\",cluster=\"$cluster\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"cas\",cluster=\"$cluster\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"icas\",cluster=\"$cluster\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Operation rate by gRPC status code",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 }
  },
  {
   "title": "Action Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_grpc_code_kubernetes_service_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_count:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"ac\",cluster=\"$cluster\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_grpc_code_kubernetes_service_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_count:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"cas\",cluster=\"$cluster\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_grpc_code_kubernetes_service_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_count:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"icas\",cluster=\"$cluster\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(backend_type_grpc_code_kubernetes_service_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_count:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  { "title": "Get() duration", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Put() duration", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "FindMissing() duration", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 36 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"FindMissing\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"FindMissing\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"FindMissing\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"FindMissing\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Get() object size", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 45 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 46 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 46 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Get\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Put() object size", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 54 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",operation=\"Put\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "FindMissing() batch size", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 63 } },
  {
   "title": "Action Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_storage_type:buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket:irate1m{backend_type=~\"$ac_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"ac\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_storage_type:buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket:irate1m{backend_type=~\"$cas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"cas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Indirect Content Addressable Storage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_storage_type:buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket:irate1m{backend_type=~\"$icas_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"icas\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Initial Size Class Cache",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "targets": [
    {
     "expr": "sum(backend_type_kubernetes_service_le_storage_type:buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket:irate1m{backend_type=~\"$iscc_backend_type\",kubernetes_service=~\"$kubernetes_service\",storage_type=\"iscc\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}