{
 "title": "Buildbarn / Centralized storage",
 "tags": [
  "cucina",
  "buildbarn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Per-replica worst shard retention: whether it is safe to restart the other replica",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "icas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "iscc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_replica}}"
    }
   ]
  },
  {
   "title": "Per-shard best replica retention: amount of data accessible right now",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "icas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "iscc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "Per-shard worst replica retention: amount of data to remain accessible if a replica were to crash",
   "type": "row",
   "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 }
  },
  {
   "title": "ac",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "cas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "icas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  {
   "title": "iscc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_shard}}"
    }
   ]
  },
  { "title": "Key-location map: Get()", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "ac operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "cas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "icas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "iscc operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyAttempts"
    }
   ]
  },
  {
   "title": "ac operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "cas operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "icas operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "iscc operation attempts",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Key-location map: Put()", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 44 } },
  {
   "title": "ac operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "cas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "icas operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "iscc operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_ignored_invalid:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "IgnoredInvalid"
    },
    {
     "expr": "outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{outcome}}"
    },
    {
     "expr": "storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "TooManyIterations"
    }
   ]
  },
  {
   "title": "ac operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{storage_type=\"ac\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "cas operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{storage_type=\"cas\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "icas operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{storage_type=\"icas\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "iscc operation iterations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 53 },
   "targets": [
    {
     "expr": "le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m{storage_type=\"iscc\",cluster=\"$cluster\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}