{
 "title": "Buildbarn / FUSE",
 "tags": [
  "cucina",
  "buildbarn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "kubernetes_service",
    "label": "Service name",
    "query": "label_values(kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m, kubernetes_service)"
   },
   {
    "name": "operation",
    "label": "FUSE operation",
    "query": "label_values(kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m, operation)"
   },
   {
    "name": "callback",
    "label": "FUSE callback",
    "query": "label_values(callback_kubernetes_service_status_code:buildbarn_fuse_raw_file_system_callbacks:irate1m, callback)"
   },
   {
    "name": "status_code",
    "label": "Status code",
    "query": "label_values(status_code:buildbarn_fuse_raw_file_system_callbacks_and_operations:irate1m, status_code)"
   }
  ]
 },
 "panels": [
  { "title": "Operation rate", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=~\"$operation\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  {
   "title": "By FUSE operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=~\"$operation\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "By status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=~\"$operation\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  { "title": "Operation duration", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "Operation duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=~\"$operation\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "Callback rate", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(callback_kubernetes_service_status_code:buildbarn_fuse_raw_file_system_callbacks:irate1m{callback=~\"$callback\",kubernetes_service=~\"$kubernetes_service\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  {
   "title": "By FUSE callback",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(callback_kubernetes_service_status_code:buildbarn_fuse_raw_file_system_callbacks:irate1m{callback=~\"$callback\",kubernetes_service=~\"$kubernetes_service\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (callback)",
     "legendFormat": "{{callback}}"
    }
   ]
  },
  {
   "title": "By status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(callback_kubernetes_service_status_code:buildbarn_fuse_raw_file_system_callbacks:irate1m{callback=~\"$callback\",kubernetes_service=~\"$kubernetes_service\",status_code=~\"$status_code\",cluster=\"$cluster\"}) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}