{
 "title": "Buildbarn / BuildExecutor",
 "tags": [
  "cucina",
  "buildbarn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "kubernetes_service",
    "label": "Service name",
    "query": "label_values(kubernetes_service:buildbarn_builder_build_executor_operations:irate1m, kubernetes_service)"
   }
  ]
 },
 "panels": [
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "Operation rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "kubernetes_service:buildbarn_builder_build_executor_operations:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  {
   "title": "FetchingInputs stage duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_stage:buildbarn_builder_build_executor_duration_seconds_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",stage=\"FetchingInputs\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Running stage duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_stage:buildbarn_builder_build_executor_duration_seconds_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",stage=\"Running\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "UploadingOutputs stage duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_stage:buildbarn_builder_build_executor_duration_seconds_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",stage=\"UploadingOutputs\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Virtual execution duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_virtual_execution_duration_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "POSIX resource usage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 25 } },
  {
   "title": "CPU user time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_user_time_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU system time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_system_time_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Maximum resident set size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_maximum_resident_set_size_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Page reclaims",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_page_reclaims_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Page faults",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_page_faults_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Swaps",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_swaps_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block input operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_block_input_operations_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Block output operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_block_output_operations_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages sent",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_messages_sent_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Messages received",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_messages_received_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Signals received",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_signals_received_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Voluntary context switches",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_voluntary_context_switches_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Involuntary context switches",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_posix_involuntary_context_switches_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "File pool resource usage", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 58 } },
  {
   "title": "Files created",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_created_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peak file count",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_count_peak_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Peak file size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_size_bytes_peak_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Read operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 67 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_count_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=\"Read\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Write operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 67 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_count_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=\"Write\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Truncate operations",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 67 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_count_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=\"Truncate\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total read size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_size_bytes_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=\"Read\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total write size",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "sum(kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_size_bytes_bucket:irate1m{kubernetes_service=~\"$kubernetes_service\",operation=\"Write\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}