{
 "title": "Buildbarn / gRPC servers",
 "tags": [
  "cucina",
  "buildbarn"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "cluster", "query": "label_values(cluster)" },
   {
    "name": "grpc_service",
    "label": "gRPC service name",
    "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, grpc_service)"
   },
   {
    "name": "grpc_method",
    "label": "gRPC method name",
    "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, grpc_method)"
   },
   {
    "name": "grpc_code",
    "label": "gRPC status code",
    "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, grpc_code)"
   },
   {
    "name": "kubernetes_service",
    "label": "Kubernetes service name",
    "query": "label_values(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m, kubernetes_service)"
   }
  ]
 },
 "panels": [
  { "title": "Number of in-flight operations", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 0 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_in_flight:sum{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_in_flight:sum{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Operation rate", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 9 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By gRPC status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{grpc_code=~\"$grpc_code\",grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m{grpc_code=~\"$grpc_code\",grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Messages sent", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 18 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_sent:irate1m{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_sent:irate1m{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Messages received", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 27 } },
  {
   "title": "By gRPC method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_received:irate1m{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (grpc_service, grpc_method)",
     "legendFormat": "{{grpc_service}}.{{grpc_method}}"
    }
   ]
  },
  {
   "title": "By Kubernetes service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service:grpc_server_msg_received:irate1m{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (kubernetes_service)",
     "legendFormat": "{{kubernetes_service}}"
    }
   ]
  },
  { "title": "Timing", "type": "row", "gridPos": { "h": 1, "w": 0, "x": 0, "y": 36 } },
  {
   "title": "RPC duration",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "sum(grpc_method_grpc_service_kubernetes_service_le:grpc_server_handling_seconds_bucket:irate1m{grpc_method=~\"$grpc_method\",grpc_service=~\"$grpc_service\",kubernetes_service=~\"$kubernetes_service\",cluster=\"$cluster\"}) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}