// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cucina/v1/common.proto

package cucinav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtocolVersion is the version of the hostd<->controller protocol and of the
// management API. Both ends send it in their first message; a mismatch in the
// major component is refused with a precise message (R-TEST-7 handshake).
type ProtocolVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Major         uint32                 `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor         uint32                 `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolVersion) Reset() {
	*x = ProtocolVersion{}
	mi := &file_cucina_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolVersion) ProtoMessage() {}

func (x *ProtocolVersion) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolVersion.ProtoReflect.Descriptor instead.
func (*ProtocolVersion) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolVersion) GetMajor() uint32 {
	if x != nil {
		return x.Major
	}
	return 0
}

func (x *ProtocolVersion) GetMinor() uint32 {
	if x != nil {
		return x.Minor
	}
	return 0
}

// PlatformProperty is one REAPI platform property (name/value).
type PlatformProperty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformProperty) Reset() {
	*x = PlatformProperty{}
	mi := &file_cucina_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformProperty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformProperty) ProtoMessage() {}

func (x *PlatformProperty) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformProperty.ProtoReflect.Descriptor instead.
func (*PlatformProperty) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlatformProperty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlatformProperty) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// QueueRef identifies one Buildbarn size class queue.
type QueueRef struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceNamePrefix string                 `protobuf:"bytes,1,opt,name=instance_name_prefix,json=instanceNamePrefix,proto3" json:"instance_name_prefix,omitempty"`
	Platform           []*PlatformProperty    `protobuf:"bytes,2,rep,name=platform,proto3" json:"platform,omitempty"`
	SizeClass          uint32                 `protobuf:"varint,3,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueueRef) Reset() {
	*x = QueueRef{}
	mi := &file_cucina_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRef) ProtoMessage() {}

func (x *QueueRef) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRef.ProtoReflect.Descriptor instead.
func (*QueueRef) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *QueueRef) GetInstanceNamePrefix() string {
	if x != nil {
		return x.InstanceNamePrefix
	}
	return ""
}

func (x *QueueRef) GetPlatform() []*PlatformProperty {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *QueueRef) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

// Money is a USD amount in micro-dollars (avoids floats).
type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Micros        int64                  `protobuf:"varint,1,opt,name=micros,proto3" json:"micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_cucina_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *Money) GetMicros() int64 {
	if x != nil {
		return x.Micros
	}
	return 0
}

// Page controls list paging.
type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_cucina_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *Page) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Page) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Alert is a firing (or recently fired) alert shown in `status` and the TUI.
type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // info | warning | critical
	Summary       string                 `protobuf:"bytes,3,opt,name=summary,proto3" json:"summary,omitempty"`
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_cucina_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_cucina_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *Alert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Alert) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_cucina_v1_common_proto protoreflect.FileDescriptor

const file_cucina_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x16cucina/v1/common.proto\x12\tcucina.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"=\n" +
	"\x0fProtocolVersion\x12\x14\n" +
	"\x05major\x18\x01 \x01(\rR\x05major\x12\x14\n" +
	"\x05minor\x18\x02 \x01(\rR\x05minor\"<\n" +
	"\x10PlatformProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x94\x01\n" +
	"\bQueueRef\x120\n" +
	"\x14instance_name_prefix\x18\x01 \x01(\tR\x12instanceNamePrefix\x127\n" +
	"\bplatform\x18\x02 \x03(\v2\x1b.cucina.v1.PlatformPropertyR\bplatform\x12\x1d\n" +
	"\n" +
	"size_class\x18\x03 \x01(\rR\tsizeClass\"\x1f\n" +
	"\x05Money\x12\x16\n" +
	"\x06micros\x18\x01 \x01(\x03R\x06micros\"0\n" +
	"\x04Page\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\xf4\x01\n" +
	"\x05Alert\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x18\n" +
	"\asummary\x18\x03 \x01(\tR\asummary\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x124\n" +
	"\x06labels\x18\x05 \x03(\v2\x1c.cucina.v1.Alert.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B:Z8github.com/sloper-ai/cucina/api/proto/cucina/v1;cucinav1b\x06proto3"

var (
	file_cucina_v1_common_proto_rawDescOnce sync.Once
	file_cucina_v1_common_proto_rawDescData []byte
)

func file_cucina_v1_common_proto_rawDescGZIP() []byte {
	file_cucina_v1_common_proto_rawDescOnce.Do(func() {
		file_cucina_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cucina_v1_common_proto_rawDesc), len(file_cucina_v1_common_proto_rawDesc)))
	})
	return file_cucina_v1_common_proto_rawDescData
}

var file_cucina_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cucina_v1_common_proto_goTypes = []any{
	(*ProtocolVersion)(nil),       // 0: cucina.v1.ProtocolVersion
	(*PlatformProperty)(nil),      // 1: cucina.v1.PlatformProperty
	(*QueueRef)(nil),              // 2: cucina.v1.QueueRef
	(*Money)(nil),                 // 3: cucina.v1.Money
	(*Page)(nil),                  // 4: cucina.v1.Page
	(*Alert)(nil),                 // 5: cucina.v1.Alert
	nil,                           // 6: cucina.v1.Alert.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_cucina_v1_common_proto_depIdxs = []int32{
	1, // 0: cucina.v1.QueueRef.platform:type_name -> cucina.v1.PlatformProperty
	7, // 1: cucina.v1.Alert.since:type_name -> google.protobuf.Timestamp
	6, // 2: cucina.v1.Alert.labels:type_name -> cucina.v1.Alert.LabelsEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cucina_v1_common_proto_init() }
func file_cucina_v1_common_proto_init() {
	if File_cucina_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cucina_v1_common_proto_rawDesc), len(file_cucina_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cucina_v1_common_proto_goTypes,
		DependencyIndexes: file_cucina_v1_common_proto_depIdxs,
		MessageInfos:      file_cucina_v1_common_proto_msgTypes,
	}.Build()
	File_cucina_v1_common_proto = out.File
	file_cucina_v1_common_proto_goTypes = nil
	file_cucina_v1_common_proto_depIdxs = nil
}
