// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cucina/v1/enrollment.proto

package cucinav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnrollHostResponse_Status int32

const (
	EnrollHostResponse_STATUS_UNSPECIFIED   EnrollHostResponse_Status = 0
	EnrollHostResponse_STATUS_PENDING       EnrollHostResponse_Status = 1 // serial unknown/unapproved: poll again after retry_after
	EnrollHostResponse_STATUS_APPROVED      EnrollHostResponse_Status = 2 // certificate issued
	EnrollHostResponse_STATUS_DENIED        EnrollHostResponse_Status = 3 // serial revoked or re-enrollment of an existing serial (needs an admin)
	EnrollHostResponse_STATUS_TOKEN_INVALID EnrollHostResponse_Status = 4 // expired, revoked, wrong site, or max hosts reached
)

// Enum value maps for EnrollHostResponse_Status.
var (
	EnrollHostResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_APPROVED",
		3: "STATUS_DENIED",
		4: "STATUS_TOKEN_INVALID",
	}
	EnrollHostResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":   0,
		"STATUS_PENDING":       1,
		"STATUS_APPROVED":      2,
		"STATUS_DENIED":        3,
		"STATUS_TOKEN_INVALID": 4,
	}
)

func (x EnrollHostResponse_Status) Enum() *EnrollHostResponse_Status {
	p := new(EnrollHostResponse_Status)
	*p = x
	return p
}

func (x EnrollHostResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnrollHostResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cucina_v1_enrollment_proto_enumTypes[0].Descriptor()
}

func (EnrollHostResponse_Status) Type() protoreflect.EnumType {
	return &file_cucina_v1_enrollment_proto_enumTypes[0]
}

func (x EnrollHostResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnrollHostResponse_Status.Descriptor instead.
func (EnrollHostResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{6, 0}
}

type EnrollWorkerRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Protocol *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	// Raw JSON of http://169.254.169.254/latest/dynamic/instance-identity/document.
	InstanceIdentityDocument []byte `protobuf:"bytes,2,opt,name=instance_identity_document,json=instanceIdentityDocument,proto3" json:"instance_identity_document,omitempty"`
	// Base64 RSA-2048 signature: the body of …/instance-identity/rsa2048 (NOT /signature, which is
	// RSA-1024) — the controller verifies it against the AWS regional certificate over the document.
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	// PEM PKCS#10 CSR for a key the agent generated at boot (the key never leaves the instance).
	CsrPem        []byte `protobuf:"bytes,4,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	AgentVersion  string `protobuf:"bytes,5,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os            string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`     // linux | windows
	Arch          string `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"` // x86_64 | arm64
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollWorkerRequest) Reset() {
	*x = EnrollWorkerRequest{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollWorkerRequest) ProtoMessage() {}

func (x *EnrollWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollWorkerRequest.ProtoReflect.Descriptor instead.
func (*EnrollWorkerRequest) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollWorkerRequest) GetProtocol() *ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *EnrollWorkerRequest) GetInstanceIdentityDocument() []byte {
	if x != nil {
		return x.InstanceIdentityDocument
	}
	return nil
}

func (x *EnrollWorkerRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *EnrollWorkerRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollWorkerRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *EnrollWorkerRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EnrollWorkerRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

type EnrollWorkerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM leaf certificate (URI SAN spiffe://cucina/worker/<pool>/<instance-id>), <= 7 days.
	CertificatePem []byte `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	// PEM CA bundle (Cucina CA, possibly two during rotation).
	CaPem         []byte                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Pool          string                 `protobuf:"bytes,4,opt,name=pool,proto3" json:"pool,omitempty"`
	Generation    string                 `protobuf:"bytes,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Settings      *WorkerSettings        `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollWorkerResponse) Reset() {
	*x = EnrollWorkerResponse{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollWorkerResponse) ProtoMessage() {}

func (x *EnrollWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollWorkerResponse.ProtoReflect.Descriptor instead.
func (*EnrollWorkerResponse) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollWorkerResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EnrollWorkerResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollWorkerResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnrollWorkerResponse) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *EnrollWorkerResponse) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *EnrollWorkerResponse) GetSettings() *WorkerSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// WorkerSettings are the pool-level inputs of internal/bbconfig.RenderWorker /
// RenderRunner. The agent (EC2) or hostd (Tart) adds the machine-dependent parts
// (instance-store path, vCPUs, memory, paths) and writes the final configuration files.
type WorkerSettings struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Pool    string                 `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	Node    string                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"` // EC2 instance ID or "<host>/<vm>" — the `node` worker-id label
	Runners []*RunnerSettings      `protobuf:"bytes,3,rep,name=runners,proto3" json:"runners,omitempty"`
	// Where to connect.
	SchedulerEndpoint string `protobuf:"bytes,4,opt,name=scheduler_endpoint,json=schedulerEndpoint,proto3" json:"scheduler_endpoint,omitempty"` // host:port of the scheduler worker API (via the worker endpoint)
	StorageEndpoint   string `protobuf:"bytes,5,opt,name=storage_endpoint,json=storageEndpoint,proto3" json:"storage_endpoint,omitempty"`       // host:port of the frontend worker listener (CAS/AC); Mac VMs: hostd L2
	ServerName        string `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`                      // TLS server name to verify
	// Build directory and cache.
	BuildDirectory          string   `protobuf:"bytes,7,opt,name=build_directory,json=buildDirectory,proto3" json:"build_directory,omitempty"` // fuse | winfsp | nfsv4 | native
	L1Placement             string   `protobuf:"bytes,8,opt,name=l1_placement,json=l1Placement,proto3" json:"l1_placement,omitempty"`          // instance-store | ebs | memory | vm-disk | auto
	L1SizeBytes             uint64   `protobuf:"varint,9,opt,name=l1_size_bytes,json=l1SizeBytes,proto3" json:"l1_size_bytes,omitempty"`       // 0 = derive from the machine
	MaximumMessageSizeBytes uint64   `protobuf:"varint,10,opt,name=maximum_message_size_bytes,json=maximumMessageSizeBytes,proto3" json:"maximum_message_size_bytes,omitempty"`
	WanCompression          bool     `protobuf:"varint,11,opt,name=wan_compression,json=wanCompression,proto3" json:"wan_compression,omitempty"` // zstd encoderLevel 3 on the hop to the central endpoint (Mac sites)
	SizeClass               uint32   `protobuf:"varint,12,opt,name=size_class,json=sizeClass,proto3" json:"size_class,omitempty"`
	InstanceNamePrefixes    []string `protobuf:"bytes,13,rep,name=instance_name_prefixes,json=instanceNamePrefixes,proto3" json:"instance_name_prefixes,omitempty"`
	// Dead-man switch (R-POOL-7).
	Deadman *DeadmanSettings `protobuf:"bytes,14,opt,name=deadman,proto3" json:"deadman,omitempty"`
	// Metrics: Prometheus HTTP-SD is served by the controller; workers expose bb_worker /metrics
	// on this port (allowed from the cluster SG). Mac VMs push via hostd.
	MetricsPort    uint32 `protobuf:"varint,15,opt,name=metrics_port,json=metricsPort,proto3" json:"metrics_port,omitempty"`
	PushgatewayUrl string `protobuf:"bytes,16,opt,name=pushgateway_url,json=pushgatewayUrl,proto3" json:"pushgateway_url,omitempty"`
	// Free-form extra environment for the services (for example proxies); never secrets.
	Env map[string]string `protobuf:"bytes,17,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Spot interruption handling: SIGTERM bb_worker on the 2-minute notice (R-POOL-2 SHOULD).
	HandleSpotInterruption bool `protobuf:"varint,18,opt,name=handle_spot_interruption,json=handleSpotInterruption,proto3" json:"handle_spot_interruption,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *WorkerSettings) Reset() {
	*x = WorkerSettings{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerSettings) ProtoMessage() {}

func (x *WorkerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerSettings.ProtoReflect.Descriptor instead.
func (*WorkerSettings) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerSettings) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *WorkerSettings) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *WorkerSettings) GetRunners() []*RunnerSettings {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *WorkerSettings) GetSchedulerEndpoint() string {
	if x != nil {
		return x.SchedulerEndpoint
	}
	return ""
}

func (x *WorkerSettings) GetStorageEndpoint() string {
	if x != nil {
		return x.StorageEndpoint
	}
	return ""
}

func (x *WorkerSettings) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *WorkerSettings) GetBuildDirectory() string {
	if x != nil {
		return x.BuildDirectory
	}
	return ""
}

func (x *WorkerSettings) GetL1Placement() string {
	if x != nil {
		return x.L1Placement
	}
	return ""
}

func (x *WorkerSettings) GetL1SizeBytes() uint64 {
	if x != nil {
		return x.L1SizeBytes
	}
	return 0
}

func (x *WorkerSettings) GetMaximumMessageSizeBytes() uint64 {
	if x != nil {
		return x.MaximumMessageSizeBytes
	}
	return 0
}

func (x *WorkerSettings) GetWanCompression() bool {
	if x != nil {
		return x.WanCompression
	}
	return false
}

func (x *WorkerSettings) GetSizeClass() uint32 {
	if x != nil {
		return x.SizeClass
	}
	return 0
}

func (x *WorkerSettings) GetInstanceNamePrefixes() []string {
	if x != nil {
		return x.InstanceNamePrefixes
	}
	return nil
}

func (x *WorkerSettings) GetDeadman() *DeadmanSettings {
	if x != nil {
		return x.Deadman
	}
	return nil
}

func (x *WorkerSettings) GetMetricsPort() uint32 {
	if x != nil {
		return x.MetricsPort
	}
	return 0
}

func (x *WorkerSettings) GetPushgatewayUrl() string {
	if x != nil {
		return x.PushgatewayUrl
	}
	return ""
}

func (x *WorkerSettings) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *WorkerSettings) GetHandleSpotInterruption() bool {
	if x != nil {
		return x.HandleSpotInterruption
	}
	return false
}

type RunnerSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                // native | qemu-rv64g | xcode | generic | …
	Platform      []*PlatformProperty    `protobuf:"bytes,2,rep,name=platform,proto3" json:"platform,omitempty"`        // exact REAPI property set
	Concurrency   uint32                 `protobuf:"varint,3,opt,name=concurrency,proto3" json:"concurrency,omitempty"` // 0 = derive (vCPUs)
	Emulator      string                 `protobuf:"bytes,4,opt,name=emulator,proto3" json:"emulator,omitempty"`        // e.g. "qemu-riscv64" for emulated runners
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerSettings) Reset() {
	*x = RunnerSettings{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerSettings) ProtoMessage() {}

func (x *RunnerSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerSettings.ProtoReflect.Descriptor instead.
func (*RunnerSettings) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *RunnerSettings) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RunnerSettings) GetPlatform() []*PlatformProperty {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *RunnerSettings) GetConcurrency() uint32 {
	if x != nil {
		return x.Concurrency
	}
	return 0
}

func (x *RunnerSettings) GetEmulator() string {
	if x != nil {
		return x.Emulator
	}
	return ""
}

type DeadmanSettings struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IdleLimit        *durationpb.Duration   `protobuf:"bytes,1,opt,name=idle_limit,json=idleLimit,proto3" json:"idle_limit,omitempty"`                      // default 30m
	UnreachableLimit *durationpb.Duration   `protobuf:"bytes,2,opt,name=unreachable_limit,json=unreachableLimit,proto3" json:"unreachable_limit,omitempty"` // default 10m
	MaxUptime        *durationpb.Duration   `protobuf:"bytes,3,opt,name=max_uptime,json=maxUptime,proto3" json:"max_uptime,omitempty"`                      // default 12h
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeadmanSettings) Reset() {
	*x = DeadmanSettings{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadmanSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadmanSettings) ProtoMessage() {}

func (x *DeadmanSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadmanSettings.ProtoReflect.Descriptor instead.
func (*DeadmanSettings) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *DeadmanSettings) GetIdleLimit() *durationpb.Duration {
	if x != nil {
		return x.IdleLimit
	}
	return nil
}

func (x *DeadmanSettings) GetUnreachableLimit() *durationpb.Duration {
	if x != nil {
		return x.UnreachableLimit
	}
	return nil
}

func (x *DeadmanSettings) GetMaxUptime() *durationpb.Duration {
	if x != nil {
		return x.MaxUptime
	}
	return nil
}

type EnrollHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SiteToken     string                 `protobuf:"bytes,2,opt,name=site_token,json=siteToken,proto3" json:"site_token,omitempty"` // the multi-use site enrollment token (never logged)
	SerialNumber  string                 `protobuf:"bytes,3,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Hostname      string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,5,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // key generated by hostd, kept in the System keychain
	Facts         *HostFacts             `protobuf:"bytes,6,opt,name=facts,proto3" json:"facts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollHostRequest) Reset() {
	*x = EnrollHostRequest{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollHostRequest) ProtoMessage() {}

func (x *EnrollHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollHostRequest.ProtoReflect.Descriptor instead.
func (*EnrollHostRequest) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *EnrollHostRequest) GetProtocol() *ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *EnrollHostRequest) GetSiteToken() string {
	if x != nil {
		return x.SiteToken
	}
	return ""
}

func (x *EnrollHostRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *EnrollHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *EnrollHostRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EnrollHostRequest) GetFacts() *HostFacts {
	if x != nil {
		return x.Facts
	}
	return nil
}

type EnrollHostResponse struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Status         EnrollHostResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=cucina.v1.EnrollHostResponse_Status" json:"status,omitempty"`
	Message        string                    `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CertificatePem []byte                    `protobuf:"bytes,3,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"` // URI SAN spiffe://cucina/host/<serial>
	CaPem          []byte                    `protobuf:"bytes,4,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	ExpiresAt      *timestamppb.Timestamp    `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RetryAfter     *durationpb.Duration      `protobuf:"bytes,6,opt,name=retry_after,json=retryAfter,proto3" json:"retry_after,omitempty"`
	HostEndpoint   string                    `protobuf:"bytes,7,opt,name=host_endpoint,json=hostEndpoint,proto3" json:"host_endpoint,omitempty"` // address of HostService (mTLS)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnrollHostResponse) Reset() {
	*x = EnrollHostResponse{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollHostResponse) ProtoMessage() {}

func (x *EnrollHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollHostResponse.ProtoReflect.Descriptor instead.
func (*EnrollHostResponse) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{6}
}

func (x *EnrollHostResponse) GetStatus() EnrollHostResponse_Status {
	if x != nil {
		return x.Status
	}
	return EnrollHostResponse_STATUS_UNSPECIFIED
}

func (x *EnrollHostResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnrollHostResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EnrollHostResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollHostResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EnrollHostResponse) GetRetryAfter() *durationpb.Duration {
	if x != nil {
		return x.RetryAfter
	}
	return nil
}

func (x *EnrollHostResponse) GetHostEndpoint() string {
	if x != nil {
		return x.HostEndpoint
	}
	return ""
}

// HostFacts are reported at enrollment and at every Connect (R-MAC-5).
type HostFacts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Chip          string                 `protobuf:"bytes,2,opt,name=chip,proto3" json:"chip,omitempty"`
	Cores         uint32                 `protobuf:"varint,3,opt,name=cores,proto3" json:"cores,omitempty"`
	MemoryGib     uint32                 `protobuf:"varint,4,opt,name=memory_gib,json=memoryGib,proto3" json:"memory_gib,omitempty"`
	DiskFreeGib   uint32                 `protobuf:"varint,5,opt,name=disk_free_gib,json=diskFreeGib,proto3" json:"disk_free_gib,omitempty"`
	MacosVersion  string                 `protobuf:"bytes,6,opt,name=macos_version,json=macosVersion,proto3" json:"macos_version,omitempty"`
	TartVersion   string                 `protobuf:"bytes,7,opt,name=tart_version,json=tartVersion,proto3" json:"tart_version,omitempty"`
	AgentVersion  string                 `protobuf:"bytes,8,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Filevault     string                 `protobuf:"bytes,9,opt,name=filevault,proto3" json:"filevault,omitempty"` // "off" | "on" | "unknown"
	Site          string                 `protobuf:"bytes,10,opt,name=site,proto3" json:"site,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,11,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostFacts) Reset() {
	*x = HostFacts{}
	mi := &file_cucina_v1_enrollment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostFacts) ProtoMessage() {}

func (x *HostFacts) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_enrollment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostFacts.ProtoReflect.Descriptor instead.
func (*HostFacts) Descriptor() ([]byte, []int) {
	return file_cucina_v1_enrollment_proto_rawDescGZIP(), []int{7}
}

func (x *HostFacts) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *HostFacts) GetChip() string {
	if x != nil {
		return x.Chip
	}
	return ""
}

func (x *HostFacts) GetCores() uint32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *HostFacts) GetMemoryGib() uint32 {
	if x != nil {
		return x.MemoryGib
	}
	return 0
}

func (x *HostFacts) GetDiskFreeGib() uint32 {
	if x != nil {
		return x.DiskFreeGib
	}
	return 0
}

func (x *HostFacts) GetMacosVersion() string {
	if x != nil {
		return x.MacosVersion
	}
	return ""
}

func (x *HostFacts) GetTartVersion() string {
	if x != nil {
		return x.TartVersion
	}
	return ""
}

func (x *HostFacts) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HostFacts) GetFilevault() string {
	if x != nil {
		return x.Filevault
	}
	return ""
}

func (x *HostFacts) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *HostFacts) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_cucina_v1_enrollment_proto protoreflect.FileDescriptor

const file_cucina_v1_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1acucina/v1/enrollment.proto\x12\tcucina.v1\x1a\x16cucina/v1/common.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8b\x02\n" +
	"\x13EnrollWorkerRequest\x126\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1a.cucina.v1.ProtocolVersionR\bprotocol\x12<\n" +
	"\x1ainstance_identity_document\x18\x02 \x01(\fR\x18instanceIdentityDocument\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x17\n" +
	"\acsr_pem\x18\x04 \x01(\fR\x06csrPem\x12#\n" +
	"\ragent_version\x18\x05 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x06 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\a \x01(\tR\x04arch\"\xfc\x01\n" +
	"\x14EnrollWorkerResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x12\n" +
	"\x04pool\x18\x04 \x01(\tR\x04pool\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\tR\n" +
	"generation\x125\n" +
	"\bsettings\x18\x06 \x01(\v2\x19.cucina.v1.WorkerSettingsR\bsettings\"\xbd\x06\n" +
	"\x0eWorkerSettings\x12\x12\n" +
	"\x04pool\x18\x01 \x01(\tR\x04pool\x12\x12\n" +
	"\x04node\x18\x02 \x01(\tR\x04node\x123\n" +
	"\arunners\x18\x03 \x03(\v2\x19.cucina.v1.RunnerSettingsR\arunners\x12-\n" +
	"\x12scheduler_endpoint\x18\x04 \x01(\tR\x11schedulerEndpoint\x12)\n" +
	"\x10storage_endpoint\x18\x05 \x01(\tR\x0fstorageEndpoint\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\x12'\n" +
	"\x0fbuild_directory\x18\a \x01(\tR\x0ebuildDirectory\x12!\n" +
	"\fl1_placement\x18\b \x01(\tR\vl1Placement\x12\"\n" +
	"\rl1_size_bytes\x18\t \x01(\x04R\vl1SizeBytes\x12;\n" +
	"\x1amaximum_message_size_bytes\x18\n" +
	" \x01(\x04R\x17maximumMessageSizeBytes\x12'\n" +
	"\x0fwan_compression\x18\v \x01(\bR\x0ewanCompression\x12\x1d\n" +
	"\n" +
	"size_class\x18\f \x01(\rR\tsizeClass\x124\n" +
	"\x16instance_name_prefixes\x18\r \x03(\tR\x14instanceNamePrefixes\x124\n" +
	"\adeadman\x18\x0e \x01(\v2\x1a.cucina.v1.DeadmanSettingsR\adeadman\x12!\n" +
	"\fmetrics_port\x18\x0f \x01(\rR\vmetricsPort\x12'\n" +
	"\x0fpushgateway_url\x18\x10 \x01(\tR\x0epushgatewayUrl\x124\n" +
	"\x03env\x18\x11 \x03(\v2\".cucina.v1.WorkerSettings.EnvEntryR\x03env\x128\n" +
	"\x18handle_spot_interruption\x18\x12 \x01(\bR\x16handleSpotInterruption\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9b\x01\n" +
	"\x0eRunnerSettings\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\bplatform\x18\x02 \x03(\v2\x1b.cucina.v1.PlatformPropertyR\bplatform\x12 \n" +
	"\vconcurrency\x18\x03 \x01(\rR\vconcurrency\x12\x1a\n" +
	"\bemulator\x18\x04 \x01(\tR\bemulator\"\xcd\x01\n" +
	"\x0fDeadmanSettings\x128\n" +
	"\n" +
	"idle_limit\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\tidleLimit\x12F\n" +
	"\x11unreachable_limit\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x10unreachableLimit\x128\n" +
	"\n" +
	"max_uptime\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\tmaxUptime\"\xf0\x01\n" +
	"\x11EnrollHostRequest\x126\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1a.cucina.v1.ProtocolVersionR\bprotocol\x12\x1d\n" +
	"\n" +
	"site_token\x18\x02 \x01(\tR\tsiteToken\x12#\n" +
	"\rserial_number\x18\x03 \x01(\tR\fserialNumber\x12\x1a\n" +
	"\bhostname\x18\x04 \x01(\tR\bhostname\x12\x17\n" +
	"\acsr_pem\x18\x05 \x01(\fR\x06csrPem\x12*\n" +
	"\x05facts\x18\x06 \x01(\v2\x14.cucina.v1.HostFactsR\x05facts\"\xc0\x03\n" +
	"\x12EnrollHostResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\x0e2$.cucina.v1.EnrollHostResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fcertificate_pem\x18\x03 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x04 \x01(\fR\x05caPem\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12:\n" +
	"\vretry_after\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"retryAfter\x12#\n" +
	"\rhost_endpoint\x18\a \x01(\tR\fhostEndpoint\"v\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x02\x12\x11\n" +
	"\rSTATUS_DENIED\x10\x03\x12\x18\n" +
	"\x14STATUS_TOKEN_INVALID\x10\x04\"\xa2\x03\n" +
	"\tHostFacts\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x12\n" +
	"\x04chip\x18\x02 \x01(\tR\x04chip\x12\x14\n" +
	"\x05cores\x18\x03 \x01(\rR\x05cores\x12\x1d\n" +
	"\n" +
	"memory_gib\x18\x04 \x01(\rR\tmemoryGib\x12\"\n" +
	"\rdisk_free_gib\x18\x05 \x01(\rR\vdiskFreeGib\x12#\n" +
	"\rmacos_version\x18\x06 \x01(\tR\fmacosVersion\x12!\n" +
	"\ftart_version\x18\a \x01(\tR\vtartVersion\x12#\n" +
	"\ragent_version\x18\b \x01(\tR\fagentVersion\x12\x1c\n" +
	"\tfilevault\x18\t \x01(\tR\tfilevault\x12\x12\n" +
	"\x04site\x18\n" +
	" \x01(\tR\x04site\x128\n" +
	"\x06labels\x18\v \x03(\v2 .cucina.v1.HostFacts.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xaf\x01\n" +
	"\x11EnrollmentService\x12O\n" +
	"\fEnrollWorker\x12\x1e.cucina.v1.EnrollWorkerRequest\x1a\x1f.cucina.v1.EnrollWorkerResponse\x12I\n" +
	"\n" +
	"EnrollHost\x12\x1c.cucina.v1.EnrollHostRequest\x1a\x1d.cucina.v1.EnrollHostResponseB:Z8github.com/sloper-ai/cucina/api/proto/cucina/v1;cucinav1b\x06proto3"

var (
	file_cucina_v1_enrollment_proto_rawDescOnce sync.Once
	file_cucina_v1_enrollment_proto_rawDescData []byte
)

func file_cucina_v1_enrollment_proto_rawDescGZIP() []byte {
	file_cucina_v1_enrollment_proto_rawDescOnce.Do(func() {
		file_cucina_v1_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cucina_v1_enrollment_proto_rawDesc), len(file_cucina_v1_enrollment_proto_rawDesc)))
	})
	return file_cucina_v1_enrollment_proto_rawDescData
}

var file_cucina_v1_enrollment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cucina_v1_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cucina_v1_enrollment_proto_goTypes = []any{
	(EnrollHostResponse_Status)(0), // 0: cucina.v1.EnrollHostResponse.Status
	(*EnrollWorkerRequest)(nil),    // 1: cucina.v1.EnrollWorkerRequest
	(*EnrollWorkerResponse)(nil),   // 2: cucina.v1.EnrollWorkerResponse
	(*WorkerSettings)(nil),         // 3: cucina.v1.WorkerSettings
	(*RunnerSettings)(nil),         // 4: cucina.v1.RunnerSettings
	(*DeadmanSettings)(nil),        // 5: cucina.v1.DeadmanSettings
	(*EnrollHostRequest)(nil),      // 6: cucina.v1.EnrollHostRequest
	(*EnrollHostResponse)(nil),     // 7: cucina.v1.EnrollHostResponse
	(*HostFacts)(nil),              // 8: cucina.v1.HostFacts
	nil,                            // 9: cucina.v1.WorkerSettings.EnvEntry
	nil,                            // 10: cucina.v1.HostFacts.LabelsEntry
	(*ProtocolVersion)(nil),        // 11: cucina.v1.ProtocolVersion
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
	(*PlatformProperty)(nil),       // 13: cucina.v1.PlatformProperty
	(*durationpb.Duration)(nil),    // 14: google.protobuf.Duration
}
var file_cucina_v1_enrollment_proto_depIdxs = []int32{
	11, // 0: cucina.v1.EnrollWorkerRequest.protocol:type_name -> cucina.v1.ProtocolVersion
	12, // 1: cucina.v1.EnrollWorkerResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 2: cucina.v1.EnrollWorkerResponse.settings:type_name -> cucina.v1.WorkerSettings
	4,  // 3: cucina.v1.WorkerSettings.runners:type_name -> cucina.v1.RunnerSettings
	5,  // 4: cucina.v1.WorkerSettings.deadman:type_name -> cucina.v1.DeadmanSettings
	9,  // 5: cucina.v1.WorkerSettings.env:type_name -> cucina.v1.WorkerSettings.EnvEntry
	13, // 6: cucina.v1.RunnerSettings.platform:type_name -> cucina.v1.PlatformProperty
	14, // 7: cucina.v1.DeadmanSettings.idle_limit:type_name -> google.protobuf.Duration
	14, // 8: cucina.v1.DeadmanSettings.unreachable_limit:type_name -> google.protobuf.Duration
	14, // 9: cucina.v1.DeadmanSettings.max_uptime:type_name -> google.protobuf.Duration
	11, // 10: cucina.v1.EnrollHostRequest.protocol:type_name -> cucina.v1.ProtocolVersion
	8,  // 11: cucina.v1.EnrollHostRequest.facts:type_name -> cucina.v1.HostFacts
	0,  // 12: cucina.v1.EnrollHostResponse.status:type_name -> cucina.v1.EnrollHostResponse.Status
	12, // 13: cucina.v1.EnrollHostResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 14: cucina.v1.EnrollHostResponse.retry_after:type_name -> google.protobuf.Duration
	10, // 15: cucina.v1.HostFacts.labels:type_name -> cucina.v1.HostFacts.LabelsEntry
	1,  // 16: cucina.v1.EnrollmentService.EnrollWorker:input_type -> cucina.v1.EnrollWorkerRequest
	6,  // 17: cucina.v1.EnrollmentService.EnrollHost:input_type -> cucina.v1.EnrollHostRequest
	2,  // 18: cucina.v1.EnrollmentService.EnrollWorker:output_type -> cucina.v1.EnrollWorkerResponse
	7,  // 19: cucina.v1.EnrollmentService.EnrollHost:output_type -> cucina.v1.EnrollHostResponse
	18, // [18:20] is the sub-list for method output_type
	16, // [16:18] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_cucina_v1_enrollment_proto_init() }
func file_cucina_v1_enrollment_proto_init() {
	if File_cucina_v1_enrollment_proto != nil {
		return
	}
	file_cucina_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cucina_v1_enrollment_proto_rawDesc), len(file_cucina_v1_enrollment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cucina_v1_enrollment_proto_goTypes,
		DependencyIndexes: file_cucina_v1_enrollment_proto_depIdxs,
		EnumInfos:         file_cucina_v1_enrollment_proto_enumTypes,
		MessageInfos:      file_cucina_v1_enrollment_proto_msgTypes,
	}.Build()
	File_cucina_v1_enrollment_proto = out.File
	file_cucina_v1_enrollment_proto_goTypes = nil
	file_cucina_v1_enrollment_proto_depIdxs = nil
}
