// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cucina/v1/enrollment.proto

package cucinav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EnrollmentService_EnrollWorker_FullMethodName = "/cucina.v1.EnrollmentService/EnrollWorker"
	EnrollmentService_EnrollHost_FullMethodName   = "/cucina.v1.EnrollmentService/EnrollHost"
)

// EnrollmentServiceClient is the client API for EnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EnrollmentService is served by the controller on the worker endpoint
// (TLS server authentication with a certificate from Cucina's CA; client
// certificates are NOT required because the callers have none yet). Callers
// authenticate through the request itself:
//   - EC2 workers: the AWS-signed instance identity document (R-SEC-3), verified
//     against the AWS public certificate and cross-checked with a tag-filtered
//     DescribeInstances call (pool tags, instance state, launch age).
//   - Mac hosts: a multi-use site enrollment token + serial number + CSR. The
//     controller admits only pre-registered or approved serial numbers.
//
// No long-lived secret is baked into any image or package (R-SEC-3, UC23).
type EnrollmentServiceClient interface {
	// EnrollWorker is called at EVERY boot of an EC2 worker by `cucina-worker-agent bootstrap`.
	EnrollWorker(ctx context.Context, in *EnrollWorkerRequest, opts ...grpc.CallOption) (*EnrollWorkerResponse, error)
	// EnrollHost is called by cucina-hostd on first start (and re-polled while PENDING).
	EnrollHost(ctx context.Context, in *EnrollHostRequest, opts ...grpc.CallOption) (*EnrollHostResponse, error)
}

type enrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEnrollmentServiceClient(cc grpc.ClientConnInterface) EnrollmentServiceClient {
	return &enrollmentServiceClient{cc}
}

func (c *enrollmentServiceClient) EnrollWorker(ctx context.Context, in *EnrollWorkerRequest, opts ...grpc.CallOption) (*EnrollWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollWorkerResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_EnrollWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *enrollmentServiceClient) EnrollHost(ctx context.Context, in *EnrollHostRequest, opts ...grpc.CallOption) (*EnrollHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollHostResponse)
	err := c.cc.Invoke(ctx, EnrollmentService_EnrollHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EnrollmentServiceServer is the server API for EnrollmentService service.
// All implementations must embed UnimplementedEnrollmentServiceServer
// for forward compatibility.
//
// EnrollmentService is served by the controller on the worker endpoint
// (TLS server authentication with a certificate from Cucina's CA; client
// certificates are NOT required because the callers have none yet). Callers
// authenticate through the request itself:
//   - EC2 workers: the AWS-signed instance identity document (R-SEC-3), verified
//     against the AWS public certificate and cross-checked with a tag-filtered
//     DescribeInstances call (pool tags, instance state, launch age).
//   - Mac hosts: a multi-use site enrollment token + serial number + CSR. The
//     controller admits only pre-registered or approved serial numbers.
//
// No long-lived secret is baked into any image or package (R-SEC-3, UC23).
type EnrollmentServiceServer interface {
	// EnrollWorker is called at EVERY boot of an EC2 worker by `cucina-worker-agent bootstrap`.
	EnrollWorker(context.Context, *EnrollWorkerRequest) (*EnrollWorkerResponse, error)
	// EnrollHost is called by cucina-hostd on first start (and re-polled while PENDING).
	EnrollHost(context.Context, *EnrollHostRequest) (*EnrollHostResponse, error)
	mustEmbedUnimplementedEnrollmentServiceServer()
}

// UnimplementedEnrollmentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEnrollmentServiceServer struct{}

func (UnimplementedEnrollmentServiceServer) EnrollWorker(context.Context, *EnrollWorkerRequest) (*EnrollWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollWorker not implemented")
}
func (UnimplementedEnrollmentServiceServer) EnrollHost(context.Context, *EnrollHostRequest) (*EnrollHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrollHost not implemented")
}
func (UnimplementedEnrollmentServiceServer) mustEmbedUnimplementedEnrollmentServiceServer() {}
func (UnimplementedEnrollmentServiceServer) testEmbeddedByValue()                           {}

// UnsafeEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EnrollmentServiceServer will
// result in compilation errors.
type UnsafeEnrollmentServiceServer interface {
	mustEmbedUnimplementedEnrollmentServiceServer()
}

func RegisterEnrollmentServiceServer(s grpc.ServiceRegistrar, srv EnrollmentServiceServer) {
	// If the following call panics, it indicates UnimplementedEnrollmentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EnrollmentService_ServiceDesc, srv)
}

func _EnrollmentService_EnrollWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).EnrollWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_EnrollWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).EnrollWorker(ctx, req.(*EnrollWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EnrollmentService_EnrollHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EnrollmentServiceServer).EnrollHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EnrollmentService_EnrollHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EnrollmentServiceServer).EnrollHost(ctx, req.(*EnrollHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EnrollmentService_ServiceDesc is the grpc.ServiceDesc for EnrollmentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cucina.v1.EnrollmentService",
	HandlerType: (*EnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnrollWorker",
			Handler:    _EnrollmentService_EnrollWorker_Handler,
		},
		{
			MethodName: "EnrollHost",
			Handler:    _EnrollmentService_EnrollHost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cucina/v1/enrollment.proto",
}
