// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cucina/v1/host.proto

package cucinav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*HostMessage_Hello
	//	*HostMessage_Heartbeat
	//	*HostMessage_VmEvent
	//	*HostMessage_CommandResult
	//	*HostMessage_Log
	Message       isHostMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_cucina_v1_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{0}
}

func (x *HostMessage) GetMessage() isHostMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *HostMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *HostMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *HostMessage) GetVmEvent() *VMEvent {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_VmEvent); ok {
			return x.VmEvent
		}
	}
	return nil
}

func (x *HostMessage) GetCommandResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_CommandResult); ok {
			return x.CommandResult
		}
	}
	return nil
}

func (x *HostMessage) GetLog() *LogData {
	if x != nil {
		if x, ok := x.Message.(*HostMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

type isHostMessage_Message interface {
	isHostMessage_Message()
}

type HostMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HostMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type HostMessage_VmEvent struct {
	VmEvent *VMEvent `protobuf:"bytes,3,opt,name=vm_event,json=vmEvent,proto3,oneof"`
}

type HostMessage_CommandResult struct {
	CommandResult *CommandResult `protobuf:"bytes,4,opt,name=command_result,json=commandResult,proto3,oneof"`
}

type HostMessage_Log struct {
	Log *LogData `protobuf:"bytes,5,opt,name=log,proto3,oneof"`
}

func (*HostMessage_Hello) isHostMessage_Message() {}

func (*HostMessage_Heartbeat) isHostMessage_Message() {}

func (*HostMessage_VmEvent) isHostMessage_Message() {}

func (*HostMessage_CommandResult) isHostMessage_Message() {}

func (*HostMessage_Log) isHostMessage_Message() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Facts         *HostFacts             `protobuf:"bytes,3,opt,name=facts,proto3" json:"facts,omitempty"`
	Vms           []*VMInfo              `protobuf:"bytes,4,rep,name=vms,proto3" json:"vms,omitempty"`       // VMs present on the host (inventory after restart)
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"` // cached Tart image references
	BootId        string                 `protobuf:"bytes,6,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_cucina_v1_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetProtocol() *ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *Hello) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *Hello) GetFacts() *HostFacts {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *Hello) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *Hello) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Hello) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Vms           []*VMInfo              `protobuf:"bytes,2,rep,name=vms,proto3" json:"vms,omitempty"`
	Metrics       *HostMetrics           `protobuf:"bytes,3,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Cordoned      bool                   `protobuf:"varint,4,opt,name=cordoned,proto3" json:"cordoned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_cucina_v1_host_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Heartbeat) GetVms() []*VMInfo {
	if x != nil {
		return x.Vms
	}
	return nil
}

func (x *Heartbeat) GetMetrics() *HostMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Heartbeat) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

type HostMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunningVms    uint32                 `protobuf:"varint,1,opt,name=running_vms,json=runningVms,proto3" json:"running_vms,omitempty"`
	DiskFreeBytes uint64                 `protobuf:"varint,2,opt,name=disk_free_bytes,json=diskFreeBytes,proto3" json:"disk_free_bytes,omitempty"`
	CpuLoad       float32                `protobuf:"fixed32,3,opt,name=cpu_load,json=cpuLoad,proto3" json:"cpu_load,omitempty"`
	// L2 cache (host bb_storage) accounting (R-CACHE-4, R-DATA-7).
	L2Hits           uint64 `protobuf:"varint,4,opt,name=l2_hits,json=l2Hits,proto3" json:"l2_hits,omitempty"`
	L2Misses         uint64 `protobuf:"varint,5,opt,name=l2_misses,json=l2Misses,proto3" json:"l2_misses,omitempty"`
	WanBytesReceived uint64 `protobuf:"varint,6,opt,name=wan_bytes_received,json=wanBytesReceived,proto3" json:"wan_bytes_received,omitempty"`
	WanBytesSent     uint64 `protobuf:"varint,7,opt,name=wan_bytes_sent,json=wanBytesSent,proto3" json:"wan_bytes_sent,omitempty"`
	L2SizeBytes      uint64 `protobuf:"varint,8,opt,name=l2_size_bytes,json=l2SizeBytes,proto3" json:"l2_size_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HostMetrics) Reset() {
	*x = HostMetrics{}
	mi := &file_cucina_v1_host_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMetrics) ProtoMessage() {}

func (x *HostMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMetrics.ProtoReflect.Descriptor instead.
func (*HostMetrics) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{3}
}

func (x *HostMetrics) GetRunningVms() uint32 {
	if x != nil {
		return x.RunningVms
	}
	return 0
}

func (x *HostMetrics) GetDiskFreeBytes() uint64 {
	if x != nil {
		return x.DiskFreeBytes
	}
	return 0
}

func (x *HostMetrics) GetCpuLoad() float32 {
	if x != nil {
		return x.CpuLoad
	}
	return 0
}

func (x *HostMetrics) GetL2Hits() uint64 {
	if x != nil {
		return x.L2Hits
	}
	return 0
}

func (x *HostMetrics) GetL2Misses() uint64 {
	if x != nil {
		return x.L2Misses
	}
	return 0
}

func (x *HostMetrics) GetWanBytesReceived() uint64 {
	if x != nil {
		return x.WanBytesReceived
	}
	return 0
}

func (x *HostMetrics) GetWanBytesSent() uint64 {
	if x != nil {
		return x.WanBytesSent
	}
	return 0
}

func (x *HostMetrics) GetL2SizeBytes() uint64 {
	if x != nil {
		return x.L2SizeBytes
	}
	return 0
}

type VMInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // cloning | starting | running | stopping | stopped | failed
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"` // OCI reference
	Generation    string                 `protobuf:"bytes,5,opt,name=generation,proto3" json:"generation,omitempty"`
	Ip            string                 `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created,proto3" json:"created,omitempty"`
	Started       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=started,proto3" json:"started,omitempty"`
	DiskBytes     uint64                 `protobuf:"varint,9,opt,name=disk_bytes,json=diskBytes,proto3" json:"disk_bytes,omitempty"`
	LastError     string                 `protobuf:"bytes,10,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMInfo) Reset() {
	*x = VMInfo{}
	mi := &file_cucina_v1_host_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMInfo) ProtoMessage() {}

func (x *VMInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMInfo.ProtoReflect.Descriptor instead.
func (*VMInfo) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{4}
}

func (x *VMInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMInfo) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *VMInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *VMInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *VMInfo) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *VMInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *VMInfo) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *VMInfo) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *VMInfo) GetDiskBytes() uint64 {
	if x != nil {
		return x.DiskBytes
	}
	return 0
}

func (x *VMInfo) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type VMEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vm            *VMInfo                `protobuf:"bytes,1,opt,name=vm,proto3" json:"vm,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"` // cloned | started | ready | stopped | deleted | failed | worker-registered
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMEvent) Reset() {
	*x = VMEvent{}
	mi := &file_cucina_v1_host_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMEvent) ProtoMessage() {}

func (x *VMEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMEvent.ProtoReflect.Descriptor instead.
func (*VMEvent) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{5}
}

func (x *VMEvent) GetVm() *VMInfo {
	if x != nil {
		return x.Vm
	}
	return nil
}

func (x *VMEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *VMEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VMEvent) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"` // small outputs only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_cucina_v1_host_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type LogData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // diagnostics streams reuse the command id
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Last          bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogData) Reset() {
	*x = LogData{}
	mi := &file_cucina_v1_host_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogData) ProtoMessage() {}

func (x *LogData) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogData.ProtoReflect.Descriptor instead.
func (*LogData) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{7}
}

func (x *LogData) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *LogData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogData) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControllerMessage_Welcome
	//	*ControllerMessage_StartVm
	//	*ControllerMessage_StopVm
	//	*ControllerMessage_DeleteVm
	//	*ControllerMessage_ReimageVm
	//	*ControllerMessage_PullImage
	//	*ControllerMessage_SetCordon
	//	*ControllerMessage_CollectDiagnostics
	//	*ControllerMessage_UpdateConfig
	//	*ControllerMessage_Ping
	Message       isControllerMessage_Message `protobuf_oneof:"message"`
	CommandId     string                      `protobuf:"bytes,20,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // echoed in CommandResult
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_cucina_v1_host_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{8}
}

func (x *ControllerMessage) GetMessage() isControllerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControllerMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ControllerMessage) GetStartVm() *StartVM {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_StartVm); ok {
			return x.StartVm
		}
	}
	return nil
}

func (x *ControllerMessage) GetStopVm() *StopVM {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_StopVm); ok {
			return x.StopVm
		}
	}
	return nil
}

func (x *ControllerMessage) GetDeleteVm() *DeleteVM {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_DeleteVm); ok {
			return x.DeleteVm
		}
	}
	return nil
}

func (x *ControllerMessage) GetReimageVm() *ReimageVM {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_ReimageVm); ok {
			return x.ReimageVm
		}
	}
	return nil
}

func (x *ControllerMessage) GetPullImage() *PullImage {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_PullImage); ok {
			return x.PullImage
		}
	}
	return nil
}

func (x *ControllerMessage) GetSetCordon() *SetCordon {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_SetCordon); ok {
			return x.SetCordon
		}
	}
	return nil
}

func (x *ControllerMessage) GetCollectDiagnostics() *CollectDiagnostics {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_CollectDiagnostics); ok {
			return x.CollectDiagnostics
		}
	}
	return nil
}

func (x *ControllerMessage) GetUpdateConfig() *UpdateHostConfig {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *ControllerMessage) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *ControllerMessage) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type isControllerMessage_Message interface {
	isControllerMessage_Message()
}

type ControllerMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ControllerMessage_StartVm struct {
	StartVm *StartVM `protobuf:"bytes,2,opt,name=start_vm,json=startVm,proto3,oneof"`
}

type ControllerMessage_StopVm struct {
	StopVm *StopVM `protobuf:"bytes,3,opt,name=stop_vm,json=stopVm,proto3,oneof"`
}

type ControllerMessage_DeleteVm struct {
	DeleteVm *DeleteVM `protobuf:"bytes,4,opt,name=delete_vm,json=deleteVm,proto3,oneof"`
}

type ControllerMessage_ReimageVm struct {
	ReimageVm *ReimageVM `protobuf:"bytes,5,opt,name=reimage_vm,json=reimageVm,proto3,oneof"`
}

type ControllerMessage_PullImage struct {
	PullImage *PullImage `protobuf:"bytes,6,opt,name=pull_image,json=pullImage,proto3,oneof"`
}

type ControllerMessage_SetCordon struct {
	SetCordon *SetCordon `protobuf:"bytes,7,opt,name=set_cordon,json=setCordon,proto3,oneof"`
}

type ControllerMessage_CollectDiagnostics struct {
	CollectDiagnostics *CollectDiagnostics `protobuf:"bytes,8,opt,name=collect_diagnostics,json=collectDiagnostics,proto3,oneof"`
}

type ControllerMessage_UpdateConfig struct {
	UpdateConfig *UpdateHostConfig `protobuf:"bytes,9,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type ControllerMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

func (*ControllerMessage_Welcome) isControllerMessage_Message() {}

func (*ControllerMessage_StartVm) isControllerMessage_Message() {}

func (*ControllerMessage_StopVm) isControllerMessage_Message() {}

func (*ControllerMessage_DeleteVm) isControllerMessage_Message() {}

func (*ControllerMessage_ReimageVm) isControllerMessage_Message() {}

func (*ControllerMessage_PullImage) isControllerMessage_Message() {}

func (*ControllerMessage_SetCordon) isControllerMessage_Message() {}

func (*ControllerMessage_CollectDiagnostics) isControllerMessage_Message() {}

func (*ControllerMessage_UpdateConfig) isControllerMessage_Message() {}

func (*ControllerMessage_Ping) isControllerMessage_Message() {}

type Welcome struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Protocol          *ProtocolVersion       `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClusterId         string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	HeartbeatInterval *durationpb.Duration   `protobuf:"bytes,3,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	DesiredImages     []string               `protobuf:"bytes,4,rep,name=desired_images,json=desiredImages,proto3" json:"desired_images,omitempty"`
	Slots             uint32                 `protobuf:"varint,5,opt,name=slots,proto3" json:"slots,omitempty"` // VMs per host (1-2)
	Settings          *HostSettings          `protobuf:"bytes,6,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_cucina_v1_host_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{9}
}

func (x *Welcome) GetProtocol() *ProtocolVersion {
	if x != nil {
		return x.Protocol
	}
	return nil
}

func (x *Welcome) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Welcome) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

func (x *Welcome) GetDesiredImages() []string {
	if x != nil {
		return x.DesiredImages
	}
	return nil
}

func (x *Welcome) GetSlots() uint32 {
	if x != nil {
		return x.Slots
	}
	return 0
}

func (x *Welcome) GetSettings() *HostSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// HostSettings are controller-provided overrides on top of the managed preferences.
type HostSettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	L2SizeGib         uint32                 `protobuf:"varint,1,opt,name=l2_size_gib,json=l2SizeGib,proto3" json:"l2_size_gib,omitempty"`
	LogLevel          string                 `protobuf:"bytes,2,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	VmCpu             uint32                 `protobuf:"varint,3,opt,name=vm_cpu,json=vmCpu,proto3" json:"vm_cpu,omitempty"`                                    // 0 = derive (cores-2)/slots
	VmMemoryGib       uint32                 `protobuf:"varint,4,opt,name=vm_memory_gib,json=vmMemoryGib,proto3" json:"vm_memory_gib,omitempty"`                // 0 = derive (RAM-8GB)/slots
	CentralEndpoint   string                 `protobuf:"bytes,5,opt,name=central_endpoint,json=centralEndpoint,proto3" json:"central_endpoint,omitempty"`       // worker endpoint for the L2 cache upstream
	SchedulerEndpoint string                 `protobuf:"bytes,6,opt,name=scheduler_endpoint,json=schedulerEndpoint,proto3" json:"scheduler_endpoint,omitempty"` // forwarded for VMs through hostd
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HostSettings) Reset() {
	*x = HostSettings{}
	mi := &file_cucina_v1_host_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostSettings) ProtoMessage() {}

func (x *HostSettings) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostSettings.ProtoReflect.Descriptor instead.
func (*HostSettings) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{10}
}

func (x *HostSettings) GetL2SizeGib() uint32 {
	if x != nil {
		return x.L2SizeGib
	}
	return 0
}

func (x *HostSettings) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *HostSettings) GetVmCpu() uint32 {
	if x != nil {
		return x.VmCpu
	}
	return 0
}

func (x *HostSettings) GetVmMemoryGib() uint32 {
	if x != nil {
		return x.VmMemoryGib
	}
	return 0
}

func (x *HostSettings) GetCentralEndpoint() string {
	if x != nil {
		return x.CentralEndpoint
	}
	return ""
}

func (x *HostSettings) GetSchedulerEndpoint() string {
	if x != nil {
		return x.SchedulerEndpoint
	}
	return ""
}

type StartVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"` // OCI reference
	Generation    string                 `protobuf:"bytes,4,opt,name=generation,proto3" json:"generation,omitempty"`
	Cpu           uint32                 `protobuf:"varint,5,opt,name=cpu,proto3" json:"cpu,omitempty"`
	MemoryGib     uint32                 `protobuf:"varint,6,opt,name=memory_gib,json=memoryGib,proto3" json:"memory_gib,omitempty"`
	DiskGib       uint32                 `protobuf:"varint,7,opt,name=disk_gib,json=diskGib,proto3" json:"disk_gib,omitempty"`
	Node          string                 `protobuf:"bytes,8,opt,name=node,proto3" json:"node,omitempty"`                             // "<host>/<vm>"
	XcodeSlot     uint32                 `protobuf:"varint,9,opt,name=xcode_slot,json=xcodeSlot,proto3" json:"xcode_slot,omitempty"` // runner concurrency hints are in WorkerSettings
	MaxAgeHours   uint32                 `protobuf:"varint,10,opt,name=max_age_hours,json=maxAgeHours,proto3" json:"max_age_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartVM) Reset() {
	*x = StartVM{}
	mi := &file_cucina_v1_host_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartVM) ProtoMessage() {}

func (x *StartVM) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartVM.ProtoReflect.Descriptor instead.
func (*StartVM) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{11}
}

func (x *StartVM) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *StartVM) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *StartVM) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *StartVM) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *StartVM) GetCpu() uint32 {
	if x != nil {
		return x.Cpu
	}
	return 0
}

func (x *StartVM) GetMemoryGib() uint32 {
	if x != nil {
		return x.MemoryGib
	}
	return 0
}

func (x *StartVM) GetDiskGib() uint32 {
	if x != nil {
		return x.DiskGib
	}
	return 0
}

func (x *StartVM) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *StartVM) GetXcodeSlot() uint32 {
	if x != nil {
		return x.XcodeSlot
	}
	return 0
}

func (x *StartVM) GetMaxAgeHours() uint32 {
	if x != nil {
		return x.MaxAgeHours
	}
	return 0
}

type StopVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"` // tart stop --timeout
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`   // idle | drain | rollout | maintenance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopVM) Reset() {
	*x = StopVM{}
	mi := &file_cucina_v1_host_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopVM) ProtoMessage() {}

func (x *StopVM) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopVM.ProtoReflect.Descriptor instead.
func (*StopVM) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{12}
}

func (x *StopVM) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *StopVM) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *StopVM) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type DeleteVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVM) Reset() {
	*x = DeleteVM{}
	mi := &file_cucina_v1_host_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVM) ProtoMessage() {}

func (x *DeleteVM) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVM.ProtoReflect.Descriptor instead.
func (*DeleteVM) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteVM) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

type ReimageVM struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"` // re-clone from the golden image at next start (or now if stopped)
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReimageVM) Reset() {
	*x = ReimageVM{}
	mi := &file_cucina_v1_host_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReimageVM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReimageVM) ProtoMessage() {}

func (x *ReimageVM) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReimageVM.ProtoReflect.Descriptor instead.
func (*ReimageVM) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{14}
}

func (x *ReimageVM) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *ReimageVM) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type PullImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullImage) Reset() {
	*x = PullImage{}
	mi := &file_cucina_v1_host_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullImage) ProtoMessage() {}

func (x *PullImage) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullImage.ProtoReflect.Descriptor instead.
func (*PullImage) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{15}
}

func (x *PullImage) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type SetCordon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cordoned      bool                   `protobuf:"varint,1,opt,name=cordoned,proto3" json:"cordoned,omitempty"` // true: drain (VMs shut down); false: uncordon
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCordon) Reset() {
	*x = SetCordon{}
	mi := &file_cucina_v1_host_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCordon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCordon) ProtoMessage() {}

func (x *SetCordon) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCordon.ProtoReflect.Descriptor instead.
func (*SetCordon) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{16}
}

func (x *SetCordon) GetCordoned() bool {
	if x != nil {
		return x.Cordoned
	}
	return false
}

type CollectDiagnostics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludeVmLogs bool                   `protobuf:"varint,1,opt,name=include_vm_logs,json=includeVmLogs,proto3" json:"include_vm_logs,omitempty"`
	// Optional scoping used by StreamWorkerLogs for Tart VMs: one VM, one unit
	// (bb-worker | bb-runner | agent), the last N lines, and whether to keep following.
	VmName        string `protobuf:"bytes,2,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Unit          string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	TailLines     uint32 `protobuf:"varint,4,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	Follow        bool   `protobuf:"varint,5,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectDiagnostics) Reset() {
	*x = CollectDiagnostics{}
	mi := &file_cucina_v1_host_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectDiagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectDiagnostics) ProtoMessage() {}

func (x *CollectDiagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectDiagnostics.ProtoReflect.Descriptor instead.
func (*CollectDiagnostics) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{17}
}

func (x *CollectDiagnostics) GetIncludeVmLogs() bool {
	if x != nil {
		return x.IncludeVmLogs
	}
	return false
}

func (x *CollectDiagnostics) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *CollectDiagnostics) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *CollectDiagnostics) GetTailLines() uint32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *CollectDiagnostics) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type UpdateHostConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *HostSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostConfig) Reset() {
	*x = UpdateHostConfig{}
	mi := &file_cucina_v1_host_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostConfig) ProtoMessage() {}

func (x *UpdateHostConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostConfig.ProtoReflect.Descriptor instead.
func (*UpdateHostConfig) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateHostConfig) GetSettings() *HostSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_cucina_v1_host_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{19}
}

type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        []byte                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_cucina_v1_host_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{20}
}

func (x *RenewCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RenewCertificateResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem []byte                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CaPem          []byte                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_cucina_v1_host_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{21}
}

func (x *RenewCertificateResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *RenewCertificateResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *RenewCertificateResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type IssueVMIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VmName        string                 `protobuf:"bytes,1,opt,name=vm_name,json=vmName,proto3" json:"vm_name,omitempty"`
	Pool          string                 `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
	CsrPem        []byte                 `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"` // key generated by hostd for the VM
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueVMIdentityRequest) Reset() {
	*x = IssueVMIdentityRequest{}
	mi := &file_cucina_v1_host_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVMIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVMIdentityRequest) ProtoMessage() {}

func (x *IssueVMIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVMIdentityRequest.ProtoReflect.Descriptor instead.
func (*IssueVMIdentityRequest) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{22}
}

func (x *IssueVMIdentityRequest) GetVmName() string {
	if x != nil {
		return x.VmName
	}
	return ""
}

func (x *IssueVMIdentityRequest) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

func (x *IssueVMIdentityRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type IssueVMIdentityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertificatePem []byte                 `protobuf:"bytes,1,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"` // URI SAN spiffe://cucina/worker/<pool>/<host>/<vm>, short-lived
	CaPem          []byte                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Settings       *WorkerSettings        `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IssueVMIdentityResponse) Reset() {
	*x = IssueVMIdentityResponse{}
	mi := &file_cucina_v1_host_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueVMIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueVMIdentityResponse) ProtoMessage() {}

func (x *IssueVMIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueVMIdentityResponse.ProtoReflect.Descriptor instead.
func (*IssueVMIdentityResponse) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{23}
}

func (x *IssueVMIdentityResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *IssueVMIdentityResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *IssueVMIdentityResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *IssueVMIdentityResponse) GetSettings() *WorkerSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetRegistryCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistryCredentialsRequest) Reset() {
	*x = GetRegistryCredentialsRequest{}
	mi := &file_cucina_v1_host_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistryCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistryCredentialsRequest) ProtoMessage() {}

func (x *GetRegistryCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistryCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetRegistryCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{24}
}

func (x *GetRegistryCredentialsRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type GetRegistryCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Host          string                 `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRegistryCredentialsResponse) Reset() {
	*x = GetRegistryCredentialsResponse{}
	mi := &file_cucina_v1_host_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRegistryCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRegistryCredentialsResponse) ProtoMessage() {}

func (x *GetRegistryCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cucina_v1_host_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRegistryCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetRegistryCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_cucina_v1_host_proto_rawDescGZIP(), []int{25}
}

func (x *GetRegistryCredentialsResponse) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GetRegistryCredentialsResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetRegistryCredentialsResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetRegistryCredentialsResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_cucina_v1_host_proto protoreflect.FileDescriptor

const file_cucina_v1_host_proto_rawDesc = "" +
	"\n" +
	"\x14cucina/v1/host.proto\x12\tcucina.v1\x1a\x16cucina/v1/common.proto\x1a\x1acucina/v1/enrollment.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\vHostMessage\x12(\n" +
	"\x05hello\x18\x01 \x01(\v2\x10.cucina.v1.HelloH\x00R\x05hello\x124\n" +
	"\theartbeat\x18\x02 \x01(\v2\x14.cucina.v1.HeartbeatH\x00R\theartbeat\x12/\n" +
	"\bvm_event\x18\x03 \x01(\v2\x12.cucina.v1.VMEventH\x00R\avmEvent\x12A\n" +
	"\x0ecommand_result\x18\x04 \x01(\v2\x18.cucina.v1.CommandResultH\x00R\rcommandResult\x12&\n" +
	"\x03log\x18\x05 \x01(\v2\x12.cucina.v1.LogDataH\x00R\x03logB\t\n" +
	"\amessage\"\xe6\x01\n" +
	"\x05Hello\x126\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1a.cucina.v1.ProtocolVersionR\bprotocol\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12*\n" +
	"\x05facts\x18\x03 \x01(\v2\x14.cucina.v1.HostFactsR\x05facts\x12#\n" +
	"\x03vms\x18\x04 \x03(\v2\x11.cucina.v1.VMInfoR\x03vms\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x17\n" +
	"\aboot_id\x18\x06 \x01(\tR\x06bootId\"\xae\x01\n" +
	"\tHeartbeat\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12#\n" +
	"\x03vms\x18\x02 \x03(\v2\x11.cucina.v1.VMInfoR\x03vms\x120\n" +
	"\ametrics\x18\x03 \x01(\v2\x16.cucina.v1.HostMetricsR\ametrics\x12\x1a\n" +
	"\bcordoned\x18\x04 \x01(\bR\bcordoned\"\x9f\x02\n" +
	"\vHostMetrics\x12\x1f\n" +
	"\vrunning_vms\x18\x01 \x01(\rR\n" +
	"runningVms\x12&\n" +
	"\x0fdisk_free_bytes\x18\x02 \x01(\x04R\rdiskFreeBytes\x12\x19\n" +
	"\bcpu_load\x18\x03 \x01(\x02R\acpuLoad\x12\x17\n" +
	"\al2_hits\x18\x04 \x01(\x04R\x06l2Hits\x12\x1b\n" +
	"\tl2_misses\x18\x05 \x01(\x04R\bl2Misses\x12,\n" +
	"\x12wan_bytes_received\x18\x06 \x01(\x04R\x10wanBytesReceived\x12$\n" +
	"\x0ewan_bytes_sent\x18\a \x01(\x04R\fwanBytesSent\x12\"\n" +
	"\rl2_size_bytes\x18\b \x01(\x04R\vl2SizeBytes\"\xb6\x02\n" +
	"\x06VMInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\tR\n" +
	"generation\x12\x0e\n" +
	"\x02ip\x18\x06 \x01(\tR\x02ip\x124\n" +
	"\acreated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x124\n" +
	"\astarted\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12\x1d\n" +
	"\n" +
	"disk_bytes\x18\t \x01(\x04R\tdiskBytes\x12\x1d\n" +
	"\n" +
	"last_error\x18\n" +
	" \x01(\tR\tlastError\"\x8c\x01\n" +
	"\aVMEvent\x12!\n" +
	"\x02vm\x18\x01 \x01(\v2\x11.cucina.v1.VMInfoR\x02vm\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12.\n" +
	"\x04time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"l\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\"P\n" +
	"\aLogData\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\"\xe2\x04\n" +
	"\x11ControllerMessage\x12.\n" +
	"\awelcome\x18\x01 \x01(\v2\x12.cucina.v1.WelcomeH\x00R\awelcome\x12/\n" +
	"\bstart_vm\x18\x02 \x01(\v2\x12.cucina.v1.StartVMH\x00R\astartVm\x12,\n" +
	"\astop_vm\x18\x03 \x01(\v2\x11.cucina.v1.StopVMH\x00R\x06stopVm\x122\n" +
	"\tdelete_vm\x18\x04 \x01(\v2\x13.cucina.v1.DeleteVMH\x00R\bdeleteVm\x125\n" +
	"\n" +
	"reimage_vm\x18\x05 \x01(\v2\x14.cucina.v1.ReimageVMH\x00R\treimageVm\x125\n" +
	"\n" +
	"pull_image\x18\x06 \x01(\v2\x14.cucina.v1.PullImageH\x00R\tpullImage\x125\n" +
	"\n" +
	"set_cordon\x18\a \x01(\v2\x14.cucina.v1.SetCordonH\x00R\tsetCordon\x12P\n" +
	"\x13collect_diagnostics\x18\b \x01(\v2\x1d.cucina.v1.CollectDiagnosticsH\x00R\x12collectDiagnostics\x12B\n" +
	"\rupdate_config\x18\t \x01(\v2\x1b.cucina.v1.UpdateHostConfigH\x00R\fupdateConfig\x12%\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x0f.cucina.v1.PingH\x00R\x04ping\x12\x1d\n" +
	"\n" +
	"command_id\x18\x14 \x01(\tR\tcommandIdB\t\n" +
	"\amessage\"\x9c\x02\n" +
	"\aWelcome\x126\n" +
	"\bprotocol\x18\x01 \x01(\v2\x1a.cucina.v1.ProtocolVersionR\bprotocol\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\x12H\n" +
	"\x12heartbeat_interval\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\x12%\n" +
	"\x0edesired_images\x18\x04 \x03(\tR\rdesiredImages\x12\x14\n" +
	"\x05slots\x18\x05 \x01(\rR\x05slots\x123\n" +
	"\bsettings\x18\x06 \x01(\v2\x17.cucina.v1.HostSettingsR\bsettings\"\xe0\x01\n" +
	"\fHostSettings\x12\x1e\n" +
	"\vl2_size_gib\x18\x01 \x01(\rR\tl2SizeGib\x12\x1b\n" +
	"\tlog_level\x18\x02 \x01(\tR\blogLevel\x12\x15\n" +
	"\x06vm_cpu\x18\x03 \x01(\rR\x05vmCpu\x12\"\n" +
	"\rvm_memory_gib\x18\x04 \x01(\rR\vvmMemoryGib\x12)\n" +
	"\x10central_endpoint\x18\x05 \x01(\tR\x0fcentralEndpoint\x12-\n" +
	"\x12scheduler_endpoint\x18\x06 \x01(\tR\x11schedulerEndpoint\"\x8f\x02\n" +
	"\aStartVM\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"generation\x18\x04 \x01(\tR\n" +
	"generation\x12\x10\n" +
	"\x03cpu\x18\x05 \x01(\rR\x03cpu\x12\x1d\n" +
	"\n" +
	"memory_gib\x18\x06 \x01(\rR\tmemoryGib\x12\x19\n" +
	"\bdisk_gib\x18\a \x01(\rR\adiskGib\x12\x12\n" +
	"\x04node\x18\b \x01(\tR\x04node\x12\x1d\n" +
	"\n" +
	"xcode_slot\x18\t \x01(\rR\txcodeSlot\x12\"\n" +
	"\rmax_age_hours\x18\n" +
	" \x01(\rR\vmaxAgeHours\"n\n" +
	"\x06StopVM\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"#\n" +
	"\bDeleteVM\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\":\n" +
	"\tReimageVM\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"!\n" +
	"\tPullImage\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"'\n" +
	"\tSetCordon\x12\x1a\n" +
	"\bcordoned\x18\x01 \x01(\bR\bcordoned\"\xa0\x01\n" +
	"\x12CollectDiagnostics\x12&\n" +
	"\x0finclude_vm_logs\x18\x01 \x01(\bR\rincludeVmLogs\x12\x17\n" +
	"\avm_name\x18\x02 \x01(\tR\x06vmName\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\tR\x04unit\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x04 \x01(\rR\ttailLines\x12\x16\n" +
	"\x06follow\x18\x05 \x01(\bR\x06follow\"G\n" +
	"\x10UpdateHostConfig\x123\n" +
	"\bsettings\x18\x01 \x01(\v2\x17.cucina.v1.HostSettingsR\bsettings\"\x06\n" +
	"\x04Ping\"2\n" +
	"\x17RenewCertificateRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\"\x95\x01\n" +
	"\x18RenewCertificateResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"^\n" +
	"\x16IssueVMIdentityRequest\x12\x17\n" +
	"\avm_name\x18\x01 \x01(\tR\x06vmName\x12\x12\n" +
	"\x04pool\x18\x02 \x01(\tR\x04pool\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\"\xcb\x01\n" +
	"\x17IssueVMIdentityResponse\x12'\n" +
	"\x0fcertificate_pem\x18\x01 \x01(\fR\x0ecertificatePem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x125\n" +
	"\bsettings\x18\x04 \x01(\v2\x19.cucina.v1.WorkerSettingsR\bsettings\"5\n" +
	"\x1dGetRegistryCredentialsRequest\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\"\xa7\x01\n" +
	"\x1eGetRegistryCredentialsResponse\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xf8\x02\n" +
	"\vHostService\x12C\n" +
	"\aConnect\x12\x16.cucina.v1.HostMessage\x1a\x1c.cucina.v1.ControllerMessage(\x010\x01\x12[\n" +
	"\x10RenewCertificate\x12\".cucina.v1.RenewCertificateRequest\x1a#.cucina.v1.RenewCertificateResponse\x12X\n" +
	"\x0fIssueVMIdentity\x12!.cucina.v1.IssueVMIdentityRequest\x1a\".cucina.v1.IssueVMIdentityResponse\x12m\n" +
	"\x16GetRegistryCredentials\x12(.cucina.v1.GetRegistryCredentialsRequest\x1a).cucina.v1.GetRegistryCredentialsResponseB:Z8github.com/sloper-ai/cucina/api/proto/cucina/v1;cucinav1b\x06proto3"

var (
	file_cucina_v1_host_proto_rawDescOnce sync.Once
	file_cucina_v1_host_proto_rawDescData []byte
)

func file_cucina_v1_host_proto_rawDescGZIP() []byte {
	file_cucina_v1_host_proto_rawDescOnce.Do(func() {
		file_cucina_v1_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cucina_v1_host_proto_rawDesc), len(file_cucina_v1_host_proto_rawDesc)))
	})
	return file_cucina_v1_host_proto_rawDescData
}

var file_cucina_v1_host_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_cucina_v1_host_proto_goTypes = []any{
	(*HostMessage)(nil),                    // 0: cucina.v1.HostMessage
	(*Hello)(nil),                          // 1: cucina.v1.Hello
	(*Heartbeat)(nil),                      // 2: cucina.v1.Heartbeat
	(*HostMetrics)(nil),                    // 3: cucina.v1.HostMetrics
	(*VMInfo)(nil),                         // 4: cucina.v1.VMInfo
	(*VMEvent)(nil),                        // 5: cucina.v1.VMEvent
	(*CommandResult)(nil),                  // 6: cucina.v1.CommandResult
	(*LogData)(nil),                        // 7: cucina.v1.LogData
	(*ControllerMessage)(nil),              // 8: cucina.v1.ControllerMessage
	(*Welcome)(nil),                        // 9: cucina.v1.Welcome
	(*HostSettings)(nil),                   // 10: cucina.v1.HostSettings
	(*StartVM)(nil),                        // 11: cucina.v1.StartVM
	(*StopVM)(nil),                         // 12: cucina.v1.StopVM
	(*DeleteVM)(nil),                       // 13: cucina.v1.DeleteVM
	(*ReimageVM)(nil),                      // 14: cucina.v1.ReimageVM
	(*PullImage)(nil),                      // 15: cucina.v1.PullImage
	(*SetCordon)(nil),                      // 16: cucina.v1.SetCordon
	(*CollectDiagnostics)(nil),             // 17: cucina.v1.CollectDiagnostics
	(*UpdateHostConfig)(nil),               // 18: cucina.v1.UpdateHostConfig
	(*Ping)(nil),                           // 19: cucina.v1.Ping
	(*RenewCertificateRequest)(nil),        // 20: cucina.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil),       // 21: cucina.v1.RenewCertificateResponse
	(*IssueVMIdentityRequest)(nil),         // 22: cucina.v1.IssueVMIdentityRequest
	(*IssueVMIdentityResponse)(nil),        // 23: cucina.v1.IssueVMIdentityResponse
	(*GetRegistryCredentialsRequest)(nil),  // 24: cucina.v1.GetRegistryCredentialsRequest
	(*GetRegistryCredentialsResponse)(nil), // 25: cucina.v1.GetRegistryCredentialsResponse
	(*ProtocolVersion)(nil),                // 26: cucina.v1.ProtocolVersion
	(*HostFacts)(nil),                      // 27: cucina.v1.HostFacts
	(*timestamppb.Timestamp)(nil),          // 28: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),            // 29: google.protobuf.Duration
	(*WorkerSettings)(nil),                 // 30: cucina.v1.WorkerSettings
}
var file_cucina_v1_host_proto_depIdxs = []int32{
	1,  // 0: cucina.v1.HostMessage.hello:type_name -> cucina.v1.Hello
	2,  // 1: cucina.v1.HostMessage.heartbeat:type_name -> cucina.v1.Heartbeat
	5,  // 2: cucina.v1.HostMessage.vm_event:type_name -> cucina.v1.VMEvent
	6,  // 3: cucina.v1.HostMessage.command_result:type_name -> cucina.v1.CommandResult
	7,  // 4: cucina.v1.HostMessage.log:type_name -> cucina.v1.LogData
	26, // 5: cucina.v1.Hello.protocol:type_name -> cucina.v1.ProtocolVersion
	27, // 6: cucina.v1.Hello.facts:type_name -> cucina.v1.HostFacts
	4,  // 7: cucina.v1.Hello.vms:type_name -> cucina.v1.VMInfo
	28, // 8: cucina.v1.Heartbeat.time:type_name -> google.protobuf.Timestamp
	4,  // 9: cucina.v1.Heartbeat.vms:type_name -> cucina.v1.VMInfo
	3,  // 10: cucina.v1.Heartbeat.metrics:type_name -> cucina.v1.HostMetrics
	28, // 11: cucina.v1.VMInfo.created:type_name -> google.protobuf.Timestamp
	28, // 12: cucina.v1.VMInfo.started:type_name -> google.protobuf.Timestamp
	4,  // 13: cucina.v1.VMEvent.vm:type_name -> cucina.v1.VMInfo
	28, // 14: cucina.v1.VMEvent.time:type_name -> google.protobuf.Timestamp
	9,  // 15: cucina.v1.ControllerMessage.welcome:type_name -> cucina.v1.Welcome
	11, // 16: cucina.v1.ControllerMessage.start_vm:type_name -> cucina.v1.StartVM
	12, // 17: cucina.v1.ControllerMessage.stop_vm:type_name -> cucina.v1.StopVM
	13, // 18: cucina.v1.ControllerMessage.delete_vm:type_name -> cucina.v1.DeleteVM
	14, // 19: cucina.v1.ControllerMessage.reimage_vm:type_name -> cucina.v1.ReimageVM
	15, // 20: cucina.v1.ControllerMessage.pull_image:type_name -> cucina.v1.PullImage
	16, // 21: cucina.v1.ControllerMessage.set_cordon:type_name -> cucina.v1.SetCordon
	17, // 22: cucina.v1.ControllerMessage.collect_diagnostics:type_name -> cucina.v1.CollectDiagnostics
	18, // 23: cucina.v1.ControllerMessage.update_config:type_name -> cucina.v1.UpdateHostConfig
	19, // 24: cucina.v1.ControllerMessage.ping:type_name -> cucina.v1.Ping
	26, // 25: cucina.v1.Welcome.protocol:type_name -> cucina.v1.ProtocolVersion
	29, // 26: cucina.v1.Welcome.heartbeat_interval:type_name -> google.protobuf.Duration
	10, // 27: cucina.v1.Welcome.settings:type_name -> cucina.v1.HostSettings
	29, // 28: cucina.v1.StopVM.timeout:type_name -> google.protobuf.Duration
	10, // 29: cucina.v1.UpdateHostConfig.settings:type_name -> cucina.v1.HostSettings
	28, // 30: cucina.v1.RenewCertificateResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 31: cucina.v1.IssueVMIdentityResponse.expires_at:type_name -> google.protobuf.Timestamp
	30, // 32: cucina.v1.IssueVMIdentityResponse.settings:type_name -> cucina.v1.WorkerSettings
	28, // 33: cucina.v1.GetRegistryCredentialsResponse.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 34: cucina.v1.HostService.Connect:input_type -> cucina.v1.HostMessage
	20, // 35: cucina.v1.HostService.RenewCertificate:input_type -> cucina.v1.RenewCertificateRequest
	22, // 36: cucina.v1.HostService.IssueVMIdentity:input_type -> cucina.v1.IssueVMIdentityRequest
	24, // 37: cucina.v1.HostService.GetRegistryCredentials:input_type -> cucina.v1.GetRegistryCredentialsRequest
	8,  // 38: cucina.v1.HostService.Connect:output_type -> cucina.v1.ControllerMessage
	21, // 39: cucina.v1.HostService.RenewCertificate:output_type -> cucina.v1.RenewCertificateResponse
	23, // 40: cucina.v1.HostService.IssueVMIdentity:output_type -> cucina.v1.IssueVMIdentityResponse
	25, // 41: cucina.v1.HostService.GetRegistryCredentials:output_type -> cucina.v1.GetRegistryCredentialsResponse
	38, // [38:42] is the sub-list for method output_type
	34, // [34:38] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_cucina_v1_host_proto_init() }
func file_cucina_v1_host_proto_init() {
	if File_cucina_v1_host_proto != nil {
		return
	}
	file_cucina_v1_common_proto_init()
	file_cucina_v1_enrollment_proto_init()
	file_cucina_v1_host_proto_msgTypes[0].OneofWrappers = []any{
		(*HostMessage_Hello)(nil),
		(*HostMessage_Heartbeat)(nil),
		(*HostMessage_VmEvent)(nil),
		(*HostMessage_CommandResult)(nil),
		(*HostMessage_Log)(nil),
	}
	file_cucina_v1_host_proto_msgTypes[8].OneofWrappers = []any{
		(*ControllerMessage_Welcome)(nil),
		(*ControllerMessage_StartVm)(nil),
		(*ControllerMessage_StopVm)(nil),
		(*ControllerMessage_DeleteVm)(nil),
		(*ControllerMessage_ReimageVm)(nil),
		(*ControllerMessage_PullImage)(nil),
		(*ControllerMessage_SetCordon)(nil),
		(*ControllerMessage_CollectDiagnostics)(nil),
		(*ControllerMessage_UpdateConfig)(nil),
		(*ControllerMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cucina_v1_host_proto_rawDesc), len(file_cucina_v1_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cucina_v1_host_proto_goTypes,
		DependencyIndexes: file_cucina_v1_host_proto_depIdxs,
		MessageInfos:      file_cucina_v1_host_proto_msgTypes,
	}.Build()
	File_cucina_v1_host_proto = out.File
	file_cucina_v1_host_proto_goTypes = nil
	file_cucina_v1_host_proto_depIdxs = nil
}
