// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cucina/v1/host.proto

package cucinav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostService_Connect_FullMethodName                = "/cucina.v1.HostService/Connect"
	HostService_RenewCertificate_FullMethodName       = "/cucina.v1.HostService/RenewCertificate"
	HostService_IssueVMIdentity_FullMethodName        = "/cucina.v1.HostService/IssueVMIdentity"
	HostService_GetRegistryCredentials_FullMethodName = "/cucina.v1.HostService/GetRegistryCredentials"
)

// HostServiceClient is the client API for HostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HostService is served by the controller over mTLS (client certificate = host
// identity, URI SAN spiffe://cucina/host/<serial>). cucina-hostd always dials OUT
// (works behind NAT) and reconnects with backoff. Hostd enforces the same safety
// rules itself (at most 2 running macOS VMs, dead-man switch) even if the controller
// is gone (R-POOL-7).
type HostServiceClient interface {
	// Connect is the long-lived bidirectional stream: hostd reports facts, VM state,
	// heartbeats and metrics; the controller sends commands (R-MAC-6).
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostMessage, ControllerMessage], error)
	// RenewCertificate issues a fresh host certificate before expiry (key unchanged or rotated by CSR).
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
	// IssueVMIdentity issues a short-lived worker identity and settings for one VM. VMs only
	// ever receive credentials through their host (R-MAC-4).
	IssueVMIdentity(ctx context.Context, in *IssueVMIdentityRequest, opts ...grpc.CallOption) (*IssueVMIdentityResponse, error)
	// GetRegistryCredentials returns short-lived (or read-only package) registry credentials
	// for pre-pulling Tart images; hostd passes them via TART_REGISTRY_* env vars, never the keychain.
	GetRegistryCredentials(ctx context.Context, in *GetRegistryCredentialsRequest, opts ...grpc.CallOption) (*GetRegistryCredentialsResponse, error)
}

type hostServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostServiceClient(cc grpc.ClientConnInterface) HostServiceClient {
	return &hostServiceClient{cc}
}

func (c *hostServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HostMessage, ControllerMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostService_ServiceDesc.Streams[0], HostService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostMessage, ControllerMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_ConnectClient = grpc.BidiStreamingClient[HostMessage, ControllerMessage]

func (c *hostServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, HostService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) IssueVMIdentity(ctx context.Context, in *IssueVMIdentityRequest, opts ...grpc.CallOption) (*IssueVMIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueVMIdentityResponse)
	err := c.cc.Invoke(ctx, HostService_IssueVMIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostServiceClient) GetRegistryCredentials(ctx context.Context, in *GetRegistryCredentialsRequest, opts ...grpc.CallOption) (*GetRegistryCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRegistryCredentialsResponse)
	err := c.cc.Invoke(ctx, HostService_GetRegistryCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostServiceServer is the server API for HostService service.
// All implementations must embed UnimplementedHostServiceServer
// for forward compatibility.
//
// HostService is served by the controller over mTLS (client certificate = host
// identity, URI SAN spiffe://cucina/host/<serial>). cucina-hostd always dials OUT
// (works behind NAT) and reconnects with backoff. Hostd enforces the same safety
// rules itself (at most 2 running macOS VMs, dead-man switch) even if the controller
// is gone (R-POOL-7).
type HostServiceServer interface {
	// Connect is the long-lived bidirectional stream: hostd reports facts, VM state,
	// heartbeats and metrics; the controller sends commands (R-MAC-6).
	Connect(grpc.BidiStreamingServer[HostMessage, ControllerMessage]) error
	// RenewCertificate issues a fresh host certificate before expiry (key unchanged or rotated by CSR).
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	// IssueVMIdentity issues a short-lived worker identity and settings for one VM. VMs only
	// ever receive credentials through their host (R-MAC-4).
	IssueVMIdentity(context.Context, *IssueVMIdentityRequest) (*IssueVMIdentityResponse, error)
	// GetRegistryCredentials returns short-lived (or read-only package) registry credentials
	// for pre-pulling Tart images; hostd passes them via TART_REGISTRY_* env vars, never the keychain.
	GetRegistryCredentials(context.Context, *GetRegistryCredentialsRequest) (*GetRegistryCredentialsResponse, error)
	mustEmbedUnimplementedHostServiceServer()
}

// UnimplementedHostServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostServiceServer struct{}

func (UnimplementedHostServiceServer) Connect(grpc.BidiStreamingServer[HostMessage, ControllerMessage]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedHostServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedHostServiceServer) IssueVMIdentity(context.Context, *IssueVMIdentityRequest) (*IssueVMIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueVMIdentity not implemented")
}
func (UnimplementedHostServiceServer) GetRegistryCredentials(context.Context, *GetRegistryCredentialsRequest) (*GetRegistryCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRegistryCredentials not implemented")
}
func (UnimplementedHostServiceServer) mustEmbedUnimplementedHostServiceServer() {}
func (UnimplementedHostServiceServer) testEmbeddedByValue()                     {}

// UnsafeHostServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostServiceServer will
// result in compilation errors.
type UnsafeHostServiceServer interface {
	mustEmbedUnimplementedHostServiceServer()
}

func RegisterHostServiceServer(s grpc.ServiceRegistrar, srv HostServiceServer) {
	// If the following call panics, it indicates UnimplementedHostServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostService_ServiceDesc, srv)
}

func _HostService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostServiceServer).Connect(&grpc.GenericServerStream[HostMessage, ControllerMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostService_ConnectServer = grpc.BidiStreamingServer[HostMessage, ControllerMessage]

func _HostService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_IssueVMIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueVMIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).IssueVMIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_IssueVMIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).IssueVMIdentity(ctx, req.(*IssueVMIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostService_GetRegistryCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRegistryCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostServiceServer).GetRegistryCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostService_GetRegistryCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostServiceServer).GetRegistryCredentials(ctx, req.(*GetRegistryCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostService_ServiceDesc is the grpc.ServiceDesc for HostService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cucina.v1.HostService",
	HandlerType: (*HostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenewCertificate",
			Handler:    _HostService_RenewCertificate_Handler,
		},
		{
			MethodName: "IssueVMIdentity",
			Handler:    _HostService_IssueVMIdentity_Handler,
		},
		{
			MethodName: "GetRegistryCredentials",
			Handler:    _HostService_GetRegistryCredentials_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _HostService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cucina/v1/host.proto",
}
