// SPDX-License-Identifier: FSL-1.1-ALv2

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: cucina/v1/management.proto

package cucinav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_GetStatus_FullMethodName            = "/cucina.v1.ManagementService/GetStatus"
	ManagementService_WatchOverview_FullMethodName        = "/cucina.v1.ManagementService/WatchOverview"
	ManagementService_ListPools_FullMethodName            = "/cucina.v1.ManagementService/ListPools"
	ManagementService_GetPool_FullMethodName              = "/cucina.v1.ManagementService/GetPool"
	ManagementService_SetPoolFloor_FullMethodName         = "/cucina.v1.ManagementService/SetPoolFloor"
	ManagementService_CordonPool_FullMethodName           = "/cucina.v1.ManagementService/CordonPool"
	ManagementService_GarbageCollectPool_FullMethodName   = "/cucina.v1.ManagementService/GarbageCollectPool"
	ManagementService_ListWorkers_FullMethodName          = "/cucina.v1.ManagementService/ListWorkers"
	ManagementService_DrainWorker_FullMethodName          = "/cucina.v1.ManagementService/DrainWorker"
	ManagementService_UndrainWorker_FullMethodName        = "/cucina.v1.ManagementService/UndrainWorker"
	ManagementService_StreamWorkerLogs_FullMethodName     = "/cucina.v1.ManagementService/StreamWorkerLogs"
	ManagementService_ListHosts_FullMethodName            = "/cucina.v1.ManagementService/ListHosts"
	ManagementService_DrainHost_FullMethodName            = "/cucina.v1.ManagementService/DrainHost"
	ManagementService_UncordonHost_FullMethodName         = "/cucina.v1.ManagementService/UncordonHost"
	ManagementService_ReimageHost_FullMethodName          = "/cucina.v1.ManagementService/ReimageHost"
	ManagementService_HostDiagnostics_FullMethodName      = "/cucina.v1.ManagementService/HostDiagnostics"
	ManagementService_RegisterHostSerials_FullMethodName  = "/cucina.v1.ManagementService/RegisterHostSerials"
	ManagementService_ApproveHost_FullMethodName          = "/cucina.v1.ManagementService/ApproveHost"
	ManagementService_RemoveHost_FullMethodName           = "/cucina.v1.ManagementService/RemoveHost"
	ManagementService_CreateEnrollToken_FullMethodName    = "/cucina.v1.ManagementService/CreateEnrollToken"
	ManagementService_ListEnrollTokens_FullMethodName     = "/cucina.v1.ManagementService/ListEnrollTokens"
	ManagementService_RevokeEnrollToken_FullMethodName    = "/cucina.v1.ManagementService/RevokeEnrollToken"
	ManagementService_ListQueues_FullMethodName           = "/cucina.v1.ManagementService/ListQueues"
	ManagementService_ListOperations_FullMethodName       = "/cucina.v1.ManagementService/ListOperations"
	ManagementService_WatchOperations_FullMethodName      = "/cucina.v1.ManagementService/WatchOperations"
	ManagementService_GetOperation_FullMethodName         = "/cucina.v1.ManagementService/GetOperation"
	ManagementService_KillOperations_FullMethodName       = "/cucina.v1.ManagementService/KillOperations"
	ManagementService_CreateServiceKey_FullMethodName     = "/cucina.v1.ManagementService/CreateServiceKey"
	ManagementService_ListServiceKeys_FullMethodName      = "/cucina.v1.ManagementService/ListServiceKeys"
	ManagementService_RevokeServiceKey_FullMethodName     = "/cucina.v1.ManagementService/RevokeServiceKey"
	ManagementService_RevokePrincipal_FullMethodName      = "/cucina.v1.ManagementService/RevokePrincipal"
	ManagementService_ListRevocations_FullMethodName      = "/cucina.v1.ManagementService/ListRevocations"
	ManagementService_GetCost_FullMethodName              = "/cucina.v1.ManagementService/GetCost"
	ManagementService_ListImages_FullMethodName           = "/cucina.v1.ManagementService/ListImages"
	ManagementService_CollectSupportBundle_FullMethodName = "/cucina.v1.ManagementService/CollectSupportBundle"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ManagementService is the controller's management API used by cucinactl
// (R-CLI-2). It is served on the controller's management port over TLS and
// authenticated with a Cucina JWT carrying the `admin` verb for mutating calls
// (R-AUTH-11); read-only calls need any valid Cucina JWT with `execute` or
// `admin` on at least one instance name, except the sensitive reads that are
// admin-only (worker logs, host diagnostics, support bundle, and the listings
// of service keys, enrollment tokens and revocations; see internal/mgmt, ADR 0580). Every mutating call is written to the
// audit log (principal, method, request summary, result; never secrets).
//
// The controller proxies BuildQueueState and Kubernetes state so the CLI never
// needs kubeconfig or cluster-internal access. Action inspection reads CAS/AC
// directly through the client endpoint with the user's own credentials; this API
// only maps operations to their action digest.
type ManagementServiceClient interface {
	// --- Overview -----------------------------------------------------------
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// WatchOverview streams a fresh Overview about every 2 s (TUI).
	WatchOverview(ctx context.Context, in *WatchOverviewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Overview], error)
	// --- Pools --------------------------------------------------------------
	ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error)
	GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error)
	// SetPoolFloor sets a temporary minRunning override (standing cost; expires).
	SetPoolFloor(ctx context.Context, in *SetPoolFloorRequest, opts ...grpc.CallOption) (*SetPoolFloorResponse, error)
	CordonPool(ctx context.Context, in *CordonPoolRequest, opts ...grpc.CallOption) (*CordonPoolResponse, error)
	// GarbageCollectPool sweeps orphaned volumes/ENIs carrying pool tags.
	GarbageCollectPool(ctx context.Context, in *GarbageCollectPoolRequest, opts ...grpc.CallOption) (*GarbageCollectPoolResponse, error)
	// --- Workers ------------------------------------------------------------
	ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error)
	DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error)
	UndrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error)
	// StreamWorkerLogs tails a worker's bb_worker/bb_runner logs (EC2: via SSM; Tart: via hostd).
	StreamWorkerLogs(ctx context.Context, in *StreamWorkerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// --- Hosts (macOS) ------------------------------------------------------
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error)
	DrainHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error)
	UncordonHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error)
	ReimageHost(ctx context.Context, in *ReimageHostRequest, opts ...grpc.CallOption) (*HostActionResponse, error)
	HostDiagnostics(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
	// RegisterHostSerials pre-registers (and approves) serial numbers, e.g. pasted from Apple Business.
	RegisterHostSerials(ctx context.Context, in *RegisterHostSerialsRequest, opts ...grpc.CallOption) (*RegisterHostSerialsResponse, error)
	ApproveHost(ctx context.Context, in *ApproveHostRequest, opts ...grpc.CallOption) (*HostActionResponse, error)
	RemoveHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error)
	// Site enrollment tokens (multi-use, expiring, revocable, bound to a site, max host count).
	CreateEnrollToken(ctx context.Context, in *CreateEnrollTokenRequest, opts ...grpc.CallOption) (*CreateEnrollTokenResponse, error)
	ListEnrollTokens(ctx context.Context, in *ListEnrollTokensRequest, opts ...grpc.CallOption) (*ListEnrollTokensResponse, error)
	RevokeEnrollToken(ctx context.Context, in *RevokeEnrollTokenRequest, opts ...grpc.CallOption) (*RevokeEnrollTokenResponse, error)
	// --- Queues and operations ---------------------------------------------
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error)
	// WatchOperations streams operation changes for a filter (until cancelled).
	WatchOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error)
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error)
	KillOperations(ctx context.Context, in *KillOperationsRequest, opts ...grpc.CallOption) (*KillOperationsResponse, error)
	// --- Identity -----------------------------------------------------------
	CreateServiceKey(ctx context.Context, in *CreateServiceKeyRequest, opts ...grpc.CallOption) (*CreateServiceKeyResponse, error)
	ListServiceKeys(ctx context.Context, in *ListServiceKeysRequest, opts ...grpc.CallOption) (*ListServiceKeysResponse, error)
	RevokeServiceKey(ctx context.Context, in *RevokeServiceKeyRequest, opts ...grpc.CallOption) (*RevokeServiceKeyResponse, error)
	// RevokePrincipal adds a sid or sub to the deny-list (effective in <= 3 min, R-AUTH-9).
	RevokePrincipal(ctx context.Context, in *RevokePrincipalRequest, opts ...grpc.CallOption) (*RevokePrincipalResponse, error)
	ListRevocations(ctx context.Context, in *ListRevocationsRequest, opts ...grpc.CallOption) (*ListRevocationsResponse, error)
	// --- Cost, images, diagnostics ----------------------------------------
	GetCost(ctx context.Context, in *GetCostRequest, opts ...grpc.CallOption) (*GetCostResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	// CollectSupportBundle streams a tar.gz support bundle (secrets redacted).
	CollectSupportBundle(ctx context.Context, in *CollectSupportBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) WatchOverview(ctx context.Context, in *WatchOverviewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Overview], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[0], ManagementService_WatchOverview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchOverviewRequest, Overview]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchOverviewClient = grpc.ServerStreamingClient[Overview]

func (c *managementServiceClient) ListPools(ctx context.Context, in *ListPoolsRequest, opts ...grpc.CallOption) (*ListPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoolsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetPool(ctx context.Context, in *GetPoolRequest, opts ...grpc.CallOption) (*GetPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPoolResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) SetPoolFloor(ctx context.Context, in *SetPoolFloorRequest, opts ...grpc.CallOption) (*SetPoolFloorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPoolFloorResponse)
	err := c.cc.Invoke(ctx, ManagementService_SetPoolFloor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CordonPool(ctx context.Context, in *CordonPoolRequest, opts ...grpc.CallOption) (*CordonPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CordonPoolResponse)
	err := c.cc.Invoke(ctx, ManagementService_CordonPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GarbageCollectPool(ctx context.Context, in *GarbageCollectPoolRequest, opts ...grpc.CallOption) (*GarbageCollectPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GarbageCollectPoolResponse)
	err := c.cc.Invoke(ctx, ManagementService_GarbageCollectPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListWorkers(ctx context.Context, in *ListWorkersRequest, opts ...grpc.CallOption) (*ListWorkersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkersResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListWorkers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainWorkerResponse)
	err := c.cc.Invoke(ctx, ManagementService_DrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UndrainWorker(ctx context.Context, in *DrainWorkerRequest, opts ...grpc.CallOption) (*DrainWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainWorkerResponse)
	err := c.cc.Invoke(ctx, ManagementService_UndrainWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) StreamWorkerLogs(ctx context.Context, in *StreamWorkerLogsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[1], ManagementService_StreamWorkerLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamWorkerLogsRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamWorkerLogsClient = grpc.ServerStreamingClient[LogChunk]

func (c *managementServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (*ListHostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListHostsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListHosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DrainHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, ManagementService_DrainHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UncordonHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, ManagementService_UncordonHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ReimageHost(ctx context.Context, in *ReimageHostRequest, opts ...grpc.CallOption) (*HostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, ManagementService_ReimageHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) HostDiagnostics(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[2], ManagementService_HostDiagnostics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HostRef, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_HostDiagnosticsClient = grpc.ServerStreamingClient[LogChunk]

func (c *managementServiceClient) RegisterHostSerials(ctx context.Context, in *RegisterHostSerialsRequest, opts ...grpc.CallOption) (*RegisterHostSerialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterHostSerialsResponse)
	err := c.cc.Invoke(ctx, ManagementService_RegisterHostSerials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ApproveHost(ctx context.Context, in *ApproveHostRequest, opts ...grpc.CallOption) (*HostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, ManagementService_ApproveHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RemoveHost(ctx context.Context, in *HostRef, opts ...grpc.CallOption) (*HostActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HostActionResponse)
	err := c.cc.Invoke(ctx, ManagementService_RemoveHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateEnrollToken(ctx context.Context, in *CreateEnrollTokenRequest, opts ...grpc.CallOption) (*CreateEnrollTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEnrollTokenResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateEnrollToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListEnrollTokens(ctx context.Context, in *ListEnrollTokensRequest, opts ...grpc.CallOption) (*ListEnrollTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEnrollTokensResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListEnrollTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RevokeEnrollToken(ctx context.Context, in *RevokeEnrollTokenRequest, opts ...grpc.CallOption) (*RevokeEnrollTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeEnrollTokenResponse)
	err := c.cc.Invoke(ctx, ManagementService_RevokeEnrollToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (*ListOperationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperationsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) WatchOperations(ctx context.Context, in *ListOperationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[OperationEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[3], ManagementService_WatchOperations_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListOperationsRequest, OperationEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchOperationsClient = grpc.ServerStreamingClient[OperationEvent]

func (c *managementServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) KillOperations(ctx context.Context, in *KillOperationsRequest, opts ...grpc.CallOption) (*KillOperationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KillOperationsResponse)
	err := c.cc.Invoke(ctx, ManagementService_KillOperations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateServiceKey(ctx context.Context, in *CreateServiceKeyRequest, opts ...grpc.CallOption) (*CreateServiceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceKeyResponse)
	err := c.cc.Invoke(ctx, ManagementService_CreateServiceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListServiceKeys(ctx context.Context, in *ListServiceKeysRequest, opts ...grpc.CallOption) (*ListServiceKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceKeysResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListServiceKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RevokeServiceKey(ctx context.Context, in *RevokeServiceKeyRequest, opts ...grpc.CallOption) (*RevokeServiceKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeServiceKeyResponse)
	err := c.cc.Invoke(ctx, ManagementService_RevokeServiceKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RevokePrincipal(ctx context.Context, in *RevokePrincipalRequest, opts ...grpc.CallOption) (*RevokePrincipalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokePrincipalResponse)
	err := c.cc.Invoke(ctx, ManagementService_RevokePrincipal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListRevocations(ctx context.Context, in *ListRevocationsRequest, opts ...grpc.CallOption) (*ListRevocationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRevocationsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListRevocations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetCost(ctx context.Context, in *GetCostRequest, opts ...grpc.CallOption) (*GetCostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCostResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetCost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CollectSupportBundle(ctx context.Context, in *CollectSupportBundleRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[LogChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ManagementService_ServiceDesc.Streams[4], ManagementService_CollectSupportBundle_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectSupportBundleRequest, LogChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_CollectSupportBundleClient = grpc.ServerStreamingClient[LogChunk]

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
//
// ManagementService is the controller's management API used by cucinactl
// (R-CLI-2). It is served on the controller's management port over TLS and
// authenticated with a Cucina JWT carrying the `admin` verb for mutating calls
// (R-AUTH-11); read-only calls need any valid Cucina JWT with `execute` or
// `admin` on at least one instance name, except the sensitive reads that are
// admin-only (worker logs, host diagnostics, support bundle, and the listings
// of service keys, enrollment tokens and revocations; see internal/mgmt, ADR 0580). Every mutating call is written to the
// audit log (principal, method, request summary, result; never secrets).
//
// The controller proxies BuildQueueState and Kubernetes state so the CLI never
// needs kubeconfig or cluster-internal access. Action inspection reads CAS/AC
// directly through the client endpoint with the user's own credentials; this API
// only maps operations to their action digest.
type ManagementServiceServer interface {
	// --- Overview -----------------------------------------------------------
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// WatchOverview streams a fresh Overview about every 2 s (TUI).
	WatchOverview(*WatchOverviewRequest, grpc.ServerStreamingServer[Overview]) error
	// --- Pools --------------------------------------------------------------
	ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error)
	GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error)
	// SetPoolFloor sets a temporary minRunning override (standing cost; expires).
	SetPoolFloor(context.Context, *SetPoolFloorRequest) (*SetPoolFloorResponse, error)
	CordonPool(context.Context, *CordonPoolRequest) (*CordonPoolResponse, error)
	// GarbageCollectPool sweeps orphaned volumes/ENIs carrying pool tags.
	GarbageCollectPool(context.Context, *GarbageCollectPoolRequest) (*GarbageCollectPoolResponse, error)
	// --- Workers ------------------------------------------------------------
	ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error)
	DrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error)
	UndrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error)
	// StreamWorkerLogs tails a worker's bb_worker/bb_runner logs (EC2: via SSM; Tart: via hostd).
	StreamWorkerLogs(*StreamWorkerLogsRequest, grpc.ServerStreamingServer[LogChunk]) error
	// --- Hosts (macOS) ------------------------------------------------------
	ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error)
	DrainHost(context.Context, *HostRef) (*HostActionResponse, error)
	UncordonHost(context.Context, *HostRef) (*HostActionResponse, error)
	ReimageHost(context.Context, *ReimageHostRequest) (*HostActionResponse, error)
	HostDiagnostics(*HostRef, grpc.ServerStreamingServer[LogChunk]) error
	// RegisterHostSerials pre-registers (and approves) serial numbers, e.g. pasted from Apple Business.
	RegisterHostSerials(context.Context, *RegisterHostSerialsRequest) (*RegisterHostSerialsResponse, error)
	ApproveHost(context.Context, *ApproveHostRequest) (*HostActionResponse, error)
	RemoveHost(context.Context, *HostRef) (*HostActionResponse, error)
	// Site enrollment tokens (multi-use, expiring, revocable, bound to a site, max host count).
	CreateEnrollToken(context.Context, *CreateEnrollTokenRequest) (*CreateEnrollTokenResponse, error)
	ListEnrollTokens(context.Context, *ListEnrollTokensRequest) (*ListEnrollTokensResponse, error)
	RevokeEnrollToken(context.Context, *RevokeEnrollTokenRequest) (*RevokeEnrollTokenResponse, error)
	// --- Queues and operations ---------------------------------------------
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error)
	// WatchOperations streams operation changes for a filter (until cancelled).
	WatchOperations(*ListOperationsRequest, grpc.ServerStreamingServer[OperationEvent]) error
	GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error)
	KillOperations(context.Context, *KillOperationsRequest) (*KillOperationsResponse, error)
	// --- Identity -----------------------------------------------------------
	CreateServiceKey(context.Context, *CreateServiceKeyRequest) (*CreateServiceKeyResponse, error)
	ListServiceKeys(context.Context, *ListServiceKeysRequest) (*ListServiceKeysResponse, error)
	RevokeServiceKey(context.Context, *RevokeServiceKeyRequest) (*RevokeServiceKeyResponse, error)
	// RevokePrincipal adds a sid or sub to the deny-list (effective in <= 3 min, R-AUTH-9).
	RevokePrincipal(context.Context, *RevokePrincipalRequest) (*RevokePrincipalResponse, error)
	ListRevocations(context.Context, *ListRevocationsRequest) (*ListRevocationsResponse, error)
	// --- Cost, images, diagnostics ----------------------------------------
	GetCost(context.Context, *GetCostRequest) (*GetCostResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	// CollectSupportBundle streams a tar.gz support bundle (secrets redacted).
	CollectSupportBundle(*CollectSupportBundleRequest, grpc.ServerStreamingServer[LogChunk]) error
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedManagementServiceServer) WatchOverview(*WatchOverviewRequest, grpc.ServerStreamingServer[Overview]) error {
	return status.Error(codes.Unimplemented, "method WatchOverview not implemented")
}
func (UnimplementedManagementServiceServer) ListPools(context.Context, *ListPoolsRequest) (*ListPoolsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPools not implemented")
}
func (UnimplementedManagementServiceServer) GetPool(context.Context, *GetPoolRequest) (*GetPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPool not implemented")
}
func (UnimplementedManagementServiceServer) SetPoolFloor(context.Context, *SetPoolFloorRequest) (*SetPoolFloorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPoolFloor not implemented")
}
func (UnimplementedManagementServiceServer) CordonPool(context.Context, *CordonPoolRequest) (*CordonPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CordonPool not implemented")
}
func (UnimplementedManagementServiceServer) GarbageCollectPool(context.Context, *GarbageCollectPoolRequest) (*GarbageCollectPoolResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GarbageCollectPool not implemented")
}
func (UnimplementedManagementServiceServer) ListWorkers(context.Context, *ListWorkersRequest) (*ListWorkersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkers not implemented")
}
func (UnimplementedManagementServiceServer) DrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainWorker not implemented")
}
func (UnimplementedManagementServiceServer) UndrainWorker(context.Context, *DrainWorkerRequest) (*DrainWorkerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndrainWorker not implemented")
}
func (UnimplementedManagementServiceServer) StreamWorkerLogs(*StreamWorkerLogsRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method StreamWorkerLogs not implemented")
}
func (UnimplementedManagementServiceServer) ListHosts(context.Context, *ListHostsRequest) (*ListHostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedManagementServiceServer) DrainHost(context.Context, *HostRef) (*HostActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainHost not implemented")
}
func (UnimplementedManagementServiceServer) UncordonHost(context.Context, *HostRef) (*HostActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UncordonHost not implemented")
}
func (UnimplementedManagementServiceServer) ReimageHost(context.Context, *ReimageHostRequest) (*HostActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReimageHost not implemented")
}
func (UnimplementedManagementServiceServer) HostDiagnostics(*HostRef, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method HostDiagnostics not implemented")
}
func (UnimplementedManagementServiceServer) RegisterHostSerials(context.Context, *RegisterHostSerialsRequest) (*RegisterHostSerialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterHostSerials not implemented")
}
func (UnimplementedManagementServiceServer) ApproveHost(context.Context, *ApproveHostRequest) (*HostActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveHost not implemented")
}
func (UnimplementedManagementServiceServer) RemoveHost(context.Context, *HostRef) (*HostActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveHost not implemented")
}
func (UnimplementedManagementServiceServer) CreateEnrollToken(context.Context, *CreateEnrollTokenRequest) (*CreateEnrollTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEnrollToken not implemented")
}
func (UnimplementedManagementServiceServer) ListEnrollTokens(context.Context, *ListEnrollTokensRequest) (*ListEnrollTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEnrollTokens not implemented")
}
func (UnimplementedManagementServiceServer) RevokeEnrollToken(context.Context, *RevokeEnrollTokenRequest) (*RevokeEnrollTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeEnrollToken not implemented")
}
func (UnimplementedManagementServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedManagementServiceServer) ListOperations(context.Context, *ListOperationsRequest) (*ListOperationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOperations not implemented")
}
func (UnimplementedManagementServiceServer) WatchOperations(*ListOperationsRequest, grpc.ServerStreamingServer[OperationEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchOperations not implemented")
}
func (UnimplementedManagementServiceServer) GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedManagementServiceServer) KillOperations(context.Context, *KillOperationsRequest) (*KillOperationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KillOperations not implemented")
}
func (UnimplementedManagementServiceServer) CreateServiceKey(context.Context, *CreateServiceKeyRequest) (*CreateServiceKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceKey not implemented")
}
func (UnimplementedManagementServiceServer) ListServiceKeys(context.Context, *ListServiceKeysRequest) (*ListServiceKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceKeys not implemented")
}
func (UnimplementedManagementServiceServer) RevokeServiceKey(context.Context, *RevokeServiceKeyRequest) (*RevokeServiceKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeServiceKey not implemented")
}
func (UnimplementedManagementServiceServer) RevokePrincipal(context.Context, *RevokePrincipalRequest) (*RevokePrincipalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokePrincipal not implemented")
}
func (UnimplementedManagementServiceServer) ListRevocations(context.Context, *ListRevocationsRequest) (*ListRevocationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRevocations not implemented")
}
func (UnimplementedManagementServiceServer) GetCost(context.Context, *GetCostRequest) (*GetCostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCost not implemented")
}
func (UnimplementedManagementServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedManagementServiceServer) CollectSupportBundle(*CollectSupportBundleRequest, grpc.ServerStreamingServer[LogChunk]) error {
	return status.Error(codes.Unimplemented, "method CollectSupportBundle not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_WatchOverview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchOverviewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).WatchOverview(m, &grpc.GenericServerStream[WatchOverviewRequest, Overview]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchOverviewServer = grpc.ServerStreamingServer[Overview]

func _ManagementService_ListPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListPools(ctx, req.(*ListPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetPool(ctx, req.(*GetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_SetPoolFloor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPoolFloorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).SetPoolFloor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_SetPoolFloor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).SetPoolFloor(ctx, req.(*SetPoolFloorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CordonPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CordonPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CordonPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CordonPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CordonPool(ctx, req.(*CordonPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GarbageCollectPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GarbageCollectPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GarbageCollectPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GarbageCollectPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GarbageCollectPool(ctx, req.(*GarbageCollectPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListWorkers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListWorkers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListWorkers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListWorkers(ctx, req.(*ListWorkersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DrainWorker(ctx, req.(*DrainWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UndrainWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UndrainWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UndrainWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UndrainWorker(ctx, req.(*DrainWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_StreamWorkerLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamWorkerLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).StreamWorkerLogs(m, &grpc.GenericServerStream[StreamWorkerLogsRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_StreamWorkerLogsServer = grpc.ServerStreamingServer[LogChunk]

func _ManagementService_ListHosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListHosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListHosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListHosts(ctx, req.(*ListHostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DrainHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DrainHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DrainHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DrainHost(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UncordonHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UncordonHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UncordonHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UncordonHost(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ReimageHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReimageHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ReimageHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ReimageHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ReimageHost(ctx, req.(*ReimageHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_HostDiagnostics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HostRef)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).HostDiagnostics(m, &grpc.GenericServerStream[HostRef, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_HostDiagnosticsServer = grpc.ServerStreamingServer[LogChunk]

func _ManagementService_RegisterHostSerials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterHostSerialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RegisterHostSerials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RegisterHostSerials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RegisterHostSerials(ctx, req.(*RegisterHostSerialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ApproveHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ApproveHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ApproveHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ApproveHost(ctx, req.(*ApproveHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RemoveHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HostRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RemoveHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RemoveHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RemoveHost(ctx, req.(*HostRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateEnrollToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEnrollTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateEnrollToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateEnrollToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateEnrollToken(ctx, req.(*CreateEnrollTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListEnrollTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEnrollTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListEnrollTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListEnrollTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListEnrollTokens(ctx, req.(*ListEnrollTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RevokeEnrollToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeEnrollTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RevokeEnrollToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RevokeEnrollToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RevokeEnrollToken(ctx, req.(*RevokeEnrollTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListOperations(ctx, req.(*ListOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_WatchOperations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListOperationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).WatchOperations(m, &grpc.GenericServerStream[ListOperationsRequest, OperationEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_WatchOperationsServer = grpc.ServerStreamingServer[OperationEvent]

func _ManagementService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_KillOperations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillOperationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).KillOperations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_KillOperations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).KillOperations(ctx, req.(*KillOperationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateServiceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateServiceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateServiceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateServiceKey(ctx, req.(*CreateServiceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListServiceKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListServiceKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListServiceKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListServiceKeys(ctx, req.(*ListServiceKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RevokeServiceKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeServiceKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RevokeServiceKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RevokeServiceKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RevokeServiceKey(ctx, req.(*RevokeServiceKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RevokePrincipal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokePrincipalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RevokePrincipal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RevokePrincipal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RevokePrincipal(ctx, req.(*RevokePrincipalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListRevocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRevocationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListRevocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListRevocations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListRevocations(ctx, req.(*ListRevocationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetCost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetCost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetCost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetCost(ctx, req.(*GetCostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CollectSupportBundle_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectSupportBundleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ManagementServiceServer).CollectSupportBundle(m, &grpc.GenericServerStream[CollectSupportBundleRequest, LogChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ManagementService_CollectSupportBundleServer = grpc.ServerStreamingServer[LogChunk]

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cucina.v1.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _ManagementService_GetStatus_Handler,
		},
		{
			MethodName: "ListPools",
			Handler:    _ManagementService_ListPools_Handler,
		},
		{
			MethodName: "GetPool",
			Handler:    _ManagementService_GetPool_Handler,
		},
		{
			MethodName: "SetPoolFloor",
			Handler:    _ManagementService_SetPoolFloor_Handler,
		},
		{
			MethodName: "CordonPool",
			Handler:    _ManagementService_CordonPool_Handler,
		},
		{
			MethodName: "GarbageCollectPool",
			Handler:    _ManagementService_GarbageCollectPool_Handler,
		},
		{
			MethodName: "ListWorkers",
			Handler:    _ManagementService_ListWorkers_Handler,
		},
		{
			MethodName: "DrainWorker",
			Handler:    _ManagementService_DrainWorker_Handler,
		},
		{
			MethodName: "UndrainWorker",
			Handler:    _ManagementService_UndrainWorker_Handler,
		},
		{
			MethodName: "ListHosts",
			Handler:    _ManagementService_ListHosts_Handler,
		},
		{
			MethodName: "DrainHost",
			Handler:    _ManagementService_DrainHost_Handler,
		},
		{
			MethodName: "UncordonHost",
			Handler:    _ManagementService_UncordonHost_Handler,
		},
		{
			MethodName: "ReimageHost",
			Handler:    _ManagementService_ReimageHost_Handler,
		},
		{
			MethodName: "RegisterHostSerials",
			Handler:    _ManagementService_RegisterHostSerials_Handler,
		},
		{
			MethodName: "ApproveHost",
			Handler:    _ManagementService_ApproveHost_Handler,
		},
		{
			MethodName: "RemoveHost",
			Handler:    _ManagementService_RemoveHost_Handler,
		},
		{
			MethodName: "CreateEnrollToken",
			Handler:    _ManagementService_CreateEnrollToken_Handler,
		},
		{
			MethodName: "ListEnrollTokens",
			Handler:    _ManagementService_ListEnrollTokens_Handler,
		},
		{
			MethodName: "RevokeEnrollToken",
			Handler:    _ManagementService_RevokeEnrollToken_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _ManagementService_ListQueues_Handler,
		},
		{
			MethodName: "ListOperations",
			Handler:    _ManagementService_ListOperations_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _ManagementService_GetOperation_Handler,
		},
		{
			MethodName: "KillOperations",
			Handler:    _ManagementService_KillOperations_Handler,
		},
		{
			MethodName: "CreateServiceKey",
			Handler:    _ManagementService_CreateServiceKey_Handler,
		},
		{
			MethodName: "ListServiceKeys",
			Handler:    _ManagementService_ListServiceKeys_Handler,
		},
		{
			MethodName: "RevokeServiceKey",
			Handler:    _ManagementService_RevokeServiceKey_Handler,
		},
		{
			MethodName: "RevokePrincipal",
			Handler:    _ManagementService_RevokePrincipal_Handler,
		},
		{
			MethodName: "ListRevocations",
			Handler:    _ManagementService_ListRevocations_Handler,
		},
		{
			MethodName: "GetCost",
			Handler:    _ManagementService_GetCost_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _ManagementService_ListImages_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchOverview",
			Handler:       _ManagementService_WatchOverview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamWorkerLogs",
			Handler:       _ManagementService_StreamWorkerLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HostDiagnostics",
			Handler:       _ManagementService_HostDiagnostics_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchOperations",
			Handler:       _ManagementService_WatchOperations_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CollectSupportBundle",
			Handler:       _ManagementService_CollectSupportBundle_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cucina/v1/management.proto",
}
