# SPDX-License-Identifier: Apache-2.0
# Ported from github.com/buildbarn/bb-deployments monitoring/prometheus/recording-rules.jsonnet
# (commit d4a6ca3, Apache-2.0, Copyright the Buildbarn authors). Changes for Cucina:
# selectors use the labels the chart's ServiceMonitors attach (cucina_buildbarn,
# cucina_component, kubernetes_service, kubernetes_shard, kubernetes_replica) instead of
# job="kubernetes-service-endpoints"/kubernetes_service="bb-storage|bb-scheduler"; the
# key-location-map rules read the lossymap metrics of bb-storage >= 2026-09-29
# (buildbarn_lossymap_hash_map_*{name="KeyLocationMap:<storage type>"}) and keep the
# recorded names the dashboards use; put_ignored_invalid no longer exists upstream.
groups:
  - name: buildbarn-recording-rules
    rules:
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_blob_size_bytes_count{cucina_buildbarn="true"}[1m])) by (backend_type, kubernetes_service, operation, storage_type)
        record: backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_find_missing_batch_size_count{cucina_buildbarn="true"}[1m])) by (backend_type, kubernetes_service, storage_type)
        labels:
          operation: FindMissing
        record: backend_type_kubernetes_service_operation_storage_type:buildbarn_blobstore_blob_access_operations_started:irate1m
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_duration_seconds_bucket{cucina_buildbarn="true"}[1m])) by (backend_type, kubernetes_service, le, operation, storage_type)
        record: backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_duration_seconds_count{cucina_buildbarn="true"}[1m])) by (backend_type, grpc_code, kubernetes_service, storage_type)
        record: backend_type_grpc_code_kubernetes_service_storage_type:buildbarn_blobstore_blob_access_operations_duration_seconds_count:irate1m
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket{cucina_buildbarn="true"}[1m])) by (backend_type, kubernetes_service, le, storage_type)
        record: backend_type_kubernetes_service_le_storage_type:buildbarn_blobstore_blob_access_operations_find_missing_batch_size_bucket:irate1m
      - expr: sum(irate(buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket{cucina_buildbarn="true"}[1m])) by (backend_type, kubernetes_service, le, operation, storage_type)
        record: backend_type_kubernetes_service_le_operation_storage_type:buildbarn_blobstore_blob_access_operations_blob_size_bytes_bucket:irate1m
      - expr: min(time() - buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds{cucina_component="storage"}) by (kubernetes_replica, kubernetes_shard, storage_type)
        record: kubernetes_replica_kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds
      - expr: min(kubernetes_replica_kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds) by (kubernetes_replica, storage_type)
        record: kubernetes_replica_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min
      - expr: max(kubernetes_replica_kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds) by (kubernetes_shard, storage_type)
        record: kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:max
      - expr: min(kubernetes_replica_kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds) by (kubernetes_shard, storage_type)
        record: kubernetes_shard_storage_type:buildbarn_blobstore_old_current_new_location_blob_map_last_removed_old_block_insertion_time_seconds:min
      - expr: sum by (outcome, storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_get_attempts_count{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_count:irate1m
      - expr: sum by (storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_get_too_many_attempts_total{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: storage_type:buildbarn_blobstore_hashing_key_location_map_get_too_many_attempts:irate1m
      - expr: sum by (le, storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_get_attempts_bucket{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: le_storage_type:buildbarn_blobstore_hashing_key_location_map_get_attempts_bucket:irate1m
      - expr: sum by (outcome, storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_put_iterations_count{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: outcome_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_count:irate1m
      - expr: sum by (storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_put_too_many_iterations_total{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: storage_type:buildbarn_blobstore_hashing_key_location_map_put_too_many_iterations:irate1m
      - expr: sum by (le, storage_type) (label_replace(irate(buildbarn_lossymap_hash_map_put_iterations_bucket{cucina_component="storage"}[1m]), "storage_type", "$1", "name", "KeyLocationMap:(.*)"))
        record: le_storage_type:buildbarn_blobstore_hashing_key_location_map_put_iterations_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_scheduled_total{cucina_component="scheduler"}[1m])) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_count{cucina_component="scheduler"}[1m])) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_count{cucina_component="scheduler"}[1m])) by (grpc_code, instance_name_prefix, platform, result, size_class)
        record: grpc_code_instance_name_prefix_platform_result_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_completed_duration_seconds_count{cucina_component="scheduler"}[1m])) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_removed:irate1m
      - expr: |-
          sum(buildbarn_builder_in_memory_build_queue_tasks_scheduled_total{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
          -
          sum(buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_count{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued:sum
      - expr: |-
          sum(buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_count{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
          -
          sum(buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_count{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing:sum
      - expr: |-
          sum(buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_count{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
          -
          sum(buildbarn_builder_in_memory_build_queue_tasks_completed_duration_seconds_count{cucina_component="scheduler"}) by (instance_name_prefix, platform, size_class)
        record: instance_name_prefix_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed:sum
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_bucket{cucina_component="scheduler"}[1m])) by (instance_name_prefix, le, platform, size_class)
        record: instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_queued_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_bucket{cucina_component="scheduler"}[1m])) by (instance_name_prefix, le, platform, size_class)
        record: instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_completed_duration_seconds_bucket{cucina_component="scheduler"}[1m])) by (instance_name_prefix, le, platform, size_class)
        record: instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_completed_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_in_memory_build_queue_tasks_executing_retries_bucket{cucina_component="scheduler"}[1m])) by (instance_name_prefix, le, platform, size_class)
        record: instance_name_prefix_le_platform_size_class:buildbarn_builder_in_memory_build_queue_tasks_executing_retries_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_duration_seconds_count{cucina_buildbarn="true"}[1m])) by (kubernetes_service)
        record: kubernetes_service:buildbarn_builder_build_executor_operations:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_duration_seconds_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le, stage)
        record: kubernetes_service_le_stage:buildbarn_builder_build_executor_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_virtual_execution_duration_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_virtual_execution_duration_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_user_time_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_user_time_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_system_time_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_system_time_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_maximum_resident_set_size_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_maximum_resident_set_size_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_page_reclaims_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_page_reclaims_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_page_faults_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_page_faults_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_swaps_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_swaps_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_block_input_operations_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_block_input_operations_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_block_output_operations_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_block_output_operations_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_messages_sent_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_messages_sent_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_messages_received_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_messages_received_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_signals_received_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_signals_received_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_voluntary_context_switches_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_voluntary_context_switches_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_posix_involuntary_context_switches_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_posix_involuntary_context_switches_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_file_pool_files_created_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_created_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_file_pool_files_count_peak_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_count_peak_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_file_pool_files_size_bytes_peak_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le)
        record: kubernetes_service_le:buildbarn_builder_build_executor_file_pool_files_size_bytes_peak_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_file_pool_operations_count_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le, operation)
        record: kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_count_bucket:irate1m
      - expr: sum(irate(buildbarn_builder_build_executor_file_pool_operations_size_bytes_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le, operation)
        record: kubernetes_service_le_operation:buildbarn_builder_build_executor_file_pool_operations_size_bytes_bucket:irate1m
      - expr: sum(rate(buildbarn_eviction_set_operations_total{cucina_buildbarn="true"}[1h])) by (kubernetes_service, name, operation)
        record: kubernetes_service_name_operation:buildbarn_eviction_set_operations:rate1h
      - expr: |-
          sum(
            grpc_client_started_total{cucina_buildbarn="true"}
            -
            sum(grpc_client_handled_total{cucina_buildbarn="true"}) without (grpc_code)
          ) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_client_in_flight:sum
      - expr: sum(irate(grpc_client_handled_total{cucina_buildbarn="true"}[1m])) by (grpc_code, grpc_method, grpc_service, kubernetes_service)
        record: grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_client_handled:irate1m
      - expr: sum(irate(grpc_client_msg_sent_total{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_client_msg_sent:irate1m
      - expr: sum(irate(grpc_client_msg_received_total{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_client_msg_received:irate1m
      - expr: sum(irate(grpc_client_handling_seconds_bucket{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service, le)
        record: grpc_method_grpc_service_kubernetes_service_le:grpc_client_handling_seconds_bucket:irate1m
      - expr: |-
          sum(
            grpc_server_started_total{cucina_buildbarn="true"}
            -
            sum(grpc_server_handled_total{cucina_buildbarn="true"}) without (grpc_code)
          ) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_server_in_flight:sum
      - expr: sum(irate(grpc_server_handled_total{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m
      - expr: sum(irate(grpc_server_handled_total{cucina_buildbarn="true"}[1m])) by (grpc_code, grpc_method, grpc_service, kubernetes_service)
        record: grpc_code_grpc_method_grpc_service_kubernetes_service:grpc_server_handled:irate1m
      - expr: sum(irate(grpc_server_msg_sent_total{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_server_msg_sent:irate1m
      - expr: sum(irate(grpc_server_msg_received_total{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service)
        record: grpc_method_grpc_service_kubernetes_service:grpc_server_msg_received:irate1m
      - expr: sum(irate(grpc_server_handling_seconds_bucket{cucina_buildbarn="true"}[1m])) by (grpc_method, grpc_service, kubernetes_service, le)
        record: grpc_method_grpc_service_kubernetes_service_le:grpc_server_handling_seconds_bucket:irate1m
      - expr: |-
          sum(
            irate(buildbarn_fuse_raw_file_system_callbacks_total{cucina_buildbarn="true"}[1m])
            or
            irate(buildbarn_fuse_raw_file_system_operations_duration_seconds_count{cucina_buildbarn="true"}[1m])
          ) by (status_code)
        record: status_code:buildbarn_fuse_raw_file_system_callbacks_and_operations:irate1m
      - expr: sum(irate(buildbarn_fuse_raw_file_system_operations_duration_seconds_count{cucina_buildbarn="true"}[1m])) by (kubernetes_service, operation, status_code)
        record: kubernetes_service_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_count:irate1m
      - expr: sum(irate(buildbarn_fuse_raw_file_system_operations_duration_seconds_bucket{cucina_buildbarn="true"}[1m])) by (kubernetes_service, le, operation, status_code)
        record: kubernetes_service_le_operation_status_code:buildbarn_fuse_raw_file_system_operations_duration_seconds_bucket:irate1m
      - expr: sum(irate(buildbarn_fuse_raw_file_system_callbacks_total{cucina_buildbarn="true"}[1m])) by (callback, kubernetes_service, status_code)
        record: callback_kubernetes_service_status_code:buildbarn_fuse_raw_file_system_callbacks:irate1m
