# SPDX-License-Identifier: FSL-1.1-ALv2
# Generated upstream source, used only at the test control-plane boundary (ADR 0112).

load("@rules_go//go:def.bzl", "go_library")

exports_files(
    ["server.go"],
    visibility = ["//tools/envtest:__pkg__"],
)

filegroup(
    name = "generated_sources",
    srcs = glob(["*.go"]) + [
        "LICENSE",
        "//internal/envtest/internal/flock:generated_sources",
        "//internal/envtest/internal/log:generated_sources",
        "//internal/envtest/internal/testing/addr:generated_sources",
        "//internal/envtest/internal/testing/certs:generated_sources",
        "//internal/envtest/internal/testing/controlplane:generated_sources",
        "//internal/envtest/internal/testing/process:generated_sources",
    ],
    visibility = ["//tools/envtest:__pkg__"],
)

go_library(
    name = "envtest",
    testonly = True,  # keep: this closure must never enter production binaries
    srcs = [
        "binaries.go",
        "crd.go",
        "doc.go",
        "helper.go",
        "server.go",
        "webhook.go",
    ],
    importpath = "github.com/sloper-ai/cucina/internal/envtest",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/envtest/internal/log",
        "//internal/envtest/internal/testing/addr",
        "//internal/envtest/internal/testing/certs",
        "//internal/envtest/internal/testing/controlplane",
        "//internal/envtest/internal/testing/process",
        "@io_k8s_api//admissionregistration/v1:admissionregistration",
        "@io_k8s_api//core/v1:core",
        "@io_k8s_apiextensions_apiserver//pkg/apis/apiextensions/v1:apiextensions",
        "@io_k8s_apiextensions_apiserver//pkg/client/clientset/clientset",
        "@io_k8s_apimachinery//pkg/api/errors",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/apis/meta/v1/unstructured",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/types",
        "@io_k8s_apimachinery//pkg/util/sets",
        "@io_k8s_apimachinery//pkg/util/version",
        "@io_k8s_apimachinery//pkg/util/wait",
        "@io_k8s_apimachinery//pkg/util/yaml",
        "@io_k8s_client_go//kubernetes/scheme",
        "@io_k8s_client_go//rest",
        "@io_k8s_client_go//util/retry",
        "@io_k8s_sigs_controller_runtime//pkg/client",
        "@io_k8s_sigs_controller_runtime//pkg/client/apiutil",
        "@io_k8s_sigs_controller_runtime//pkg/client/config",
        "@io_k8s_sigs_controller_runtime//pkg/webhook/conversion",
        "@io_k8s_sigs_yaml//:yaml",
    ],
)
