#!/usr/bin/env bash
# SPDX-License-Identifier: FSL-1.1-ALv2
#
# Writes the machine-local, gitignored `user.bazelrc` (loaded by `.bazelrc` via
# `try-import %workspace%/user.bazelrc`). It keeps Bazel's bulk data (output
# user root, disk cache, repository cache) on a storage volume of your choice and
# never in the committed `.bazelrc` (R-BUILD-4, §3).
#
# Usage: tools/setup-user-bazelrc.sh [STORAGE_DIR]
#   STORAGE_DIR defaults to $CUCINA_DEV_STORAGE/bazel, else ~/.cache/cucina/bazel.
# Env:   CUCINA_DISK_CACHE_MAX_SIZE (default 100G) caps the disk cache (GC'd by Bazel).
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
default_storage="${CUCINA_DEV_STORAGE:+${CUCINA_DEV_STORAGE}/bazel}"
storage="${1:-${default_storage:-${HOME}/.cache/cucina/bazel}}"
max_size="${CUCINA_DISK_CACHE_MAX_SIZE:-100G}"

mkdir -p "${storage}/output_user_root" "${storage}/disk_cache" "${storage}/repository_cache"

target="${repo_root}/user.bazelrc"
cat >"${target}.tmp" <<EOF
# Generated by tools/setup-user-bazelrc.sh — machine-local, gitignored. Re-run to regenerate.
startup --output_user_root=${storage}/output_user_root
# The repository cache (and Bazel's repo contents cache inside it) is shared by
# every output base on this machine, so per-agent output bases stay cheap.
common --repository_cache=${storage}/repository_cache
build --disk_cache=${storage}/disk_cache
build --experimental_disk_cache_gc_max_size=${max_size}
build --experimental_disk_cache_gc_max_age=21d
EOF
mv "${target}.tmp" "${target}"
echo "wrote ${target} (storage: ${storage})"
