# SPDX-License-Identifier: FSL-1.1-ALv2
load("//bazel:tiers.bzl", "cucina_go_test")

cucina_go_test(
    name = "boottest_test",
    timeout = "short",
    srcs = [
        "boot_test.go",
        "helpers_test.go",
        "hostl2_test.go",
        "roundtrip_test.go",
    ],
    runfiles_env = {
        "BB_RUNNER": "//tools:bb_runner",
        "BB_SCHEDULER": "//tools:bb_scheduler",
        "BB_STORAGE": "//tools:bb_storage",
        "BB_WORKER": "//tools:bb_worker",
    },
    tier = "integration",
    deps = [
        "//api/proto/cucina/v1:cucina",
        "//internal/bbconfig",
        "//internal/bbtest",
        "//internal/workeragent/hostos",
        "@com_github_bazelbuild_remote_apis//build/bazel/remote/execution/v2:execution",
        "@com_github_buildbarn_bb_remote_execution//pkg/proto/remoteworker",
        "@com_github_buildbarn_bb_storage//pkg/proto/blobstore/local",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_golang_google_grpc//:grpc",
        "@org_golang_google_grpc//codes",
        "@org_golang_google_grpc//credentials",
        "@org_golang_google_grpc//status",
        "@org_golang_google_protobuf//proto",
        "@org_golang_google_protobuf//types/known/emptypb",
        "@org_golang_google_protobuf//types/known/timestamppb",
    ],
)
