// SPDX-License-Identifier: FSL-1.1-ALv2

//! Local commands (no network): `bazelrc`, `config`, `completions`,
//! `credential-helper install`.

use std::io::{self, Write};
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Serialize;

use super::Ctx;
use crate::auth::ProfileCtx;
use crate::auth::secrets::SecretKind;
use crate::bazelrc::{self, Labels, Mode, Os};
use crate::catalog::Catalog;
use crate::cells;
use crate::cli::{BazelrcArgs, ConfigCmd};
use crate::config::{self, AuthMethod, CredentialStore};
use crate::exit::CliError;
use crate::output::{Render, dash, emit, state_cell, table, write_table};
use crate::views::ResultView;

/// `bazelrc.v1`.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct BazelrcView {
    /// `bazelrc` or `build-file`.
    pub kind: String,
    /// The exact text to paste.
    pub text: String,
}

impl Render for BazelrcView {
    const SCHEMA: &'static str = "bazelrc.v1";
    fn human(&self, out: &mut dyn Write) -> io::Result<()> {
        write!(out, "{}", self.text)
    }
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct TargetTestView {
    pub pool: String,
    pub runner: String,
    pub mode: String,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct TargetView {
    pub name: String,
    pub platform: String,
    pub os: String,
    pub cpu: String,
    pub abi: Option<String>,
    pub default_exec_pool: String,
    pub exec_pools: Vec<String>,
    pub test: Option<TargetTestView>,
}

/// `target-list.v1`.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct TargetListView {
    pub targets: Vec<TargetView>,
}

impl Render for TargetListView {
    const SCHEMA: &'static str = "target-list.v1";
    fn human(&self, out: &mut dyn Write) -> io::Result<()> {
        let mut t = table(&[
            "target",
            "compile on (default first)",
            "tests on",
            "platform",
        ]);
        for x in &self.targets {
            t.add_row(vec![
                x.name.clone(),
                x.exec_pools.join(", "),
                x.test.as_ref().map_or("- (build only)".into(), |t| {
                    format!("{}/{} ({})", t.pool, t.runner, t.mode)
                }),
                x.platform.clone(),
            ]);
        }
        write_table(out, &t, "no targets")
    }
}

fn helper_file_name() -> &'static str {
    if cfg!(windows) {
        "cucina-credential-helper.exe"
    } else {
        "cucina-credential-helper"
    }
}

/// The installed helper (next to this binary or on PATH), if any.
fn installed_helper() -> Option<PathBuf> {
    let name = helper_file_name();
    if let Some(dir) = std::env::current_exe()
        .ok()
        .and_then(|e| e.parent().map(Path::to_path_buf))
    {
        let p = dir.join(name);
        if p.is_file() {
            return Some(p);
        }
    }
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|d| d.join(name))
            .find(|p| p.is_file())
    })
}

fn default_disk_cache() -> Option<String> {
    dirs::cache_dir().map(|d| d.join("bazel-disk-cache").display().to_string())
}

pub fn bazelrc(ctx: &Ctx, args: &BazelrcArgs) -> Result<()> {
    let catalog = Catalog::embedded()?;
    let out = ctx.global.output;
    if args.list_targets {
        let targets = catalog
            .targets
            .targets
            .iter()
            .map(|t| {
                let pools: Vec<String> = t
                    .exec_platforms
                    .iter()
                    .filter_map(|n| catalog.exec_platform(n).map(|e| e.pool.clone()))
                    .collect();
                TargetView {
                    name: t.name.clone(),
                    platform: t.platform.clone(),
                    os: t.os.clone(),
                    cpu: t.cpu.clone(),
                    abi: t.abi.clone(),
                    default_exec_pool: pools.first().cloned().unwrap_or_default(),
                    exec_pools: pools,
                    test: t.test.as_ref().map(|x| TargetTestView {
                        pool: x.pool.clone(),
                        runner: x.runner.clone(),
                        mode: x.mode.clone(),
                    }),
                }
            })
            .collect();
        return emit(out, &TargetListView { targets });
    }
    let header_base = format!("Generated by cucinactl {}", crate::VERSION);
    if args.emit_build_file {
        let text = bazelrc::platforms_build_file(
            &catalog,
            &[
                format!("{header_base} (`cucinactl bazelrc --emit-build-file`)."),
                "Reference these with `cucinactl bazelrc --platforms-package //<this package>`."
                    .into(),
            ],
        );
        return emit(
            out,
            &BazelrcView {
                kind: "build-file".into(),
                text,
            },
        );
    }

    let pctx = ctx.profile()?;
    let p = &pctx.profile;
    let mode = if args.cross {
        Mode::Cross {
            target: args.target.clone().unwrap_or_default(),
            exec_pool: args.exec_pool.clone(),
        }
    } else {
        Mode::Native {
            os: args.platform.ok_or_else(|| {
                CliError::usage("pass --platform linux|windows|macos or --cross --target <P>")
            })?,
            exec_pool: args.exec_pool.clone(),
            xcode: args.xcode.clone(),
        }
    };
    let mut header = vec![format!(
        "{header_base} for profile {:?} ({}).",
        pctx.name, p.url
    )];
    let helper_path = match (&args.helper_path, installed_helper()) {
        (Some(h), _) => h.clone(),
        (None, Some(found)) => found.display().to_string(),
        (None, None) => {
            header.push(
                "cucina-credential-helper is not installed next to cucinactl or on PATH: create it with".into(),
            );
            header.push(
                "`cucinactl credential-helper install --dir tools` (or pass --helper-path).".into(),
            );
            "%workspace%/tools/cucina-credential-helper".into()
        }
    };
    if matches!(mode, Mode::Cross { .. } | Mode::Native { .. }) && args.platforms_package.is_none()
    {
        header.push(
            "Platform labels come from the @cucina_platforms Bazel module (docs/cli.md, Platforms).".into(),
        );
    }
    let req = bazelrc::Request {
        mode,
        endpoint: p.remote_executor.clone(),
        instance_name: p.instance_name.clone(),
        helper_path,
        ca_file: p.ca_file.as_ref().map(|c| c.display().to_string()),
        config_name: args.config_name.clone(),
        ci: args.ci,
        read_only: args.read_only,
        cache_only: args.cache_only,
        disk_cache: match args.disk_cache.as_deref() {
            Some("none") => None,
            Some(d) => Some(d.to_string()),
            None => default_disk_cache(),
        },
        disk_cache_max_size: args.disk_cache_max_size.clone(),
        client_os: args.client_os.unwrap_or_else(Os::current),
        labels: match &args.platforms_package {
            Some(pkg) => Labels::Package(pkg.clone()),
            None => Labels::Module,
        },
        header,
    };
    let rc = bazelrc::generate(&catalog, &req)?;
    emit(
        out,
        &BazelrcView {
            kind: "bazelrc".into(),
            text: rc.to_string(),
        },
    )
}

pub fn install_helper(ctx: &Ctx, dir: Option<PathBuf>) -> Result<()> {
    let exe = std::env::current_exe().context("locating cucinactl")?;
    let dir = match dir {
        Some(d) => d,
        None => exe
            .parent()
            .context("cucinactl has no parent directory")?
            .to_path_buf(),
    };
    std::fs::create_dir_all(&dir)?;
    let target = dir.join(helper_file_name());
    if target.exists() {
        std::fs::remove_file(&target).with_context(|| format!("replacing {}", target.display()))?;
    }
    let how = match std::fs::hard_link(&exe, &target) {
        Ok(()) => "hardlink",
        Err(_) => {
            std::fs::copy(&exe, &target)
                .with_context(|| format!("copying to {}", target.display()))?;
            "copy"
        }
    };
    emit(
        ctx.global.output,
        &ResultView::new(
            "install credential helper",
            &target.display().to_string(),
            format!("{how} of {}", exe.display()),
        ),
    )
}

pub fn completions(shell: clap_complete::Shell) -> Result<()> {
    let mut cmd = crate::cli::command();
    let mut script = Vec::new();
    clap_complete::generate(shell, &mut cmd, "cucinactl", &mut script);
    let mut out = io::stdout().lock();
    out.write_all(&script)?;
    out.flush()?;
    Ok(())
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct ProfileView {
    pub name: String,
    pub current: bool,
    pub url: String,
    pub remote_executor: String,
    pub instance_name: String,
    pub management: String,
    pub auth: AuthMethod,
    pub provider: Option<String>,
    pub ca_file: Option<String>,
    pub credential_store: CredentialStore,
    /// Whether a cached token is still valid.
    pub logged_in: bool,
    pub token_expires_at: Option<String>,
}

/// `config.v1`.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct ConfigView {
    pub config_dir: String,
    pub current_profile: Option<String>,
    pub profiles: Vec<ProfileView>,
}

impl Render for ConfigView {
    const SCHEMA: &'static str = "config.v1";
    fn human(&self, out: &mut dyn Write) -> io::Result<()> {
        writeln!(out, "Configuration directory: {}", self.config_dir)?;
        let mut t = table(&["", "profile", "url", "instance", "auth", "session"]);
        for p in &self.profiles {
            let session = if p.logged_in {
                state_cell(&format!(
                    "ok until {}",
                    dash(p.token_expires_at.as_deref().unwrap_or(""))
                ))
            } else {
                state_cell("expired or logged out")
            };
            t.add_row(cells![
                if p.current { "*" } else { "" },
                p.name.clone(),
                p.url.clone(),
                p.instance_name.clone(),
                match p.auth {
                    AuthMethod::Oidc => format!("oidc ({})", p.provider.as_deref().unwrap_or("-")),
                    AuthMethod::ServiceKey => "service key".into(),
                },
                session,
            ]);
        }
        write_table(out, &t, "no profiles; run `cucinactl login <url>`")
    }
}

/// `path.v1`.
#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct PathView {
    pub path: String,
}

impl Render for PathView {
    const SCHEMA: &'static str = "path.v1";
    fn human(&self, out: &mut dyn Write) -> io::Result<()> {
        writeln!(out, "{}", self.path)
    }
}

fn config_view(ctx: &Ctx) -> Result<ConfigView> {
    let cfg = ctx.config()?;
    let now = crate::util::now_unix();
    let profiles = cfg
        .profiles
        .iter()
        .map(|(name, p)| {
            let token = ProfileCtx::new(&ctx.paths, name, p).cache().read();
            ProfileView {
                name: name.clone(),
                current: cfg.current_profile.as_deref() == Some(name.as_str()),
                url: p.url.clone(),
                remote_executor: p.remote_executor.clone(),
                instance_name: p.instance_name.clone(),
                management: p.management.clone(),
                auth: p.auth,
                provider: p.provider.clone(),
                ca_file: p.ca_file.as_ref().map(|c| c.display().to_string()),
                credential_store: p.credential_store,
                logged_in: token.as_ref().is_some_and(|t| t.valid_for(now, 1)),
                token_expires_at: token.map(|t| crate::util::rfc3339_seconds(t.exp)),
            }
        })
        .collect();
    Ok(ConfigView {
        config_dir: ctx.paths.dir.display().to_string(),
        current_profile: cfg.current_profile.clone(),
        profiles,
    })
}

pub fn config(ctx: &Ctx, cmd: ConfigCmd) -> Result<()> {
    let out = ctx.global.output;
    match cmd {
        ConfigCmd::View | ConfigCmd::Profiles => emit(out, &config_view(ctx)?),
        ConfigCmd::Path => emit(
            out,
            &PathView {
                path: ctx.paths.dir.display().to_string(),
            },
        ),
        ConfigCmd::Use { name } => {
            let mut cfg = ctx.config()?;
            if !cfg.profiles.contains_key(&name) {
                return Err(CliError::not_found(format!("no profile named {name:?}")).into());
            }
            cfg.current_profile = Some(name.clone());
            cfg.save(&ctx.paths)?;
            emit(out, &ResultView::new("use profile", &name, ""))
        }
        ConfigCmd::Set { key, value } => {
            let mut cfg = ctx.config()?;
            let (name, mut p) = cfg.select(ctx.global.profile.as_deref())?;
            match key.as_str() {
                "instance-name" => p.instance_name = value.clone(),
                "management" => p.management = value.clone(),
                "remote-executor" => p.remote_executor = value.clone(),
                "ca-file" => p.ca_file = (!value.is_empty()).then(|| PathBuf::from(&value)),
                "credential-store" => {
                    p.credential_store = match value.as_str() {
                        "keyring" => CredentialStore::Keyring,
                        "file" => CredentialStore::File,
                        _ => {
                            return Err(
                                CliError::usage("credential-store is `keyring` or `file`").into()
                            );
                        }
                    }
                }
                other => {
                    return Err(CliError::usage(format!(
                        "unknown key {other:?} (instance-name, management, remote-executor, ca-file, credential-store)"
                    ))
                    .into());
                }
            }
            cfg.profiles.insert(name.clone(), p);
            cfg.save(&ctx.paths)?;
            emit(
                out,
                &ResultView::new("set", &format!("{name}.{key}"), value),
            )
        }
        ConfigCmd::Delete { name } => {
            let mut cfg = ctx.config()?;
            let Some(p) = cfg.profiles.remove(&name) else {
                return Err(CliError::not_found(format!("no profile named {name:?}")).into());
            };
            let pctx = ProfileCtx::new(&ctx.paths, &name, &p);
            pctx.cache().remove()?;
            if let Ok(secrets) = pctx.secrets() {
                for kind in [SecretKind::RefreshToken, SecretKind::ServiceKey] {
                    let _ = secrets.delete(&name, kind);
                }
            }
            config::remove_if_exists(&ctx.paths.discovery_file(&name))?;
            if cfg.current_profile.as_deref() == Some(name.as_str()) {
                cfg.current_profile = None;
            }
            cfg.save(&ctx.paths)?;
            emit(
                out,
                &ResultView::new("delete profile", &name, "local session removed"),
            )
        }
    }
}
