// SPDX-License-Identifier: FSL-1.1-ALv2

//! Build-system smoke test (R-BUILD-1): buffa messages and connect-rust stubs
//! generated by `cucina_proto_rust` compile into a working service handler.

use connectrpc::{RequestContext, Response, ServiceRequest, ServiceResult};
use hellopb_rs::connect::cucina::hello::v1::Greeter;
use hellopb_rs::proto::cucina::hello::v1::{HelloReply, HelloRequest};

/// Greets the caller by name ("world" when empty).
#[derive(Debug, Default)]
pub struct Server;

#[allow(refining_impl_trait)]
impl Greeter for Server {
    async fn say_hello(
        &self,
        _ctx: RequestContext,
        request: ServiceRequest<'_, HelloRequest>,
    ) -> ServiceResult<HelloReply> {
        let name = if request.name.is_empty() {
            "world"
        } else {
            request.name
        };
        Response::ok(HelloReply {
            message: format!("hello, {name}"),
            ..Default::default()
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use buffa::{Message, MessageView};
    use hellopb_rs::proto::cucina::hello::v1::HelloRequestView;

    // Guards R-BUILD-1: a request encoded with the generated buffa types is
    // decoded zero-copy and answered by a handler for the generated trait.
    #[tokio::test]
    async fn say_hello_greets_by_name() {
        for (name, want) in [("", "hello, world"), ("cucina", "hello, cucina")] {
            let request = HelloRequest {
                name: name.into(),
                ..Default::default()
            };
            let body = buffa::bytes::Bytes::from(request.encode_to_vec());
            let view = HelloRequestView::decode_view(&body).expect("decode view");
            let ctx = RequestContext::new(Default::default());
            let reply = Server
                .say_hello(ctx, ServiceRequest::from_parts(&view, &body))
                .await
                .expect("say_hello");
            assert_eq!(reply.body.message, want);
        }
    }
}
