// SPDX-License-Identifier: FSL-1.1-ALv2

//! Generated smoke-test API: buffa message types and connect-rust stubs
//! (checked in under gen/, regenerated by `cucina_proto_rust`).

/// buffa message types (`buffa_module=crate::proto`).
#[path = "gen/buffa/mod.rs"]
pub mod proto;

/// connect-rust service stubs.
#[path = "gen/connect/mod.rs"]
pub mod connect;
